apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-validator
  namespace: {{ .Values.namespace }}
  labels:
    role: validator
spec:
  replicas: {{ .Values.validator.replicas }}
  selector:
    matchLabels:
      role: validator
  template:
    metadata:
      labels:
        role: validator
    spec:
      containers:
        - name: validator-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - "chaind"
            - "start"
            - "--p2p.pex=false"
          ports:
            - containerPort: 26656
              name: p2p
          resources:
            requests:
              cpu: "{{ .Values.validator.resources.requests.cpu }}"
              memory: "{{ .Values.validator.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.validator.resources.limits.cpu }}"
              memory: "{{ .Values.validator.resources.limits.memory }}"
