// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: backend/v1/query.proto

package backendv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryService_GetBridgeVolume_FullMethodName        = "/backend.v1.QueryService/GetBridgeVolume"
	QueryService_GetValidatorUptime_FullMethodName     = "/backend.v1.QueryService/GetValidatorUptime"
	QueryService_GetOracleParticipation_FullMethodName = "/backend.v1.QueryService/GetOracleParticipation"
	QueryService_GetSettlement_FullMethodName          = "/backend.v1.QueryService/GetSettlement"
	QueryService_GetMilestoneStatus_FullMethodName     = "/backend.v1.QueryService/GetMilestoneStatus"
	QueryService_GetBridgePending_FullMethodName       = "/backend.v1.QueryService/GetBridgePending"
	QueryService_GetTps_FullMethodName                 = "/backend.v1.QueryService/GetTps"
	QueryService_GetBlockStats_FullMethodName          = "/backend.v1.QueryService/GetBlockStats"
	QueryService_GetOraclePrice_FullMethodName         = "/backend.v1.QueryService/GetOraclePrice"
	QueryService_ListSettlements_FullMethodName        = "/backend.v1.QueryService/ListSettlements"
	QueryService_ListMilestones_FullMethodName         = "/backend.v1.QueryService/ListMilestones"
	QueryService_GetBridgeTx_FullMethodName            = "/backend.v1.QueryService/GetBridgeTx"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryServiceClient interface {
	GetBridgeVolume(ctx context.Context, in *GetBridgeVolumeRequest, opts ...grpc.CallOption) (*GetBridgeVolumeResponse, error)
	GetValidatorUptime(ctx context.Context, in *GetValidatorUptimeRequest, opts ...grpc.CallOption) (*GetValidatorUptimeResponse, error)
	GetOracleParticipation(ctx context.Context, in *GetOracleParticipationRequest, opts ...grpc.CallOption) (*GetOracleParticipationResponse, error)
	GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*GetSettlementResponse, error)
	GetMilestoneStatus(ctx context.Context, in *GetMilestoneStatusRequest, opts ...grpc.CallOption) (*GetMilestoneStatusResponse, error)
	GetBridgePending(ctx context.Context, in *GetBridgePendingRequest, opts ...grpc.CallOption) (*GetBridgePendingResponse, error)
	GetTps(ctx context.Context, in *GetTpsRequest, opts ...grpc.CallOption) (*GetTpsResponse, error)
	GetBlockStats(ctx context.Context, in *GetBlockStatsRequest, opts ...grpc.CallOption) (*GetBlockStatsResponse, error)
	GetOraclePrice(ctx context.Context, in *GetOraclePriceRequest, opts ...grpc.CallOption) (*GetOraclePriceResponse, error)
	ListSettlements(ctx context.Context, in *ListSettlementsRequest, opts ...grpc.CallOption) (*ListSettlementsResponse, error)
	ListMilestones(ctx context.Context, in *ListMilestonesRequest, opts ...grpc.CallOption) (*ListMilestonesResponse, error)
	GetBridgeTx(ctx context.Context, in *GetBridgeTxRequest, opts ...grpc.CallOption) (*GetBridgeTxResponse, error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) GetBridgeVolume(ctx context.Context, in *GetBridgeVolumeRequest, opts ...grpc.CallOption) (*GetBridgeVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBridgeVolumeResponse)
	err := c.cc.Invoke(ctx, QueryService_GetBridgeVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetValidatorUptime(ctx context.Context, in *GetValidatorUptimeRequest, opts ...grpc.CallOption) (*GetValidatorUptimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValidatorUptimeResponse)
	err := c.cc.Invoke(ctx, QueryService_GetValidatorUptime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetOracleParticipation(ctx context.Context, in *GetOracleParticipationRequest, opts ...grpc.CallOption) (*GetOracleParticipationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOracleParticipationResponse)
	err := c.cc.Invoke(ctx, QueryService_GetOracleParticipation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*GetSettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettlementResponse)
	err := c.cc.Invoke(ctx, QueryService_GetSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetMilestoneStatus(ctx context.Context, in *GetMilestoneStatusRequest, opts ...grpc.CallOption) (*GetMilestoneStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMilestoneStatusResponse)
	err := c.cc.Invoke(ctx, QueryService_GetMilestoneStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetBridgePending(ctx context.Context, in *GetBridgePendingRequest, opts ...grpc.CallOption) (*GetBridgePendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBridgePendingResponse)
	err := c.cc.Invoke(ctx, QueryService_GetBridgePending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetTps(ctx context.Context, in *GetTpsRequest, opts ...grpc.CallOption) (*GetTpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTpsResponse)
	err := c.cc.Invoke(ctx, QueryService_GetTps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetBlockStats(ctx context.Context, in *GetBlockStatsRequest, opts ...grpc.CallOption) (*GetBlockStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockStatsResponse)
	err := c.cc.Invoke(ctx, QueryService_GetBlockStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetOraclePrice(ctx context.Context, in *GetOraclePriceRequest, opts ...grpc.CallOption) (*GetOraclePriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOraclePriceResponse)
	err := c.cc.Invoke(ctx, QueryService_GetOraclePrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ListSettlements(ctx context.Context, in *ListSettlementsRequest, opts ...grpc.CallOption) (*ListSettlementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSettlementsResponse)
	err := c.cc.Invoke(ctx, QueryService_ListSettlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ListMilestones(ctx context.Context, in *ListMilestonesRequest, opts ...grpc.CallOption) (*ListMilestonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMilestonesResponse)
	err := c.cc.Invoke(ctx, QueryService_ListMilestones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetBridgeTx(ctx context.Context, in *GetBridgeTxRequest, opts ...grpc.CallOption) (*GetBridgeTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBridgeTxResponse)
	err := c.cc.Invoke(ctx, QueryService_GetBridgeTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility.
type QueryServiceServer interface {
	GetBridgeVolume(context.Context, *GetBridgeVolumeRequest) (*GetBridgeVolumeResponse, error)
	GetValidatorUptime(context.Context, *GetValidatorUptimeRequest) (*GetValidatorUptimeResponse, error)
	GetOracleParticipation(context.Context, *GetOracleParticipationRequest) (*GetOracleParticipationResponse, error)
	GetSettlement(context.Context, *GetSettlementRequest) (*GetSettlementResponse, error)
	GetMilestoneStatus(context.Context, *GetMilestoneStatusRequest) (*GetMilestoneStatusResponse, error)
	GetBridgePending(context.Context, *GetBridgePendingRequest) (*GetBridgePendingResponse, error)
	GetTps(context.Context, *GetTpsRequest) (*GetTpsResponse, error)
	GetBlockStats(context.Context, *GetBlockStatsRequest) (*GetBlockStatsResponse, error)
	GetOraclePrice(context.Context, *GetOraclePriceRequest) (*GetOraclePriceResponse, error)
	ListSettlements(context.Context, *ListSettlementsRequest) (*ListSettlementsResponse, error)
	ListMilestones(context.Context, *ListMilestonesRequest) (*ListMilestonesResponse, error)
	GetBridgeTx(context.Context, *GetBridgeTxRequest) (*GetBridgeTxResponse, error)
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServiceServer struct{}

func (UnimplementedQueryServiceServer) GetBridgeVolume(context.Context, *GetBridgeVolumeRequest) (*GetBridgeVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBridgeVolume not implemented")
}
func (UnimplementedQueryServiceServer) GetValidatorUptime(context.Context, *GetValidatorUptimeRequest) (*GetValidatorUptimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValidatorUptime not implemented")
}
func (UnimplementedQueryServiceServer) GetOracleParticipation(context.Context, *GetOracleParticipationRequest) (*GetOracleParticipationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOracleParticipation not implemented")
}
func (UnimplementedQueryServiceServer) GetSettlement(context.Context, *GetSettlementRequest) (*GetSettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettlement not implemented")
}
func (UnimplementedQueryServiceServer) GetMilestoneStatus(context.Context, *GetMilestoneStatusRequest) (*GetMilestoneStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMilestoneStatus not implemented")
}
func (UnimplementedQueryServiceServer) GetBridgePending(context.Context, *GetBridgePendingRequest) (*GetBridgePendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBridgePending not implemented")
}
func (UnimplementedQueryServiceServer) GetTps(context.Context, *GetTpsRequest) (*GetTpsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTps not implemented")
}
func (UnimplementedQueryServiceServer) GetBlockStats(context.Context, *GetBlockStatsRequest) (*GetBlockStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockStats not implemented")
}
func (UnimplementedQueryServiceServer) GetOraclePrice(context.Context, *GetOraclePriceRequest) (*GetOraclePriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOraclePrice not implemented")
}
func (UnimplementedQueryServiceServer) ListSettlements(context.Context, *ListSettlementsRequest) (*ListSettlementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSettlements not implemented")
}
func (UnimplementedQueryServiceServer) ListMilestones(context.Context, *ListMilestonesRequest) (*ListMilestonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMilestones not implemented")
}
func (UnimplementedQueryServiceServer) GetBridgeTx(context.Context, *GetBridgeTxRequest) (*GetBridgeTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBridgeTx not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}
func (UnimplementedQueryServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	// If the following call panics, it indicates UnimplementedQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_GetBridgeVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBridgeVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetBridgeVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetBridgeVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetBridgeVolume(ctx, req.(*GetBridgeVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetValidatorUptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorUptimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetValidatorUptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetValidatorUptime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetValidatorUptime(ctx, req.(*GetValidatorUptimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetOracleParticipation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOracleParticipationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetOracleParticipation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetOracleParticipation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetOracleParticipation(ctx, req.(*GetOracleParticipationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetSettlement(ctx, req.(*GetSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetMilestoneStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMilestoneStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetMilestoneStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetMilestoneStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetMilestoneStatus(ctx, req.(*GetMilestoneStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetBridgePending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBridgePendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetBridgePending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetBridgePending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetBridgePending(ctx, req.(*GetBridgePendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetTps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetTps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetTps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetTps(ctx, req.(*GetTpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetBlockStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetBlockStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetBlockStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetBlockStats(ctx, req.(*GetBlockStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetOraclePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOraclePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetOraclePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetOraclePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetOraclePrice(ctx, req.(*GetOraclePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ListSettlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSettlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ListSettlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_ListSettlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ListSettlements(ctx, req.(*ListSettlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ListMilestones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMilestonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ListMilestones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_ListMilestones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ListMilestones(ctx, req.(*ListMilestonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetBridgeTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBridgeTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetBridgeTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetBridgeTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetBridgeTx(ctx, req.(*GetBridgeTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.v1.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBridgeVolume",
			Handler:    _QueryService_GetBridgeVolume_Handler,
		},
		{
			MethodName: "GetValidatorUptime",
			Handler:    _QueryService_GetValidatorUptime_Handler,
		},
		{
			MethodName: "GetOracleParticipation",
			Handler:    _QueryService_GetOracleParticipation_Handler,
		},
		{
			MethodName: "GetSettlement",
			Handler:    _QueryService_GetSettlement_Handler,
		},
		{
			MethodName: "GetMilestoneStatus",
			Handler:    _QueryService_GetMilestoneStatus_Handler,
		},
		{
			MethodName: "GetBridgePending",
			Handler:    _QueryService_GetBridgePending_Handler,
		},
		{
			MethodName: "GetTps",
			Handler:    _QueryService_GetTps_Handler,
		},
		{
			MethodName: "GetBlockStats",
			Handler:    _QueryService_GetBlockStats_Handler,
		},
		{
			MethodName: "GetOraclePrice",
			Handler:    _QueryService_GetOraclePrice_Handler,
		},
		{
			MethodName: "ListSettlements",
			Handler:    _QueryService_ListSettlements_Handler,
		},
		{
			MethodName: "ListMilestones",
			Handler:    _QueryService_ListMilestones_Handler,
		},
		{
			MethodName: "GetBridgeTx",
			Handler:    _QueryService_GetBridgeTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/v1/query.proto",
}
