// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: backend/v1/query.proto

package backendv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        []byte                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *PageRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    []byte                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetNextCursor() []byte {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

func (x *PageResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ListSettlementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageRequest           `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementsRequest) Reset() {
	*x = ListSettlementsRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementsRequest) ProtoMessage() {}

func (x *ListSettlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementsRequest.ProtoReflect.Descriptor instead.
func (*ListSettlementsRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *ListSettlementsRequest) GetPagination() *PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListSettlementsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Settlements   []*GetSettlementResponse `protobuf:"bytes,1,rep,name=settlements,proto3" json:"settlements,omitempty"`
	Pagination    *PageResponse            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementsResponse) Reset() {
	*x = ListSettlementsResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementsResponse) ProtoMessage() {}

func (x *ListSettlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementsResponse.ProtoReflect.Descriptor instead.
func (*ListSettlementsResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *ListSettlementsResponse) GetSettlements() []*GetSettlementResponse {
	if x != nil {
		return x.Settlements
	}
	return nil
}

func (x *ListSettlementsResponse) GetPagination() *PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMilestonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageRequest           `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMilestonesRequest) Reset() {
	*x = ListMilestonesRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMilestonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMilestonesRequest) ProtoMessage() {}

func (x *ListMilestonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMilestonesRequest.ProtoReflect.Descriptor instead.
func (*ListMilestonesRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *ListMilestonesRequest) GetPagination() *PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMilestonesResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Milestones    []*GetMilestoneStatusResponse `protobuf:"bytes,1,rep,name=milestones,proto3" json:"milestones,omitempty"`
	Pagination    *PageResponse                 `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMilestonesResponse) Reset() {
	*x = ListMilestonesResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMilestonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMilestonesResponse) ProtoMessage() {}

func (x *ListMilestonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMilestonesResponse.ProtoReflect.Descriptor instead.
func (*ListMilestonesResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *ListMilestonesResponse) GetMilestones() []*GetMilestoneStatusResponse {
	if x != nil {
		return x.Milestones
	}
	return nil
}

func (x *ListMilestonesResponse) GetPagination() *PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetBridgeTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBridgeTxRequest) Reset() {
	*x = GetBridgeTxRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBridgeTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBridgeTxRequest) ProtoMessage() {}

func (x *GetBridgeTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBridgeTxRequest.ProtoReflect.Descriptor instead.
func (*GetBridgeTxRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *GetBridgeTxRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GetBridgeTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BlockHeight   int64                  `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,4,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Sender        string                 `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,7,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBridgeTxResponse) Reset() {
	*x = GetBridgeTxResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBridgeTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBridgeTxResponse) ProtoMessage() {}

func (x *GetBridgeTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBridgeTxResponse.ProtoReflect.Descriptor instead.
func (*GetBridgeTxResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *GetBridgeTxResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetBridgeTxResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBridgeTxResponse) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *GetBridgeTxResponse) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetBridgeTxResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetBridgeTxResponse) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *GetBridgeTxResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

type GetBridgeVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Timeframe     string                 `protobuf:"bytes,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"` // e.g., "daily", "hourly"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBridgeVolumeRequest) Reset() {
	*x = GetBridgeVolumeRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBridgeVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBridgeVolumeRequest) ProtoMessage() {}

func (x *GetBridgeVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBridgeVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetBridgeVolumeRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *GetBridgeVolumeRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetBridgeVolumeRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetBridgeVolumeRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

type GetBridgeVolumeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalMinted      string                 `protobuf:"bytes,1,opt,name=total_minted,json=totalMinted,proto3" json:"total_minted,omitempty"`
	TotalBurned      string                 `protobuf:"bytes,2,opt,name=total_burned,json=totalBurned,proto3" json:"total_burned,omitempty"`
	VolumeUsd        string                 `protobuf:"bytes,3,opt,name=volume_usd,json=volumeUsd,proto3" json:"volume_usd,omitempty"`
	TransactionCount int64                  `protobuf:"varint,4,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBridgeVolumeResponse) Reset() {
	*x = GetBridgeVolumeResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBridgeVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBridgeVolumeResponse) ProtoMessage() {}

func (x *GetBridgeVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBridgeVolumeResponse.ProtoReflect.Descriptor instead.
func (*GetBridgeVolumeResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *GetBridgeVolumeResponse) GetTotalMinted() string {
	if x != nil {
		return x.TotalMinted
	}
	return ""
}

func (x *GetBridgeVolumeResponse) GetTotalBurned() string {
	if x != nil {
		return x.TotalBurned
	}
	return ""
}

func (x *GetBridgeVolumeResponse) GetVolumeUsd() string {
	if x != nil {
		return x.VolumeUsd
	}
	return ""
}

func (x *GetBridgeVolumeResponse) GetTransactionCount() int64 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

type GetValidatorUptimeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetValidatorUptimeRequest) Reset() {
	*x = GetValidatorUptimeRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidatorUptimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidatorUptimeRequest) ProtoMessage() {}

func (x *GetValidatorUptimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidatorUptimeRequest.ProtoReflect.Descriptor instead.
func (*GetValidatorUptimeRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *GetValidatorUptimeRequest) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

type GetValidatorUptimeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	TotalBlocks      int64                  `protobuf:"varint,2,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	MissedBlocks     int64                  `protobuf:"varint,3,opt,name=missed_blocks,json=missedBlocks,proto3" json:"missed_blocks,omitempty"`
	UptimePercentage float64                `protobuf:"fixed64,4,opt,name=uptime_percentage,json=uptimePercentage,proto3" json:"uptime_percentage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetValidatorUptimeResponse) Reset() {
	*x = GetValidatorUptimeResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidatorUptimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidatorUptimeResponse) ProtoMessage() {}

func (x *GetValidatorUptimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidatorUptimeResponse.ProtoReflect.Descriptor instead.
func (*GetValidatorUptimeResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *GetValidatorUptimeResponse) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *GetValidatorUptimeResponse) GetTotalBlocks() int64 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *GetValidatorUptimeResponse) GetMissedBlocks() int64 {
	if x != nil {
		return x.MissedBlocks
	}
	return 0
}

func (x *GetValidatorUptimeResponse) GetUptimePercentage() float64 {
	if x != nil {
		return x.UptimePercentage
	}
	return 0
}

type GetOracleParticipationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OracleAddress string                 `protobuf:"bytes,1,opt,name=oracle_address,json=oracleAddress,proto3" json:"oracle_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOracleParticipationRequest) Reset() {
	*x = GetOracleParticipationRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOracleParticipationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOracleParticipationRequest) ProtoMessage() {}

func (x *GetOracleParticipationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOracleParticipationRequest.ProtoReflect.Descriptor instead.
func (*GetOracleParticipationRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *GetOracleParticipationRequest) GetOracleAddress() string {
	if x != nil {
		return x.OracleAddress
	}
	return ""
}

type GetOracleParticipationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OracleAddress     string                 `protobuf:"bytes,1,opt,name=oracle_address,json=oracleAddress,proto3" json:"oracle_address,omitempty"`
	TotalRequests     int64                  `protobuf:"varint,2,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulReveals int64                  `protobuf:"varint,3,opt,name=successful_reveals,json=successfulReveals,proto3" json:"successful_reveals,omitempty"`
	ParticipationRate float64                `protobuf:"fixed64,4,opt,name=participation_rate,json=participationRate,proto3" json:"participation_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOracleParticipationResponse) Reset() {
	*x = GetOracleParticipationResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOracleParticipationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOracleParticipationResponse) ProtoMessage() {}

func (x *GetOracleParticipationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOracleParticipationResponse.ProtoReflect.Descriptor instead.
func (*GetOracleParticipationResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *GetOracleParticipationResponse) GetOracleAddress() string {
	if x != nil {
		return x.OracleAddress
	}
	return ""
}

func (x *GetOracleParticipationResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *GetOracleParticipationResponse) GetSuccessfulReveals() int64 {
	if x != nil {
		return x.SuccessfulReveals
	}
	return 0
}

func (x *GetOracleParticipationResponse) GetParticipationRate() float64 {
	if x != nil {
		return x.ParticipationRate
	}
	return 0
}

type GetSettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementRequest) Reset() {
	*x = GetSettlementRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementRequest) ProtoMessage() {}

func (x *GetSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementRequest.ProtoReflect.Descriptor instead.
func (*GetSettlementRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *GetSettlementRequest) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

type GetSettlementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	Proof         []byte                 `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	BlockHeight   int64                  `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Signatures    []string               `protobuf:"bytes,5,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementResponse) Reset() {
	*x = GetSettlementResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementResponse) ProtoMessage() {}

func (x *GetSettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementResponse.ProtoReflect.Descriptor instead.
func (*GetSettlementResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{15}
}

func (x *GetSettlementResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *GetSettlementResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *GetSettlementResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSettlementResponse) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *GetSettlementResponse) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type GetMilestoneStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MilestoneId   string                 `protobuf:"bytes,1,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMilestoneStatusRequest) Reset() {
	*x = GetMilestoneStatusRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMilestoneStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMilestoneStatusRequest) ProtoMessage() {}

func (x *GetMilestoneStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMilestoneStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMilestoneStatusRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{16}
}

func (x *GetMilestoneStatusRequest) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

type GetMilestoneStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MilestoneId   string                 `protobuf:"bytes,1,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BlockHeight   int64                  `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMilestoneStatusResponse) Reset() {
	*x = GetMilestoneStatusResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMilestoneStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMilestoneStatusResponse) ProtoMessage() {}

func (x *GetMilestoneStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMilestoneStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMilestoneStatusResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *GetMilestoneStatusResponse) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

func (x *GetMilestoneStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMilestoneStatusResponse) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

type GetBridgePendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBridgePendingRequest) Reset() {
	*x = GetBridgePendingRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBridgePendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBridgePendingRequest) ProtoMessage() {}

func (x *GetBridgePendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBridgePendingRequest.ProtoReflect.Descriptor instead.
func (*GetBridgePendingRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{18}
}

func (x *GetBridgePendingRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type GetBridgePendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient     string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBridgePendingResponse) Reset() {
	*x = GetBridgePendingResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBridgePendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBridgePendingResponse) ProtoMessage() {}

func (x *GetBridgePendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBridgePendingResponse.ProtoReflect.Descriptor instead.
func (*GetBridgePendingResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{19}
}

func (x *GetBridgePendingResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *GetBridgePendingResponse) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetBridgePendingResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetBridgePendingResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *GetBridgePendingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTpsRequest) Reset() {
	*x = GetTpsRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTpsRequest) ProtoMessage() {}

func (x *GetTpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTpsRequest.ProtoReflect.Descriptor instead.
func (*GetTpsRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{20}
}

type GetTpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TpsAvg        float64                `protobuf:"fixed64,1,opt,name=tps_avg,json=tpsAvg,proto3" json:"tps_avg,omitempty"`
	TpsPeak       float64                `protobuf:"fixed64,2,opt,name=tps_peak,json=tpsPeak,proto3" json:"tps_peak,omitempty"`
	TotalTxs      int64                  `protobuf:"varint,3,opt,name=total_txs,json=totalTxs,proto3" json:"total_txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTpsResponse) Reset() {
	*x = GetTpsResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTpsResponse) ProtoMessage() {}

func (x *GetTpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTpsResponse.ProtoReflect.Descriptor instead.
func (*GetTpsResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{21}
}

func (x *GetTpsResponse) GetTpsAvg() float64 {
	if x != nil {
		return x.TpsAvg
	}
	return 0
}

func (x *GetTpsResponse) GetTpsPeak() float64 {
	if x != nil {
		return x.TpsPeak
	}
	return 0
}

func (x *GetTpsResponse) GetTotalTxs() int64 {
	if x != nil {
		return x.TotalTxs
	}
	return 0
}

type GetBlockStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockStatsRequest) Reset() {
	*x = GetBlockStatsRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockStatsRequest) ProtoMessage() {}

func (x *GetBlockStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockStatsRequest.ProtoReflect.Descriptor instead.
func (*GetBlockStatsRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{22}
}

type GetBlockStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgMs         float64                `protobuf:"fixed64,1,opt,name=avg_ms,json=avgMs,proto3" json:"avg_ms,omitempty"`
	MaxMs         int64                  `protobuf:"varint,2,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockStatsResponse) Reset() {
	*x = GetBlockStatsResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockStatsResponse) ProtoMessage() {}

func (x *GetBlockStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockStatsResponse.ProtoReflect.Descriptor instead.
func (*GetBlockStatsResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{23}
}

func (x *GetBlockStatsResponse) GetAvgMs() float64 {
	if x != nil {
		return x.AvgMs
	}
	return 0
}

func (x *GetBlockStatsResponse) GetMaxMs() int64 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

type GetOraclePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOraclePriceRequest) Reset() {
	*x = GetOraclePriceRequest{}
	mi := &file_backend_v1_query_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOraclePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOraclePriceRequest) ProtoMessage() {}

func (x *GetOraclePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOraclePriceRequest.ProtoReflect.Descriptor instead.
func (*GetOraclePriceRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{24}
}

func (x *GetOraclePriceRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type GetOraclePriceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssetId         string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Open            float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High            float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low             float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close           float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	SubmissionCount int64                  `protobuf:"varint,6,opt,name=submission_count,json=submissionCount,proto3" json:"submission_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOraclePriceResponse) Reset() {
	*x = GetOraclePriceResponse{}
	mi := &file_backend_v1_query_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOraclePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOraclePriceResponse) ProtoMessage() {}

func (x *GetOraclePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_query_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOraclePriceResponse.ProtoReflect.Descriptor instead.
func (*GetOraclePriceResponse) Descriptor() ([]byte, []int) {
	return file_backend_v1_query_proto_rawDescGZIP(), []int{25}
}

func (x *GetOraclePriceResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *GetOraclePriceResponse) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *GetOraclePriceResponse) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *GetOraclePriceResponse) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *GetOraclePriceResponse) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *GetOraclePriceResponse) GetSubmissionCount() int64 {
	if x != nil {
		return x.SubmissionCount
	}
	return 0
}

var File_backend_v1_query_proto protoreflect.FileDescriptor

const file_backend_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x16backend/v1/query.proto\x12\n" +
	"backend.v1\x1a\x1cgoogle/api/annotations.proto\";\n" +
	"\vPageRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\fR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"J\n" +
	"\fPageResponse\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\fR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"Q\n" +
	"\x16ListSettlementsRequest\x127\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x17.backend.v1.PageRequestR\n" +
	"pagination\"\x98\x01\n" +
	"\x17ListSettlementsResponse\x12C\n" +
	"\vsettlements\x18\x01 \x03(\v2!.backend.v1.GetSettlementResponseR\vsettlements\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.backend.v1.PageResponseR\n" +
	"pagination\"P\n" +
	"\x15ListMilestonesRequest\x127\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x17.backend.v1.PageRequestR\n" +
	"pagination\"\x9a\x01\n" +
	"\x16ListMilestonesResponse\x12F\n" +
	"\n" +
	"milestones\x18\x01 \x03(\v2&.backend.v1.GetMilestoneStatusResponseR\n" +
	"milestones\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.backend.v1.PageResponseR\n" +
	"pagination\"-\n" +
	"\x12GetBridgeTxRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"\xdc\x01\n" +
	"\x13GetBridgeTxResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fblock_height\x18\x03 \x01(\x03R\vblockHeight\x12#\n" +
	"\rtoken_address\x18\x04 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x16\n" +
	"\x06sender\x18\x06 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\a \x01(\tR\trecipient\"v\n" +
	"\x16GetBridgeVolumeRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\tR\ttimeframe\"\xab\x01\n" +
	"\x17GetBridgeVolumeResponse\x12!\n" +
	"\ftotal_minted\x18\x01 \x01(\tR\vtotalMinted\x12!\n" +
	"\ftotal_burned\x18\x02 \x01(\tR\vtotalBurned\x12\x1d\n" +
	"\n" +
	"volume_usd\x18\x03 \x01(\tR\tvolumeUsd\x12+\n" +
	"\x11transaction_count\x18\x04 \x01(\x03R\x10transactionCount\"H\n" +
	"\x19GetValidatorUptimeRequest\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\"\xbe\x01\n" +
	"\x1aGetValidatorUptimeResponse\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\x12!\n" +
	"\ftotal_blocks\x18\x02 \x01(\x03R\vtotalBlocks\x12#\n" +
	"\rmissed_blocks\x18\x03 \x01(\x03R\fmissedBlocks\x12+\n" +
	"\x11uptime_percentage\x18\x04 \x01(\x01R\x10uptimePercentage\"F\n" +
	"\x1dGetOracleParticipationRequest\x12%\n" +
	"\x0eoracle_address\x18\x01 \x01(\tR\roracleAddress\"\xcc\x01\n" +
	"\x1eGetOracleParticipationResponse\x12%\n" +
	"\x0eoracle_address\x18\x01 \x01(\tR\roracleAddress\x12%\n" +
	"\x0etotal_requests\x18\x02 \x01(\x03R\rtotalRequests\x12-\n" +
	"\x12successful_reveals\x18\x03 \x01(\x03R\x11successfulReveals\x12-\n" +
	"\x12participation_rate\x18\x04 \x01(\x01R\x11participationRate\";\n" +
	"\x14GetSettlementRequest\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\"\xad\x01\n" +
	"\x15GetSettlementResponse\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fblock_height\x18\x04 \x01(\x03R\vblockHeight\x12\x1e\n" +
	"\n" +
	"signatures\x18\x05 \x03(\tR\n" +
	"signatures\">\n" +
	"\x19GetMilestoneStatusRequest\x12!\n" +
	"\fmilestone_id\x18\x01 \x01(\tR\vmilestoneId\"z\n" +
	"\x1aGetMilestoneStatusResponse\x12!\n" +
	"\fmilestone_id\x18\x01 \x01(\tR\vmilestoneId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fblock_height\x18\x03 \x01(\x03R\vblockHeight\"/\n" +
	"\x17GetBridgePendingRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\xa3\x01\n" +
	"\x18GetBridgePendingResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x0f\n" +
	"\rGetTpsRequest\"a\n" +
	"\x0eGetTpsResponse\x12\x17\n" +
	"\atps_avg\x18\x01 \x01(\x01R\x06tpsAvg\x12\x19\n" +
	"\btps_peak\x18\x02 \x01(\x01R\atpsPeak\x12\x1b\n" +
	"\ttotal_txs\x18\x03 \x01(\x03R\btotalTxs\"\x16\n" +
	"\x14GetBlockStatsRequest\"E\n" +
	"\x15GetBlockStatsResponse\x12\x15\n" +
	"\x06avg_ms\x18\x01 \x01(\x01R\x05avgMs\x12\x15\n" +
	"\x06max_ms\x18\x02 \x01(\x03R\x05maxMs\"2\n" +
	"\x15GetOraclePriceRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"\xae\x01\n" +
	"\x16GetOraclePriceResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12)\n" +
	"\x10submission_count\x18\x06 \x01(\x03R\x0fsubmissionCount2\xe2\f\n" +
	"\fQueryService\x12~\n" +
	"\x0fGetBridgeVolume\x12\".backend.v1.GetBridgeVolumeRequest\x1a#.backend.v1.GetBridgeVolumeResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/rest/v1/bridge/volume\x12\x9e\x01\n" +
	"\x12GetValidatorUptime\x12%.backend.v1.GetValidatorUptimeRequest\x1a&.backend.v1.GetValidatorUptimeResponse\"9\x82\xd3\xe4\x93\x023\x121/api/rest/v1/validator/uptime/{validator_address}\x12\xab\x01\n" +
	"\x16GetOracleParticipation\x12).backend.v1.GetOracleParticipationRequest\x1a*.backend.v1.GetOracleParticipationResponse\":\x82\xd3\xe4\x93\x024\x122/api/rest/v1/oracle/participation/{oracle_address}\x12\x85\x01\n" +
	"\rGetSettlement\x12 .backend.v1.GetSettlementRequest\x1a!.backend.v1.GetSettlementResponse\"/\x82\xd3\xe4\x93\x02)\x12'/api/rest/v1/settlement/{settlement_id}\x12\x92\x01\n" +
	"\x12GetMilestoneStatus\x12%.backend.v1.GetMilestoneStatusRequest\x1a&.backend.v1.GetMilestoneStatusResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/rest/v1/milestone/{milestone_id}\x12\x8a\x01\n" +
	"\x10GetBridgePending\x12#.backend.v1.GetBridgePendingRequest\x1a$.backend.v1.GetBridgePendingResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/rest/v1/bridge/pending/{nonce}\x12c\n" +
	"\x06GetTps\x12\x19.backend.v1.GetTpsRequest\x1a\x1a.backend.v1.GetTpsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/rest/v1/analytics/tps\x12{\n" +
	"\rGetBlockStats\x12 .backend.v1.GetBlockStatsRequest\x1a!.backend.v1.GetBlockStatsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/rest/v1/analytics/blocks\x12\x84\x01\n" +
	"\x0eGetOraclePrice\x12!.backend.v1.GetOraclePriceRequest\x1a\".backend.v1.GetOraclePriceResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/rest/v1/analytics/oracle/price\x12|\n" +
	"\x0fListSettlements\x12\".backend.v1.ListSettlementsRequest\x1a#.backend.v1.ListSettlementsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/rest/v1/settlements\x12x\n" +
	"\x0eListMilestones\x12!.backend.v1.ListMilestonesRequest\x1a\".backend.v1.ListMilestonesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/rest/v1/milestones\x12x\n" +
	"\vGetBridgeTx\x12\x1e.backend.v1.GetBridgeTxRequest\x1a\x1f.backend.v1.GetBridgeTxResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/rest/v1/bridge/tx/{tx_hash}B8Z6github.com/sovereign-l1/chain/api/backend/v1;backendv1b\x06proto3"

var (
	file_backend_v1_query_proto_rawDescOnce sync.Once
	file_backend_v1_query_proto_rawDescData []byte
)

func file_backend_v1_query_proto_rawDescGZIP() []byte {
	file_backend_v1_query_proto_rawDescOnce.Do(func() {
		file_backend_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_v1_query_proto_rawDesc), len(file_backend_v1_query_proto_rawDesc)))
	})
	return file_backend_v1_query_proto_rawDescData
}

var file_backend_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_backend_v1_query_proto_goTypes = []any{
	(*PageRequest)(nil),                    // 0: backend.v1.PageRequest
	(*PageResponse)(nil),                   // 1: backend.v1.PageResponse
	(*ListSettlementsRequest)(nil),         // 2: backend.v1.ListSettlementsRequest
	(*ListSettlementsResponse)(nil),        // 3: backend.v1.ListSettlementsResponse
	(*ListMilestonesRequest)(nil),          // 4: backend.v1.ListMilestonesRequest
	(*ListMilestonesResponse)(nil),         // 5: backend.v1.ListMilestonesResponse
	(*GetBridgeTxRequest)(nil),             // 6: backend.v1.GetBridgeTxRequest
	(*GetBridgeTxResponse)(nil),            // 7: backend.v1.GetBridgeTxResponse
	(*GetBridgeVolumeRequest)(nil),         // 8: backend.v1.GetBridgeVolumeRequest
	(*GetBridgeVolumeResponse)(nil),        // 9: backend.v1.GetBridgeVolumeResponse
	(*GetValidatorUptimeRequest)(nil),      // 10: backend.v1.GetValidatorUptimeRequest
	(*GetValidatorUptimeResponse)(nil),     // 11: backend.v1.GetValidatorUptimeResponse
	(*GetOracleParticipationRequest)(nil),  // 12: backend.v1.GetOracleParticipationRequest
	(*GetOracleParticipationResponse)(nil), // 13: backend.v1.GetOracleParticipationResponse
	(*GetSettlementRequest)(nil),           // 14: backend.v1.GetSettlementRequest
	(*GetSettlementResponse)(nil),          // 15: backend.v1.GetSettlementResponse
	(*GetMilestoneStatusRequest)(nil),      // 16: backend.v1.GetMilestoneStatusRequest
	(*GetMilestoneStatusResponse)(nil),     // 17: backend.v1.GetMilestoneStatusResponse
	(*GetBridgePendingRequest)(nil),        // 18: backend.v1.GetBridgePendingRequest
	(*GetBridgePendingResponse)(nil),       // 19: backend.v1.GetBridgePendingResponse
	(*GetTpsRequest)(nil),                  // 20: backend.v1.GetTpsRequest
	(*GetTpsResponse)(nil),                 // 21: backend.v1.GetTpsResponse
	(*GetBlockStatsRequest)(nil),           // 22: backend.v1.GetBlockStatsRequest
	(*GetBlockStatsResponse)(nil),          // 23: backend.v1.GetBlockStatsResponse
	(*GetOraclePriceRequest)(nil),          // 24: backend.v1.GetOraclePriceRequest
	(*GetOraclePriceResponse)(nil),         // 25: backend.v1.GetOraclePriceResponse
}
var file_backend_v1_query_proto_depIdxs = []int32{
	0,  // 0: backend.v1.ListSettlementsRequest.pagination:type_name -> backend.v1.PageRequest
	15, // 1: backend.v1.ListSettlementsResponse.settlements:type_name -> backend.v1.GetSettlementResponse
	1,  // 2: backend.v1.ListSettlementsResponse.pagination:type_name -> backend.v1.PageResponse
	0,  // 3: backend.v1.ListMilestonesRequest.pagination:type_name -> backend.v1.PageRequest
	17, // 4: backend.v1.ListMilestonesResponse.milestones:type_name -> backend.v1.GetMilestoneStatusResponse
	1,  // 5: backend.v1.ListMilestonesResponse.pagination:type_name -> backend.v1.PageResponse
	8,  // 6: backend.v1.QueryService.GetBridgeVolume:input_type -> backend.v1.GetBridgeVolumeRequest
	10, // 7: backend.v1.QueryService.GetValidatorUptime:input_type -> backend.v1.GetValidatorUptimeRequest
	12, // 8: backend.v1.QueryService.GetOracleParticipation:input_type -> backend.v1.GetOracleParticipationRequest
	14, // 9: backend.v1.QueryService.GetSettlement:input_type -> backend.v1.GetSettlementRequest
	16, // 10: backend.v1.QueryService.GetMilestoneStatus:input_type -> backend.v1.GetMilestoneStatusRequest
	18, // 11: backend.v1.QueryService.GetBridgePending:input_type -> backend.v1.GetBridgePendingRequest
	20, // 12: backend.v1.QueryService.GetTps:input_type -> backend.v1.GetTpsRequest
	22, // 13: backend.v1.QueryService.GetBlockStats:input_type -> backend.v1.GetBlockStatsRequest
	24, // 14: backend.v1.QueryService.GetOraclePrice:input_type -> backend.v1.GetOraclePriceRequest
	2,  // 15: backend.v1.QueryService.ListSettlements:input_type -> backend.v1.ListSettlementsRequest
	4,  // 16: backend.v1.QueryService.ListMilestones:input_type -> backend.v1.ListMilestonesRequest
	6,  // 17: backend.v1.QueryService.GetBridgeTx:input_type -> backend.v1.GetBridgeTxRequest
	9,  // 18: backend.v1.QueryService.GetBridgeVolume:output_type -> backend.v1.GetBridgeVolumeResponse
	11, // 19: backend.v1.QueryService.GetValidatorUptime:output_type -> backend.v1.GetValidatorUptimeResponse
	13, // 20: backend.v1.QueryService.GetOracleParticipation:output_type -> backend.v1.GetOracleParticipationResponse
	15, // 21: backend.v1.QueryService.GetSettlement:output_type -> backend.v1.GetSettlementResponse
	17, // 22: backend.v1.QueryService.GetMilestoneStatus:output_type -> backend.v1.GetMilestoneStatusResponse
	19, // 23: backend.v1.QueryService.GetBridgePending:output_type -> backend.v1.GetBridgePendingResponse
	21, // 24: backend.v1.QueryService.GetTps:output_type -> backend.v1.GetTpsResponse
	23, // 25: backend.v1.QueryService.GetBlockStats:output_type -> backend.v1.GetBlockStatsResponse
	25, // 26: backend.v1.QueryService.GetOraclePrice:output_type -> backend.v1.GetOraclePriceResponse
	3,  // 27: backend.v1.QueryService.ListSettlements:output_type -> backend.v1.ListSettlementsResponse
	5,  // 28: backend.v1.QueryService.ListMilestones:output_type -> backend.v1.ListMilestonesResponse
	7,  // 29: backend.v1.QueryService.GetBridgeTx:output_type -> backend.v1.GetBridgeTxResponse
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_backend_v1_query_proto_init() }
func file_backend_v1_query_proto_init() {
	if File_backend_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_v1_query_proto_rawDesc), len(file_backend_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_v1_query_proto_goTypes,
		DependencyIndexes: file_backend_v1_query_proto_depIdxs,
		MessageInfos:      file_backend_v1_query_proto_msgTypes,
	}.Build()
	File_backend_v1_query_proto = out.File
	file_backend_v1_query_proto_goTypes = nil
	file_backend_v1_query_proto_depIdxs = nil
}
