// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: backend/v1/stream.proto

package backendv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamBridgeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBridgeEventsRequest) Reset() {
	*x = StreamBridgeEventsRequest{}
	mi := &file_backend_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBridgeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBridgeEventsRequest) ProtoMessage() {}

func (x *StreamBridgeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBridgeEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamBridgeEventsRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamBridgeEventsRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type BridgeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "mint" or "burn"
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	BlockHeight   int64                  `protobuf:"varint,6,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	TxHash        string                 `protobuf:"bytes,7,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeEvent) Reset() {
	*x = BridgeEvent{}
	mi := &file_backend_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeEvent) ProtoMessage() {}

func (x *BridgeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeEvent.ProtoReflect.Descriptor instead.
func (*BridgeEvent) Descriptor() ([]byte, []int) {
	return file_backend_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *BridgeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BridgeEvent) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *BridgeEvent) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BridgeEvent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *BridgeEvent) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *BridgeEvent) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *BridgeEvent) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type StreamOracleEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OracleAddress string                 `protobuf:"bytes,1,opt,name=oracle_address,json=oracleAddress,proto3" json:"oracle_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOracleEventsRequest) Reset() {
	*x = StreamOracleEventsRequest{}
	mi := &file_backend_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOracleEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOracleEventsRequest) ProtoMessage() {}

func (x *StreamOracleEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOracleEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamOracleEventsRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamOracleEventsRequest) GetOracleAddress() string {
	if x != nil {
		return x.OracleAddress
	}
	return ""
}

type OracleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OracleAddress string                 `protobuf:"bytes,1,opt,name=oracle_address,json=oracleAddress,proto3" json:"oracle_address,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	BlockHeight   int64                  `protobuf:"varint,5,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // e.g., "requested", "revealed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OracleEvent) Reset() {
	*x = OracleEvent{}
	mi := &file_backend_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OracleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleEvent) ProtoMessage() {}

func (x *OracleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleEvent.ProtoReflect.Descriptor instead.
func (*OracleEvent) Descriptor() ([]byte, []int) {
	return file_backend_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *OracleEvent) GetOracleAddress() string {
	if x != nil {
		return x.OracleAddress
	}
	return ""
}

func (x *OracleEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OracleEvent) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *OracleEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *OracleEvent) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *OracleEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StreamMilestoneEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MilestoneId   string                 `protobuf:"bytes,1,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMilestoneEventsRequest) Reset() {
	*x = StreamMilestoneEventsRequest{}
	mi := &file_backend_v1_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMilestoneEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMilestoneEventsRequest) ProtoMessage() {}

func (x *StreamMilestoneEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMilestoneEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamMilestoneEventsRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_stream_proto_rawDescGZIP(), []int{4}
}

func (x *StreamMilestoneEventsRequest) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

type MilestoneEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MilestoneId   string                 `protobuf:"bytes,1,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "achieved", "stale"
	BlockHeight   int64                  `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MilestoneEvent) Reset() {
	*x = MilestoneEvent{}
	mi := &file_backend_v1_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MilestoneEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestoneEvent) ProtoMessage() {}

func (x *MilestoneEvent) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestoneEvent.ProtoReflect.Descriptor instead.
func (*MilestoneEvent) Descriptor() ([]byte, []int) {
	return file_backend_v1_stream_proto_rawDescGZIP(), []int{5}
}

func (x *MilestoneEvent) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

func (x *MilestoneEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MilestoneEvent) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

type StreamChainStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChainStatsRequest) Reset() {
	*x = StreamChainStatsRequest{}
	mi := &file_backend_v1_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChainStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChainStatsRequest) ProtoMessage() {}

func (x *StreamChainStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChainStatsRequest.ProtoReflect.Descriptor instead.
func (*StreamChainStatsRequest) Descriptor() ([]byte, []int) {
	return file_backend_v1_stream_proto_rawDescGZIP(), []int{6}
}

type ChainStatsEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TpsAvg         float64                `protobuf:"fixed64,1,opt,name=tps_avg,json=tpsAvg,proto3" json:"tps_avg,omitempty"`
	TpsPeak        float64                `protobuf:"fixed64,2,opt,name=tps_peak,json=tpsPeak,proto3" json:"tps_peak,omitempty"`
	TotalTxs       int64                  `protobuf:"varint,3,opt,name=total_txs,json=totalTxs,proto3" json:"total_txs,omitempty"`
	AvgBlockTimeMs float64                `protobuf:"fixed64,4,opt,name=avg_block_time_ms,json=avgBlockTimeMs,proto3" json:"avg_block_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChainStatsEvent) Reset() {
	*x = ChainStatsEvent{}
	mi := &file_backend_v1_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStatsEvent) ProtoMessage() {}

func (x *ChainStatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStatsEvent.ProtoReflect.Descriptor instead.
func (*ChainStatsEvent) Descriptor() ([]byte, []int) {
	return file_backend_v1_stream_proto_rawDescGZIP(), []int{7}
}

func (x *ChainStatsEvent) GetTpsAvg() float64 {
	if x != nil {
		return x.TpsAvg
	}
	return 0
}

func (x *ChainStatsEvent) GetTpsPeak() float64 {
	if x != nil {
		return x.TpsPeak
	}
	return 0
}

func (x *ChainStatsEvent) GetTotalTxs() int64 {
	if x != nil {
		return x.TotalTxs
	}
	return 0
}

func (x *ChainStatsEvent) GetAvgBlockTimeMs() float64 {
	if x != nil {
		return x.AvgBlockTimeMs
	}
	return 0
}

var File_backend_v1_stream_proto protoreflect.FileDescriptor

const file_backend_v1_stream_proto_rawDesc = "" +
	"\n" +
	"\x17backend/v1/stream.proto\x12\n" +
	"backend.v1\x1a\x1cgoogle/api/annotations.proto\"@\n" +
	"\x19StreamBridgeEventsRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\"\xdb\x01\n" +
	"\vBridgeEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x05 \x01(\tR\trecipient\x12!\n" +
	"\fblock_height\x18\x06 \x01(\x03R\vblockHeight\x12\x17\n" +
	"\atx_hash\x18\a \x01(\tR\x06txHash\"B\n" +
	"\x19StreamOracleEventsRequest\x12%\n" +
	"\x0eoracle_address\x18\x01 \x01(\tR\roracleAddress\"\xc5\x01\n" +
	"\vOracleEvent\x12%\n" +
	"\x0eoracle_address\x18\x01 \x01(\tR\roracleAddress\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12!\n" +
	"\fblock_height\x18\x05 \x01(\x03R\vblockHeight\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"A\n" +
	"\x1cStreamMilestoneEventsRequest\x12!\n" +
	"\fmilestone_id\x18\x01 \x01(\tR\vmilestoneId\"n\n" +
	"\x0eMilestoneEvent\x12!\n" +
	"\fmilestone_id\x18\x01 \x01(\tR\vmilestoneId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fblock_height\x18\x03 \x01(\x03R\vblockHeight\"\x19\n" +
	"\x17StreamChainStatsRequest\"\x8d\x01\n" +
	"\x0fChainStatsEvent\x12\x17\n" +
	"\atps_avg\x18\x01 \x01(\x01R\x06tpsAvg\x12\x19\n" +
	"\btps_peak\x18\x02 \x01(\x01R\atpsPeak\x12\x1b\n" +
	"\ttotal_txs\x18\x03 \x01(\x03R\btotalTxs\x12)\n" +
	"\x11avg_block_time_ms\x18\x04 \x01(\x01R\x0eavgBlockTimeMs2\x8b\x04\n" +
	"\rStreamService\x12z\n" +
	"\x12StreamBridgeEvents\x12%.backend.v1.StreamBridgeEventsRequest\x1a\x17.backend.v1.BridgeEvent\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/rest/v1/stream/bridge0\x01\x12z\n" +
	"\x12StreamOracleEvents\x12%.backend.v1.StreamOracleEventsRequest\x1a\x17.backend.v1.OracleEvent\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/rest/v1/stream/oracle0\x01\x12\x86\x01\n" +
	"\x15StreamMilestoneEvents\x12(.backend.v1.StreamMilestoneEventsRequest\x1a\x1a.backend.v1.MilestoneEvent\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/rest/v1/stream/milestone0\x01\x12y\n" +
	"\x10StreamChainStats\x12#.backend.v1.StreamChainStatsRequest\x1a\x1b.backend.v1.ChainStatsEvent\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/rest/v1/stream/stats0\x01B8Z6github.com/sovereign-l1/chain/api/backend/v1;backendv1b\x06proto3"

var (
	file_backend_v1_stream_proto_rawDescOnce sync.Once
	file_backend_v1_stream_proto_rawDescData []byte
)

func file_backend_v1_stream_proto_rawDescGZIP() []byte {
	file_backend_v1_stream_proto_rawDescOnce.Do(func() {
		file_backend_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_v1_stream_proto_rawDesc), len(file_backend_v1_stream_proto_rawDesc)))
	})
	return file_backend_v1_stream_proto_rawDescData
}

var file_backend_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_backend_v1_stream_proto_goTypes = []any{
	(*StreamBridgeEventsRequest)(nil),    // 0: backend.v1.StreamBridgeEventsRequest
	(*BridgeEvent)(nil),                  // 1: backend.v1.BridgeEvent
	(*StreamOracleEventsRequest)(nil),    // 2: backend.v1.StreamOracleEventsRequest
	(*OracleEvent)(nil),                  // 3: backend.v1.OracleEvent
	(*StreamMilestoneEventsRequest)(nil), // 4: backend.v1.StreamMilestoneEventsRequest
	(*MilestoneEvent)(nil),               // 5: backend.v1.MilestoneEvent
	(*StreamChainStatsRequest)(nil),      // 6: backend.v1.StreamChainStatsRequest
	(*ChainStatsEvent)(nil),              // 7: backend.v1.ChainStatsEvent
}
var file_backend_v1_stream_proto_depIdxs = []int32{
	0, // 0: backend.v1.StreamService.StreamBridgeEvents:input_type -> backend.v1.StreamBridgeEventsRequest
	2, // 1: backend.v1.StreamService.StreamOracleEvents:input_type -> backend.v1.StreamOracleEventsRequest
	4, // 2: backend.v1.StreamService.StreamMilestoneEvents:input_type -> backend.v1.StreamMilestoneEventsRequest
	6, // 3: backend.v1.StreamService.StreamChainStats:input_type -> backend.v1.StreamChainStatsRequest
	1, // 4: backend.v1.StreamService.StreamBridgeEvents:output_type -> backend.v1.BridgeEvent
	3, // 5: backend.v1.StreamService.StreamOracleEvents:output_type -> backend.v1.OracleEvent
	5, // 6: backend.v1.StreamService.StreamMilestoneEvents:output_type -> backend.v1.MilestoneEvent
	7, // 7: backend.v1.StreamService.StreamChainStats:output_type -> backend.v1.ChainStatsEvent
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_v1_stream_proto_init() }
func file_backend_v1_stream_proto_init() {
	if File_backend_v1_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_v1_stream_proto_rawDesc), len(file_backend_v1_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_v1_stream_proto_goTypes,
		DependencyIndexes: file_backend_v1_stream_proto_depIdxs,
		MessageInfos:      file_backend_v1_stream_proto_msgTypes,
	}.Build()
	File_backend_v1_stream_proto = out.File
	file_backend_v1_stream_proto_goTypes = nil
	file_backend_v1_stream_proto_depIdxs = nil
}
