// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: backend/v1/stream.proto

package backendv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamService_StreamBridgeEvents_FullMethodName    = "/backend.v1.StreamService/StreamBridgeEvents"
	StreamService_StreamOracleEvents_FullMethodName    = "/backend.v1.StreamService/StreamOracleEvents"
	StreamService_StreamMilestoneEvents_FullMethodName = "/backend.v1.StreamService/StreamMilestoneEvents"
	StreamService_StreamChainStats_FullMethodName      = "/backend.v1.StreamService/StreamChainStats"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	StreamBridgeEvents(ctx context.Context, in *StreamBridgeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BridgeEvent], error)
	StreamOracleEvents(ctx context.Context, in *StreamOracleEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OracleEvent], error)
	StreamMilestoneEvents(ctx context.Context, in *StreamMilestoneEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MilestoneEvent], error)
	StreamChainStats(ctx context.Context, in *StreamChainStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChainStatsEvent], error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) StreamBridgeEvents(ctx context.Context, in *StreamBridgeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BridgeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_StreamBridgeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBridgeEventsRequest, BridgeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamBridgeEventsClient = grpc.ServerStreamingClient[BridgeEvent]

func (c *streamServiceClient) StreamOracleEvents(ctx context.Context, in *StreamOracleEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OracleEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[1], StreamService_StreamOracleEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamOracleEventsRequest, OracleEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamOracleEventsClient = grpc.ServerStreamingClient[OracleEvent]

func (c *streamServiceClient) StreamMilestoneEvents(ctx context.Context, in *StreamMilestoneEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MilestoneEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[2], StreamService_StreamMilestoneEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMilestoneEventsRequest, MilestoneEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamMilestoneEventsClient = grpc.ServerStreamingClient[MilestoneEvent]

func (c *streamServiceClient) StreamChainStats(ctx context.Context, in *StreamChainStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChainStatsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[3], StreamService_StreamChainStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChainStatsRequest, ChainStatsEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamChainStatsClient = grpc.ServerStreamingClient[ChainStatsEvent]

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility.
type StreamServiceServer interface {
	StreamBridgeEvents(*StreamBridgeEventsRequest, grpc.ServerStreamingServer[BridgeEvent]) error
	StreamOracleEvents(*StreamOracleEventsRequest, grpc.ServerStreamingServer[OracleEvent]) error
	StreamMilestoneEvents(*StreamMilestoneEventsRequest, grpc.ServerStreamingServer[MilestoneEvent]) error
	StreamChainStats(*StreamChainStatsRequest, grpc.ServerStreamingServer[ChainStatsEvent]) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServiceServer struct{}

func (UnimplementedStreamServiceServer) StreamBridgeEvents(*StreamBridgeEventsRequest, grpc.ServerStreamingServer[BridgeEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamBridgeEvents not implemented")
}
func (UnimplementedStreamServiceServer) StreamOracleEvents(*StreamOracleEventsRequest, grpc.ServerStreamingServer[OracleEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamOracleEvents not implemented")
}
func (UnimplementedStreamServiceServer) StreamMilestoneEvents(*StreamMilestoneEventsRequest, grpc.ServerStreamingServer[MilestoneEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamMilestoneEvents not implemented")
}
func (UnimplementedStreamServiceServer) StreamChainStats(*StreamChainStatsRequest, grpc.ServerStreamingServer[ChainStatsEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamChainStats not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}
func (UnimplementedStreamServiceServer) testEmbeddedByValue()                       {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_StreamBridgeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBridgeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).StreamBridgeEvents(m, &grpc.GenericServerStream[StreamBridgeEventsRequest, BridgeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamBridgeEventsServer = grpc.ServerStreamingServer[BridgeEvent]

func _StreamService_StreamOracleEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOracleEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).StreamOracleEvents(m, &grpc.GenericServerStream[StreamOracleEventsRequest, OracleEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamOracleEventsServer = grpc.ServerStreamingServer[OracleEvent]

func _StreamService_StreamMilestoneEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMilestoneEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).StreamMilestoneEvents(m, &grpc.GenericServerStream[StreamMilestoneEventsRequest, MilestoneEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamMilestoneEventsServer = grpc.ServerStreamingServer[MilestoneEvent]

func _StreamService_StreamChainStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChainStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).StreamChainStats(m, &grpc.GenericServerStream[StreamChainStatsRequest, ChainStatsEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamChainStatsServer = grpc.ServerStreamingServer[ChainStatsEvent]

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.v1.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBridgeEvents",
			Handler:       _StreamService_StreamBridgeEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOracleEvents",
			Handler:       _StreamService_StreamOracleEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMilestoneEvents",
			Handler:       _StreamService_StreamMilestoneEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamChainStats",
			Handler:       _StreamService_StreamChainStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backend/v1/stream.proto",
}
