// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "backend/v1/query.proto" (package "backend.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { QueryService } from "./query";
import type { GetBridgeTxResponse } from "./query";
import type { GetBridgeTxRequest } from "./query";
import type { ListMilestonesResponse } from "./query";
import type { ListMilestonesRequest } from "./query";
import type { ListSettlementsResponse } from "./query";
import type { ListSettlementsRequest } from "./query";
import type { GetOraclePriceResponse } from "./query";
import type { GetOraclePriceRequest } from "./query";
import type { GetBlockStatsResponse } from "./query";
import type { GetBlockStatsRequest } from "./query";
import type { GetTpsResponse } from "./query";
import type { GetTpsRequest } from "./query";
import type { GetBridgePendingResponse } from "./query";
import type { GetBridgePendingRequest } from "./query";
import type { GetMilestoneStatusResponse } from "./query";
import type { GetMilestoneStatusRequest } from "./query";
import type { GetSettlementResponse } from "./query";
import type { GetSettlementRequest } from "./query";
import type { GetOracleParticipationResponse } from "./query";
import type { GetOracleParticipationRequest } from "./query";
import type { GetValidatorUptimeResponse } from "./query";
import type { GetValidatorUptimeRequest } from "./query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetBridgeVolumeResponse } from "./query";
import type { GetBridgeVolumeRequest } from "./query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service backend.v1.QueryService
 */
export interface IQueryServiceClient {
    /**
     * @generated from protobuf rpc: GetBridgeVolume
     */
    getBridgeVolume(input: GetBridgeVolumeRequest, options?: RpcOptions): UnaryCall<GetBridgeVolumeRequest, GetBridgeVolumeResponse>;
    /**
     * @generated from protobuf rpc: GetValidatorUptime
     */
    getValidatorUptime(input: GetValidatorUptimeRequest, options?: RpcOptions): UnaryCall<GetValidatorUptimeRequest, GetValidatorUptimeResponse>;
    /**
     * @generated from protobuf rpc: GetOracleParticipation
     */
    getOracleParticipation(input: GetOracleParticipationRequest, options?: RpcOptions): UnaryCall<GetOracleParticipationRequest, GetOracleParticipationResponse>;
    /**
     * @generated from protobuf rpc: GetSettlement
     */
    getSettlement(input: GetSettlementRequest, options?: RpcOptions): UnaryCall<GetSettlementRequest, GetSettlementResponse>;
    /**
     * @generated from protobuf rpc: GetMilestoneStatus
     */
    getMilestoneStatus(input: GetMilestoneStatusRequest, options?: RpcOptions): UnaryCall<GetMilestoneStatusRequest, GetMilestoneStatusResponse>;
    /**
     * @generated from protobuf rpc: GetBridgePending
     */
    getBridgePending(input: GetBridgePendingRequest, options?: RpcOptions): UnaryCall<GetBridgePendingRequest, GetBridgePendingResponse>;
    /**
     * @generated from protobuf rpc: GetTps
     */
    getTps(input: GetTpsRequest, options?: RpcOptions): UnaryCall<GetTpsRequest, GetTpsResponse>;
    /**
     * @generated from protobuf rpc: GetBlockStats
     */
    getBlockStats(input: GetBlockStatsRequest, options?: RpcOptions): UnaryCall<GetBlockStatsRequest, GetBlockStatsResponse>;
    /**
     * @generated from protobuf rpc: GetOraclePrice
     */
    getOraclePrice(input: GetOraclePriceRequest, options?: RpcOptions): UnaryCall<GetOraclePriceRequest, GetOraclePriceResponse>;
    /**
     * @generated from protobuf rpc: ListSettlements
     */
    listSettlements(input: ListSettlementsRequest, options?: RpcOptions): UnaryCall<ListSettlementsRequest, ListSettlementsResponse>;
    /**
     * @generated from protobuf rpc: ListMilestones
     */
    listMilestones(input: ListMilestonesRequest, options?: RpcOptions): UnaryCall<ListMilestonesRequest, ListMilestonesResponse>;
    /**
     * @generated from protobuf rpc: GetBridgeTx
     */
    getBridgeTx(input: GetBridgeTxRequest, options?: RpcOptions): UnaryCall<GetBridgeTxRequest, GetBridgeTxResponse>;
}
/**
 * @generated from protobuf service backend.v1.QueryService
 */
export class QueryServiceClient implements IQueryServiceClient, ServiceInfo {
    typeName = QueryService.typeName;
    methods = QueryService.methods;
    options = QueryService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetBridgeVolume
     */
    getBridgeVolume(input: GetBridgeVolumeRequest, options?: RpcOptions): UnaryCall<GetBridgeVolumeRequest, GetBridgeVolumeResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBridgeVolumeRequest, GetBridgeVolumeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetValidatorUptime
     */
    getValidatorUptime(input: GetValidatorUptimeRequest, options?: RpcOptions): UnaryCall<GetValidatorUptimeRequest, GetValidatorUptimeResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetValidatorUptimeRequest, GetValidatorUptimeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetOracleParticipation
     */
    getOracleParticipation(input: GetOracleParticipationRequest, options?: RpcOptions): UnaryCall<GetOracleParticipationRequest, GetOracleParticipationResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOracleParticipationRequest, GetOracleParticipationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSettlement
     */
    getSettlement(input: GetSettlementRequest, options?: RpcOptions): UnaryCall<GetSettlementRequest, GetSettlementResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSettlementRequest, GetSettlementResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMilestoneStatus
     */
    getMilestoneStatus(input: GetMilestoneStatusRequest, options?: RpcOptions): UnaryCall<GetMilestoneStatusRequest, GetMilestoneStatusResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMilestoneStatusRequest, GetMilestoneStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBridgePending
     */
    getBridgePending(input: GetBridgePendingRequest, options?: RpcOptions): UnaryCall<GetBridgePendingRequest, GetBridgePendingResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBridgePendingRequest, GetBridgePendingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTps
     */
    getTps(input: GetTpsRequest, options?: RpcOptions): UnaryCall<GetTpsRequest, GetTpsResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTpsRequest, GetTpsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlockStats
     */
    getBlockStats(input: GetBlockStatsRequest, options?: RpcOptions): UnaryCall<GetBlockStatsRequest, GetBlockStatsResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBlockStatsRequest, GetBlockStatsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetOraclePrice
     */
    getOraclePrice(input: GetOraclePriceRequest, options?: RpcOptions): UnaryCall<GetOraclePriceRequest, GetOraclePriceResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOraclePriceRequest, GetOraclePriceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSettlements
     */
    listSettlements(input: ListSettlementsRequest, options?: RpcOptions): UnaryCall<ListSettlementsRequest, ListSettlementsResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSettlementsRequest, ListSettlementsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMilestones
     */
    listMilestones(input: ListMilestonesRequest, options?: RpcOptions): UnaryCall<ListMilestonesRequest, ListMilestonesResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMilestonesRequest, ListMilestonesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBridgeTx
     */
    getBridgeTx(input: GetBridgeTxRequest, options?: RpcOptions): UnaryCall<GetBridgeTxRequest, GetBridgeTxResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBridgeTxRequest, GetBridgeTxResponse>("unary", this._transport, method, opt, input);
    }
}
