// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "backend/v1/query.proto" (package "backend.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message backend.v1.PageRequest
 */
export interface PageRequest {
    /**
     * @generated from protobuf field: bytes cursor = 1
     */
    cursor: Uint8Array;
    /**
     * @generated from protobuf field: uint32 limit = 2
     */
    limit: number;
}
/**
 * @generated from protobuf message backend.v1.PageResponse
 */
export interface PageResponse {
    /**
     * @generated from protobuf field: bytes next_cursor = 1
     */
    nextCursor: Uint8Array;
    /**
     * @generated from protobuf field: bool has_more = 2
     */
    hasMore: boolean;
}
/**
 * @generated from protobuf message backend.v1.ListSettlementsRequest
 */
export interface ListSettlementsRequest {
    /**
     * @generated from protobuf field: backend.v1.PageRequest pagination = 1
     */
    pagination?: PageRequest;
}
/**
 * @generated from protobuf message backend.v1.ListSettlementsResponse
 */
export interface ListSettlementsResponse {
    /**
     * @generated from protobuf field: repeated backend.v1.GetSettlementResponse settlements = 1
     */
    settlements: GetSettlementResponse[];
    /**
     * @generated from protobuf field: backend.v1.PageResponse pagination = 2
     */
    pagination?: PageResponse;
}
/**
 * @generated from protobuf message backend.v1.ListMilestonesRequest
 */
export interface ListMilestonesRequest {
    /**
     * @generated from protobuf field: backend.v1.PageRequest pagination = 1
     */
    pagination?: PageRequest;
}
/**
 * @generated from protobuf message backend.v1.ListMilestonesResponse
 */
export interface ListMilestonesResponse {
    /**
     * @generated from protobuf field: repeated backend.v1.GetMilestoneStatusResponse milestones = 1
     */
    milestones: GetMilestoneStatusResponse[];
    /**
     * @generated from protobuf field: backend.v1.PageResponse pagination = 2
     */
    pagination?: PageResponse;
}
/**
 * @generated from protobuf message backend.v1.GetBridgeTxRequest
 */
export interface GetBridgeTxRequest {
    /**
     * @generated from protobuf field: string tx_hash = 1
     */
    txHash: string;
}
/**
 * @generated from protobuf message backend.v1.GetBridgeTxResponse
 */
export interface GetBridgeTxResponse {
    /**
     * @generated from protobuf field: string tx_hash = 1
     */
    txHash: string;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string;
    /**
     * @generated from protobuf field: int64 block_height = 3
     */
    blockHeight: string;
    /**
     * @generated from protobuf field: string token_address = 4
     */
    tokenAddress: string;
    /**
     * @generated from protobuf field: string amount = 5
     */
    amount: string;
    /**
     * @generated from protobuf field: string sender = 6
     */
    sender: string;
    /**
     * @generated from protobuf field: string recipient = 7
     */
    recipient: string;
}
/**
 * @generated from protobuf message backend.v1.GetBridgeVolumeRequest
 */
export interface GetBridgeVolumeRequest {
    /**
     * @generated from protobuf field: string token_address = 1
     */
    tokenAddress: string;
    /**
     * @generated from protobuf field: string chain_id = 2
     */
    chainId: string;
    /**
     * @generated from protobuf field: string timeframe = 3
     */
    timeframe: string; // e.g., "daily", "hourly"
}
/**
 * @generated from protobuf message backend.v1.GetBridgeVolumeResponse
 */
export interface GetBridgeVolumeResponse {
    /**
     * @generated from protobuf field: string total_minted = 1
     */
    totalMinted: string;
    /**
     * @generated from protobuf field: string total_burned = 2
     */
    totalBurned: string;
    /**
     * @generated from protobuf field: string volume_usd = 3
     */
    volumeUsd: string;
    /**
     * @generated from protobuf field: int64 transaction_count = 4
     */
    transactionCount: string;
}
/**
 * @generated from protobuf message backend.v1.GetValidatorUptimeRequest
 */
export interface GetValidatorUptimeRequest {
    /**
     * @generated from protobuf field: string validator_address = 1
     */
    validatorAddress: string;
}
/**
 * @generated from protobuf message backend.v1.GetValidatorUptimeResponse
 */
export interface GetValidatorUptimeResponse {
    /**
     * @generated from protobuf field: string validator_address = 1
     */
    validatorAddress: string;
    /**
     * @generated from protobuf field: int64 total_blocks = 2
     */
    totalBlocks: string;
    /**
     * @generated from protobuf field: int64 missed_blocks = 3
     */
    missedBlocks: string;
    /**
     * @generated from protobuf field: double uptime_percentage = 4
     */
    uptimePercentage: number;
}
/**
 * @generated from protobuf message backend.v1.GetOracleParticipationRequest
 */
export interface GetOracleParticipationRequest {
    /**
     * @generated from protobuf field: string oracle_address = 1
     */
    oracleAddress: string;
}
/**
 * @generated from protobuf message backend.v1.GetOracleParticipationResponse
 */
export interface GetOracleParticipationResponse {
    /**
     * @generated from protobuf field: string oracle_address = 1
     */
    oracleAddress: string;
    /**
     * @generated from protobuf field: int64 total_requests = 2
     */
    totalRequests: string;
    /**
     * @generated from protobuf field: int64 successful_reveals = 3
     */
    successfulReveals: string;
    /**
     * @generated from protobuf field: double participation_rate = 4
     */
    participationRate: number;
}
/**
 * @generated from protobuf message backend.v1.GetSettlementRequest
 */
export interface GetSettlementRequest {
    /**
     * @generated from protobuf field: string settlement_id = 1
     */
    settlementId: string;
}
/**
 * @generated from protobuf message backend.v1.GetSettlementResponse
 */
export interface GetSettlementResponse {
    /**
     * @generated from protobuf field: string settlement_id = 1
     */
    settlementId: string;
    /**
     * @generated from protobuf field: bytes proof = 2
     */
    proof: Uint8Array;
    /**
     * @generated from protobuf field: string status = 3
     */
    status: string;
    /**
     * @generated from protobuf field: int64 block_height = 4
     */
    blockHeight: string;
    /**
     * @generated from protobuf field: repeated string signatures = 5
     */
    signatures: string[];
}
/**
 * @generated from protobuf message backend.v1.GetMilestoneStatusRequest
 */
export interface GetMilestoneStatusRequest {
    /**
     * @generated from protobuf field: string milestone_id = 1
     */
    milestoneId: string;
}
/**
 * @generated from protobuf message backend.v1.GetMilestoneStatusResponse
 */
export interface GetMilestoneStatusResponse {
    /**
     * @generated from protobuf field: string milestone_id = 1
     */
    milestoneId: string;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string;
    /**
     * @generated from protobuf field: int64 block_height = 3
     */
    blockHeight: string;
}
/**
 * @generated from protobuf message backend.v1.GetBridgePendingRequest
 */
export interface GetBridgePendingRequest {
    /**
     * @generated from protobuf field: uint64 nonce = 1
     */
    nonce: string;
}
/**
 * @generated from protobuf message backend.v1.GetBridgePendingResponse
 */
export interface GetBridgePendingResponse {
    /**
     * @generated from protobuf field: uint64 nonce = 1
     */
    nonce: string;
    /**
     * @generated from protobuf field: string token_address = 2
     */
    tokenAddress: string;
    /**
     * @generated from protobuf field: string amount = 3
     */
    amount: string;
    /**
     * @generated from protobuf field: string recipient = 4
     */
    recipient: string;
    /**
     * @generated from protobuf field: string status = 5
     */
    status: string;
}
/**
 * @generated from protobuf message backend.v1.GetTpsRequest
 */
export interface GetTpsRequest {
}
/**
 * @generated from protobuf message backend.v1.GetTpsResponse
 */
export interface GetTpsResponse {
    /**
     * @generated from protobuf field: double tps_avg = 1
     */
    tpsAvg: number;
    /**
     * @generated from protobuf field: double tps_peak = 2
     */
    tpsPeak: number;
    /**
     * @generated from protobuf field: int64 total_txs = 3
     */
    totalTxs: string;
}
/**
 * @generated from protobuf message backend.v1.GetBlockStatsRequest
 */
export interface GetBlockStatsRequest {
}
/**
 * @generated from protobuf message backend.v1.GetBlockStatsResponse
 */
export interface GetBlockStatsResponse {
    /**
     * @generated from protobuf field: double avg_ms = 1
     */
    avgMs: number;
    /**
     * @generated from protobuf field: int64 max_ms = 2
     */
    maxMs: string;
}
/**
 * @generated from protobuf message backend.v1.GetOraclePriceRequest
 */
export interface GetOraclePriceRequest {
    /**
     * @generated from protobuf field: string asset_id = 1
     */
    assetId: string;
}
/**
 * @generated from protobuf message backend.v1.GetOraclePriceResponse
 */
export interface GetOraclePriceResponse {
    /**
     * @generated from protobuf field: string asset_id = 1
     */
    assetId: string;
    /**
     * @generated from protobuf field: double open = 2
     */
    open: number;
    /**
     * @generated from protobuf field: double high = 3
     */
    high: number;
    /**
     * @generated from protobuf field: double low = 4
     */
    low: number;
    /**
     * @generated from protobuf field: double close = 5
     */
    close: number;
    /**
     * @generated from protobuf field: int64 submission_count = 6
     */
    submissionCount: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class PageRequest$Type extends MessageType<PageRequest> {
    constructor() {
        super("backend.v1.PageRequest", [
            { no: 1, name: "cursor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "limit", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<PageRequest>): PageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cursor = new Uint8Array(0);
        message.limit = 0;
        if (value !== undefined)
            reflectionMergePartial<PageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageRequest): PageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes cursor */ 1:
                    message.cursor = reader.bytes();
                    break;
                case /* uint32 limit */ 2:
                    message.limit = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes cursor = 1; */
        if (message.cursor.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.cursor);
        /* uint32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).uint32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.PageRequest
 */
export const PageRequest = new PageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageResponse$Type extends MessageType<PageResponse> {
    constructor() {
        super("backend.v1.PageResponse", [
            { no: 1, name: "next_cursor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "has_more", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PageResponse>): PageResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.nextCursor = new Uint8Array(0);
        message.hasMore = false;
        if (value !== undefined)
            reflectionMergePartial<PageResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageResponse): PageResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes next_cursor */ 1:
                    message.nextCursor = reader.bytes();
                    break;
                case /* bool has_more */ 2:
                    message.hasMore = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes next_cursor = 1; */
        if (message.nextCursor.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.nextCursor);
        /* bool has_more = 2; */
        if (message.hasMore !== false)
            writer.tag(2, WireType.Varint).bool(message.hasMore);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.PageResponse
 */
export const PageResponse = new PageResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListSettlementsRequest$Type extends MessageType<ListSettlementsRequest> {
    constructor() {
        super("backend.v1.ListSettlementsRequest", [
            { no: 1, name: "pagination", kind: "message", T: () => PageRequest }
        ]);
    }
    create(value?: PartialMessage<ListSettlementsRequest>): ListSettlementsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListSettlementsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListSettlementsRequest): ListSettlementsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* backend.v1.PageRequest pagination */ 1:
                    message.pagination = PageRequest.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListSettlementsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* backend.v1.PageRequest pagination = 1; */
        if (message.pagination)
            PageRequest.internalBinaryWrite(message.pagination, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.ListSettlementsRequest
 */
export const ListSettlementsRequest = new ListSettlementsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListSettlementsResponse$Type extends MessageType<ListSettlementsResponse> {
    constructor() {
        super("backend.v1.ListSettlementsResponse", [
            { no: 1, name: "settlements", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GetSettlementResponse },
            { no: 2, name: "pagination", kind: "message", T: () => PageResponse }
        ]);
    }
    create(value?: PartialMessage<ListSettlementsResponse>): ListSettlementsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.settlements = [];
        if (value !== undefined)
            reflectionMergePartial<ListSettlementsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListSettlementsResponse): ListSettlementsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated backend.v1.GetSettlementResponse settlements */ 1:
                    message.settlements.push(GetSettlementResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* backend.v1.PageResponse pagination */ 2:
                    message.pagination = PageResponse.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListSettlementsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated backend.v1.GetSettlementResponse settlements = 1; */
        for (let i = 0; i < message.settlements.length; i++)
            GetSettlementResponse.internalBinaryWrite(message.settlements[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* backend.v1.PageResponse pagination = 2; */
        if (message.pagination)
            PageResponse.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.ListSettlementsResponse
 */
export const ListSettlementsResponse = new ListSettlementsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMilestonesRequest$Type extends MessageType<ListMilestonesRequest> {
    constructor() {
        super("backend.v1.ListMilestonesRequest", [
            { no: 1, name: "pagination", kind: "message", T: () => PageRequest }
        ]);
    }
    create(value?: PartialMessage<ListMilestonesRequest>): ListMilestonesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListMilestonesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListMilestonesRequest): ListMilestonesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* backend.v1.PageRequest pagination */ 1:
                    message.pagination = PageRequest.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListMilestonesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* backend.v1.PageRequest pagination = 1; */
        if (message.pagination)
            PageRequest.internalBinaryWrite(message.pagination, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.ListMilestonesRequest
 */
export const ListMilestonesRequest = new ListMilestonesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMilestonesResponse$Type extends MessageType<ListMilestonesResponse> {
    constructor() {
        super("backend.v1.ListMilestonesResponse", [
            { no: 1, name: "milestones", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GetMilestoneStatusResponse },
            { no: 2, name: "pagination", kind: "message", T: () => PageResponse }
        ]);
    }
    create(value?: PartialMessage<ListMilestonesResponse>): ListMilestonesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.milestones = [];
        if (value !== undefined)
            reflectionMergePartial<ListMilestonesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListMilestonesResponse): ListMilestonesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated backend.v1.GetMilestoneStatusResponse milestones */ 1:
                    message.milestones.push(GetMilestoneStatusResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* backend.v1.PageResponse pagination */ 2:
                    message.pagination = PageResponse.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListMilestonesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated backend.v1.GetMilestoneStatusResponse milestones = 1; */
        for (let i = 0; i < message.milestones.length; i++)
            GetMilestoneStatusResponse.internalBinaryWrite(message.milestones[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* backend.v1.PageResponse pagination = 2; */
        if (message.pagination)
            PageResponse.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.ListMilestonesResponse
 */
export const ListMilestonesResponse = new ListMilestonesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBridgeTxRequest$Type extends MessageType<GetBridgeTxRequest> {
    constructor() {
        super("backend.v1.GetBridgeTxRequest", [
            { no: 1, name: "tx_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetBridgeTxRequest>): GetBridgeTxRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.txHash = "";
        if (value !== undefined)
            reflectionMergePartial<GetBridgeTxRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBridgeTxRequest): GetBridgeTxRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tx_hash */ 1:
                    message.txHash = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBridgeTxRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tx_hash = 1; */
        if (message.txHash !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.txHash);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetBridgeTxRequest
 */
export const GetBridgeTxRequest = new GetBridgeTxRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBridgeTxResponse$Type extends MessageType<GetBridgeTxResponse> {
    constructor() {
        super("backend.v1.GetBridgeTxResponse", [
            { no: 1, name: "tx_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "block_height", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 4, name: "token_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "amount", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "sender", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "recipient", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetBridgeTxResponse>): GetBridgeTxResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.txHash = "";
        message.status = "";
        message.blockHeight = "0";
        message.tokenAddress = "";
        message.amount = "";
        message.sender = "";
        message.recipient = "";
        if (value !== undefined)
            reflectionMergePartial<GetBridgeTxResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBridgeTxResponse): GetBridgeTxResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string tx_hash */ 1:
                    message.txHash = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* int64 block_height */ 3:
                    message.blockHeight = reader.int64().toString();
                    break;
                case /* string token_address */ 4:
                    message.tokenAddress = reader.string();
                    break;
                case /* string amount */ 5:
                    message.amount = reader.string();
                    break;
                case /* string sender */ 6:
                    message.sender = reader.string();
                    break;
                case /* string recipient */ 7:
                    message.recipient = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBridgeTxResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string tx_hash = 1; */
        if (message.txHash !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.txHash);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* int64 block_height = 3; */
        if (message.blockHeight !== "0")
            writer.tag(3, WireType.Varint).int64(message.blockHeight);
        /* string token_address = 4; */
        if (message.tokenAddress !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.tokenAddress);
        /* string amount = 5; */
        if (message.amount !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.amount);
        /* string sender = 6; */
        if (message.sender !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.sender);
        /* string recipient = 7; */
        if (message.recipient !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.recipient);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetBridgeTxResponse
 */
export const GetBridgeTxResponse = new GetBridgeTxResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBridgeVolumeRequest$Type extends MessageType<GetBridgeVolumeRequest> {
    constructor() {
        super("backend.v1.GetBridgeVolumeRequest", [
            { no: 1, name: "token_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "chain_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "timeframe", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetBridgeVolumeRequest>): GetBridgeVolumeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tokenAddress = "";
        message.chainId = "";
        message.timeframe = "";
        if (value !== undefined)
            reflectionMergePartial<GetBridgeVolumeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBridgeVolumeRequest): GetBridgeVolumeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string token_address */ 1:
                    message.tokenAddress = reader.string();
                    break;
                case /* string chain_id */ 2:
                    message.chainId = reader.string();
                    break;
                case /* string timeframe */ 3:
                    message.timeframe = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBridgeVolumeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string token_address = 1; */
        if (message.tokenAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tokenAddress);
        /* string chain_id = 2; */
        if (message.chainId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.chainId);
        /* string timeframe = 3; */
        if (message.timeframe !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.timeframe);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetBridgeVolumeRequest
 */
export const GetBridgeVolumeRequest = new GetBridgeVolumeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBridgeVolumeResponse$Type extends MessageType<GetBridgeVolumeResponse> {
    constructor() {
        super("backend.v1.GetBridgeVolumeResponse", [
            { no: 1, name: "total_minted", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "total_burned", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "volume_usd", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "transaction_count", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetBridgeVolumeResponse>): GetBridgeVolumeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.totalMinted = "";
        message.totalBurned = "";
        message.volumeUsd = "";
        message.transactionCount = "0";
        if (value !== undefined)
            reflectionMergePartial<GetBridgeVolumeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBridgeVolumeResponse): GetBridgeVolumeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string total_minted */ 1:
                    message.totalMinted = reader.string();
                    break;
                case /* string total_burned */ 2:
                    message.totalBurned = reader.string();
                    break;
                case /* string volume_usd */ 3:
                    message.volumeUsd = reader.string();
                    break;
                case /* int64 transaction_count */ 4:
                    message.transactionCount = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBridgeVolumeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string total_minted = 1; */
        if (message.totalMinted !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.totalMinted);
        /* string total_burned = 2; */
        if (message.totalBurned !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.totalBurned);
        /* string volume_usd = 3; */
        if (message.volumeUsd !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.volumeUsd);
        /* int64 transaction_count = 4; */
        if (message.transactionCount !== "0")
            writer.tag(4, WireType.Varint).int64(message.transactionCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetBridgeVolumeResponse
 */
export const GetBridgeVolumeResponse = new GetBridgeVolumeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetValidatorUptimeRequest$Type extends MessageType<GetValidatorUptimeRequest> {
    constructor() {
        super("backend.v1.GetValidatorUptimeRequest", [
            { no: 1, name: "validator_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetValidatorUptimeRequest>): GetValidatorUptimeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.validatorAddress = "";
        if (value !== undefined)
            reflectionMergePartial<GetValidatorUptimeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetValidatorUptimeRequest): GetValidatorUptimeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string validator_address */ 1:
                    message.validatorAddress = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetValidatorUptimeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string validator_address = 1; */
        if (message.validatorAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.validatorAddress);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetValidatorUptimeRequest
 */
export const GetValidatorUptimeRequest = new GetValidatorUptimeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetValidatorUptimeResponse$Type extends MessageType<GetValidatorUptimeResponse> {
    constructor() {
        super("backend.v1.GetValidatorUptimeResponse", [
            { no: 1, name: "validator_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "total_blocks", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "missed_blocks", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 4, name: "uptime_percentage", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<GetValidatorUptimeResponse>): GetValidatorUptimeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.validatorAddress = "";
        message.totalBlocks = "0";
        message.missedBlocks = "0";
        message.uptimePercentage = 0;
        if (value !== undefined)
            reflectionMergePartial<GetValidatorUptimeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetValidatorUptimeResponse): GetValidatorUptimeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string validator_address */ 1:
                    message.validatorAddress = reader.string();
                    break;
                case /* int64 total_blocks */ 2:
                    message.totalBlocks = reader.int64().toString();
                    break;
                case /* int64 missed_blocks */ 3:
                    message.missedBlocks = reader.int64().toString();
                    break;
                case /* double uptime_percentage */ 4:
                    message.uptimePercentage = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetValidatorUptimeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string validator_address = 1; */
        if (message.validatorAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.validatorAddress);
        /* int64 total_blocks = 2; */
        if (message.totalBlocks !== "0")
            writer.tag(2, WireType.Varint).int64(message.totalBlocks);
        /* int64 missed_blocks = 3; */
        if (message.missedBlocks !== "0")
            writer.tag(3, WireType.Varint).int64(message.missedBlocks);
        /* double uptime_percentage = 4; */
        if (message.uptimePercentage !== 0)
            writer.tag(4, WireType.Bit64).double(message.uptimePercentage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetValidatorUptimeResponse
 */
export const GetValidatorUptimeResponse = new GetValidatorUptimeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOracleParticipationRequest$Type extends MessageType<GetOracleParticipationRequest> {
    constructor() {
        super("backend.v1.GetOracleParticipationRequest", [
            { no: 1, name: "oracle_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetOracleParticipationRequest>): GetOracleParticipationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.oracleAddress = "";
        if (value !== undefined)
            reflectionMergePartial<GetOracleParticipationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOracleParticipationRequest): GetOracleParticipationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string oracle_address */ 1:
                    message.oracleAddress = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOracleParticipationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string oracle_address = 1; */
        if (message.oracleAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.oracleAddress);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetOracleParticipationRequest
 */
export const GetOracleParticipationRequest = new GetOracleParticipationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOracleParticipationResponse$Type extends MessageType<GetOracleParticipationResponse> {
    constructor() {
        super("backend.v1.GetOracleParticipationResponse", [
            { no: 1, name: "oracle_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "total_requests", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "successful_reveals", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 4, name: "participation_rate", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<GetOracleParticipationResponse>): GetOracleParticipationResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.oracleAddress = "";
        message.totalRequests = "0";
        message.successfulReveals = "0";
        message.participationRate = 0;
        if (value !== undefined)
            reflectionMergePartial<GetOracleParticipationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOracleParticipationResponse): GetOracleParticipationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string oracle_address */ 1:
                    message.oracleAddress = reader.string();
                    break;
                case /* int64 total_requests */ 2:
                    message.totalRequests = reader.int64().toString();
                    break;
                case /* int64 successful_reveals */ 3:
                    message.successfulReveals = reader.int64().toString();
                    break;
                case /* double participation_rate */ 4:
                    message.participationRate = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOracleParticipationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string oracle_address = 1; */
        if (message.oracleAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.oracleAddress);
        /* int64 total_requests = 2; */
        if (message.totalRequests !== "0")
            writer.tag(2, WireType.Varint).int64(message.totalRequests);
        /* int64 successful_reveals = 3; */
        if (message.successfulReveals !== "0")
            writer.tag(3, WireType.Varint).int64(message.successfulReveals);
        /* double participation_rate = 4; */
        if (message.participationRate !== 0)
            writer.tag(4, WireType.Bit64).double(message.participationRate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetOracleParticipationResponse
 */
export const GetOracleParticipationResponse = new GetOracleParticipationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSettlementRequest$Type extends MessageType<GetSettlementRequest> {
    constructor() {
        super("backend.v1.GetSettlementRequest", [
            { no: 1, name: "settlement_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetSettlementRequest>): GetSettlementRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.settlementId = "";
        if (value !== undefined)
            reflectionMergePartial<GetSettlementRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSettlementRequest): GetSettlementRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string settlement_id */ 1:
                    message.settlementId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSettlementRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string settlement_id = 1; */
        if (message.settlementId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.settlementId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetSettlementRequest
 */
export const GetSettlementRequest = new GetSettlementRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSettlementResponse$Type extends MessageType<GetSettlementResponse> {
    constructor() {
        super("backend.v1.GetSettlementResponse", [
            { no: 1, name: "settlement_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "proof", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "block_height", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "signatures", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetSettlementResponse>): GetSettlementResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.settlementId = "";
        message.proof = new Uint8Array(0);
        message.status = "";
        message.blockHeight = "0";
        message.signatures = [];
        if (value !== undefined)
            reflectionMergePartial<GetSettlementResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSettlementResponse): GetSettlementResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string settlement_id */ 1:
                    message.settlementId = reader.string();
                    break;
                case /* bytes proof */ 2:
                    message.proof = reader.bytes();
                    break;
                case /* string status */ 3:
                    message.status = reader.string();
                    break;
                case /* int64 block_height */ 4:
                    message.blockHeight = reader.int64().toString();
                    break;
                case /* repeated string signatures */ 5:
                    message.signatures.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSettlementResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string settlement_id = 1; */
        if (message.settlementId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.settlementId);
        /* bytes proof = 2; */
        if (message.proof.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.proof);
        /* string status = 3; */
        if (message.status !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.status);
        /* int64 block_height = 4; */
        if (message.blockHeight !== "0")
            writer.tag(4, WireType.Varint).int64(message.blockHeight);
        /* repeated string signatures = 5; */
        for (let i = 0; i < message.signatures.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.signatures[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetSettlementResponse
 */
export const GetSettlementResponse = new GetSettlementResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMilestoneStatusRequest$Type extends MessageType<GetMilestoneStatusRequest> {
    constructor() {
        super("backend.v1.GetMilestoneStatusRequest", [
            { no: 1, name: "milestone_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetMilestoneStatusRequest>): GetMilestoneStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.milestoneId = "";
        if (value !== undefined)
            reflectionMergePartial<GetMilestoneStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMilestoneStatusRequest): GetMilestoneStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string milestone_id */ 1:
                    message.milestoneId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMilestoneStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string milestone_id = 1; */
        if (message.milestoneId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.milestoneId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetMilestoneStatusRequest
 */
export const GetMilestoneStatusRequest = new GetMilestoneStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMilestoneStatusResponse$Type extends MessageType<GetMilestoneStatusResponse> {
    constructor() {
        super("backend.v1.GetMilestoneStatusResponse", [
            { no: 1, name: "milestone_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "block_height", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetMilestoneStatusResponse>): GetMilestoneStatusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.milestoneId = "";
        message.status = "";
        message.blockHeight = "0";
        if (value !== undefined)
            reflectionMergePartial<GetMilestoneStatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMilestoneStatusResponse): GetMilestoneStatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string milestone_id */ 1:
                    message.milestoneId = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* int64 block_height */ 3:
                    message.blockHeight = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMilestoneStatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string milestone_id = 1; */
        if (message.milestoneId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.milestoneId);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* int64 block_height = 3; */
        if (message.blockHeight !== "0")
            writer.tag(3, WireType.Varint).int64(message.blockHeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetMilestoneStatusResponse
 */
export const GetMilestoneStatusResponse = new GetMilestoneStatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBridgePendingRequest$Type extends MessageType<GetBridgePendingRequest> {
    constructor() {
        super("backend.v1.GetBridgePendingRequest", [
            { no: 1, name: "nonce", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetBridgePendingRequest>): GetBridgePendingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.nonce = "0";
        if (value !== undefined)
            reflectionMergePartial<GetBridgePendingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBridgePendingRequest): GetBridgePendingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 nonce */ 1:
                    message.nonce = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBridgePendingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 nonce = 1; */
        if (message.nonce !== "0")
            writer.tag(1, WireType.Varint).uint64(message.nonce);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetBridgePendingRequest
 */
export const GetBridgePendingRequest = new GetBridgePendingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBridgePendingResponse$Type extends MessageType<GetBridgePendingResponse> {
    constructor() {
        super("backend.v1.GetBridgePendingResponse", [
            { no: 1, name: "nonce", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "token_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "amount", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "recipient", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetBridgePendingResponse>): GetBridgePendingResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.nonce = "0";
        message.tokenAddress = "";
        message.amount = "";
        message.recipient = "";
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<GetBridgePendingResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBridgePendingResponse): GetBridgePendingResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 nonce */ 1:
                    message.nonce = reader.uint64().toString();
                    break;
                case /* string token_address */ 2:
                    message.tokenAddress = reader.string();
                    break;
                case /* string amount */ 3:
                    message.amount = reader.string();
                    break;
                case /* string recipient */ 4:
                    message.recipient = reader.string();
                    break;
                case /* string status */ 5:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBridgePendingResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 nonce = 1; */
        if (message.nonce !== "0")
            writer.tag(1, WireType.Varint).uint64(message.nonce);
        /* string token_address = 2; */
        if (message.tokenAddress !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tokenAddress);
        /* string amount = 3; */
        if (message.amount !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.amount);
        /* string recipient = 4; */
        if (message.recipient !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.recipient);
        /* string status = 5; */
        if (message.status !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetBridgePendingResponse
 */
export const GetBridgePendingResponse = new GetBridgePendingResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTpsRequest$Type extends MessageType<GetTpsRequest> {
    constructor() {
        super("backend.v1.GetTpsRequest", []);
    }
    create(value?: PartialMessage<GetTpsRequest>): GetTpsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetTpsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTpsRequest): GetTpsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTpsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetTpsRequest
 */
export const GetTpsRequest = new GetTpsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTpsResponse$Type extends MessageType<GetTpsResponse> {
    constructor() {
        super("backend.v1.GetTpsResponse", [
            { no: 1, name: "tps_avg", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "tps_peak", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "total_txs", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetTpsResponse>): GetTpsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tpsAvg = 0;
        message.tpsPeak = 0;
        message.totalTxs = "0";
        if (value !== undefined)
            reflectionMergePartial<GetTpsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTpsResponse): GetTpsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double tps_avg */ 1:
                    message.tpsAvg = reader.double();
                    break;
                case /* double tps_peak */ 2:
                    message.tpsPeak = reader.double();
                    break;
                case /* int64 total_txs */ 3:
                    message.totalTxs = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTpsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double tps_avg = 1; */
        if (message.tpsAvg !== 0)
            writer.tag(1, WireType.Bit64).double(message.tpsAvg);
        /* double tps_peak = 2; */
        if (message.tpsPeak !== 0)
            writer.tag(2, WireType.Bit64).double(message.tpsPeak);
        /* int64 total_txs = 3; */
        if (message.totalTxs !== "0")
            writer.tag(3, WireType.Varint).int64(message.totalTxs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetTpsResponse
 */
export const GetTpsResponse = new GetTpsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBlockStatsRequest$Type extends MessageType<GetBlockStatsRequest> {
    constructor() {
        super("backend.v1.GetBlockStatsRequest", []);
    }
    create(value?: PartialMessage<GetBlockStatsRequest>): GetBlockStatsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetBlockStatsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBlockStatsRequest): GetBlockStatsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBlockStatsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetBlockStatsRequest
 */
export const GetBlockStatsRequest = new GetBlockStatsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBlockStatsResponse$Type extends MessageType<GetBlockStatsResponse> {
    constructor() {
        super("backend.v1.GetBlockStatsResponse", [
            { no: 1, name: "avg_ms", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "max_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetBlockStatsResponse>): GetBlockStatsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.avgMs = 0;
        message.maxMs = "0";
        if (value !== undefined)
            reflectionMergePartial<GetBlockStatsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBlockStatsResponse): GetBlockStatsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double avg_ms */ 1:
                    message.avgMs = reader.double();
                    break;
                case /* int64 max_ms */ 2:
                    message.maxMs = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBlockStatsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double avg_ms = 1; */
        if (message.avgMs !== 0)
            writer.tag(1, WireType.Bit64).double(message.avgMs);
        /* int64 max_ms = 2; */
        if (message.maxMs !== "0")
            writer.tag(2, WireType.Varint).int64(message.maxMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetBlockStatsResponse
 */
export const GetBlockStatsResponse = new GetBlockStatsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOraclePriceRequest$Type extends MessageType<GetOraclePriceRequest> {
    constructor() {
        super("backend.v1.GetOraclePriceRequest", [
            { no: 1, name: "asset_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetOraclePriceRequest>): GetOraclePriceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.assetId = "";
        if (value !== undefined)
            reflectionMergePartial<GetOraclePriceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOraclePriceRequest): GetOraclePriceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string asset_id */ 1:
                    message.assetId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOraclePriceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string asset_id = 1; */
        if (message.assetId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.assetId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetOraclePriceRequest
 */
export const GetOraclePriceRequest = new GetOraclePriceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOraclePriceResponse$Type extends MessageType<GetOraclePriceResponse> {
    constructor() {
        super("backend.v1.GetOraclePriceResponse", [
            { no: 1, name: "asset_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "open", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "high", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "low", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "close", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "submission_count", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetOraclePriceResponse>): GetOraclePriceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.assetId = "";
        message.open = 0;
        message.high = 0;
        message.low = 0;
        message.close = 0;
        message.submissionCount = "0";
        if (value !== undefined)
            reflectionMergePartial<GetOraclePriceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOraclePriceResponse): GetOraclePriceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string asset_id */ 1:
                    message.assetId = reader.string();
                    break;
                case /* double open */ 2:
                    message.open = reader.double();
                    break;
                case /* double high */ 3:
                    message.high = reader.double();
                    break;
                case /* double low */ 4:
                    message.low = reader.double();
                    break;
                case /* double close */ 5:
                    message.close = reader.double();
                    break;
                case /* int64 submission_count */ 6:
                    message.submissionCount = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOraclePriceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string asset_id = 1; */
        if (message.assetId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.assetId);
        /* double open = 2; */
        if (message.open !== 0)
            writer.tag(2, WireType.Bit64).double(message.open);
        /* double high = 3; */
        if (message.high !== 0)
            writer.tag(3, WireType.Bit64).double(message.high);
        /* double low = 4; */
        if (message.low !== 0)
            writer.tag(4, WireType.Bit64).double(message.low);
        /* double close = 5; */
        if (message.close !== 0)
            writer.tag(5, WireType.Bit64).double(message.close);
        /* int64 submission_count = 6; */
        if (message.submissionCount !== "0")
            writer.tag(6, WireType.Varint).int64(message.submissionCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.GetOraclePriceResponse
 */
export const GetOraclePriceResponse = new GetOraclePriceResponse$Type();
/**
 * @generated ServiceType for protobuf service backend.v1.QueryService
 */
export const QueryService = new ServiceType("backend.v1.QueryService", [
    { name: "GetBridgeVolume", options: { "google.api.http": { get: "/api/rest/v1/bridge/volume" } }, I: GetBridgeVolumeRequest, O: GetBridgeVolumeResponse },
    { name: "GetValidatorUptime", options: { "google.api.http": { get: "/api/rest/v1/validator/uptime/{validator_address}" } }, I: GetValidatorUptimeRequest, O: GetValidatorUptimeResponse },
    { name: "GetOracleParticipation", options: { "google.api.http": { get: "/api/rest/v1/oracle/participation/{oracle_address}" } }, I: GetOracleParticipationRequest, O: GetOracleParticipationResponse },
    { name: "GetSettlement", options: { "google.api.http": { get: "/api/rest/v1/settlement/{settlement_id}" } }, I: GetSettlementRequest, O: GetSettlementResponse },
    { name: "GetMilestoneStatus", options: { "google.api.http": { get: "/api/rest/v1/milestone/{milestone_id}" } }, I: GetMilestoneStatusRequest, O: GetMilestoneStatusResponse },
    { name: "GetBridgePending", options: { "google.api.http": { get: "/api/rest/v1/bridge/pending/{nonce}" } }, I: GetBridgePendingRequest, O: GetBridgePendingResponse },
    { name: "GetTps", options: { "google.api.http": { get: "/api/rest/v1/analytics/tps" } }, I: GetTpsRequest, O: GetTpsResponse },
    { name: "GetBlockStats", options: { "google.api.http": { get: "/api/rest/v1/analytics/blocks" } }, I: GetBlockStatsRequest, O: GetBlockStatsResponse },
    { name: "GetOraclePrice", options: { "google.api.http": { get: "/api/rest/v1/analytics/oracle/price" } }, I: GetOraclePriceRequest, O: GetOraclePriceResponse },
    { name: "ListSettlements", options: { "google.api.http": { get: "/api/rest/v1/settlements" } }, I: ListSettlementsRequest, O: ListSettlementsResponse },
    { name: "ListMilestones", options: { "google.api.http": { get: "/api/rest/v1/milestones" } }, I: ListMilestonesRequest, O: ListMilestonesResponse },
    { name: "GetBridgeTx", options: { "google.api.http": { get: "/api/rest/v1/bridge/tx/{tx_hash}" } }, I: GetBridgeTxRequest, O: GetBridgeTxResponse }
]);
