// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "backend/v1/stream.proto" (package "backend.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message backend.v1.StreamBridgeEventsRequest
 */
export interface StreamBridgeEventsRequest {
    /**
     * @generated from protobuf field: string token_address = 1
     */
    tokenAddress: string;
}
/**
 * @generated from protobuf message backend.v1.BridgeEvent
 */
export interface BridgeEvent {
    /**
     * @generated from protobuf field: string event_type = 1
     */
    eventType: string; // "mint" or "burn"
    /**
     * @generated from protobuf field: string token_address = 2
     */
    tokenAddress: string;
    /**
     * @generated from protobuf field: string amount = 3
     */
    amount: string;
    /**
     * @generated from protobuf field: string sender = 4
     */
    sender: string;
    /**
     * @generated from protobuf field: string recipient = 5
     */
    recipient: string;
    /**
     * @generated from protobuf field: int64 block_height = 6
     */
    blockHeight: string;
    /**
     * @generated from protobuf field: string tx_hash = 7
     */
    txHash: string;
}
/**
 * @generated from protobuf message backend.v1.StreamOracleEventsRequest
 */
export interface StreamOracleEventsRequest {
    /**
     * @generated from protobuf field: string oracle_address = 1
     */
    oracleAddress: string;
}
/**
 * @generated from protobuf message backend.v1.OracleEvent
 */
export interface OracleEvent {
    /**
     * @generated from protobuf field: string oracle_address = 1
     */
    oracleAddress: string;
    /**
     * @generated from protobuf field: string request_id = 2
     */
    requestId: string;
    /**
     * @generated from protobuf field: string data_type = 3
     */
    dataType: string;
    /**
     * @generated from protobuf field: string payload = 4
     */
    payload: string;
    /**
     * @generated from protobuf field: int64 block_height = 5
     */
    blockHeight: string;
    /**
     * @generated from protobuf field: string status = 6
     */
    status: string; // e.g., "requested", "revealed"
}
/**
 * @generated from protobuf message backend.v1.StreamMilestoneEventsRequest
 */
export interface StreamMilestoneEventsRequest {
    /**
     * @generated from protobuf field: string milestone_id = 1
     */
    milestoneId: string;
}
/**
 * @generated from protobuf message backend.v1.MilestoneEvent
 */
export interface MilestoneEvent {
    /**
     * @generated from protobuf field: string milestone_id = 1
     */
    milestoneId: string;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string; // "pending", "achieved", "stale"
    /**
     * @generated from protobuf field: int64 block_height = 3
     */
    blockHeight: string;
}
/**
 * @generated from protobuf message backend.v1.StreamChainStatsRequest
 */
export interface StreamChainStatsRequest {
}
/**
 * @generated from protobuf message backend.v1.ChainStatsEvent
 */
export interface ChainStatsEvent {
    /**
     * @generated from protobuf field: double tps_avg = 1
     */
    tpsAvg: number;
    /**
     * @generated from protobuf field: double tps_peak = 2
     */
    tpsPeak: number;
    /**
     * @generated from protobuf field: int64 total_txs = 3
     */
    totalTxs: string;
    /**
     * @generated from protobuf field: double avg_block_time_ms = 4
     */
    avgBlockTimeMs: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class StreamBridgeEventsRequest$Type extends MessageType<StreamBridgeEventsRequest> {
    constructor() {
        super("backend.v1.StreamBridgeEventsRequest", [
            { no: 1, name: "token_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StreamBridgeEventsRequest>): StreamBridgeEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tokenAddress = "";
        if (value !== undefined)
            reflectionMergePartial<StreamBridgeEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamBridgeEventsRequest): StreamBridgeEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string token_address */ 1:
                    message.tokenAddress = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamBridgeEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string token_address = 1; */
        if (message.tokenAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tokenAddress);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.StreamBridgeEventsRequest
 */
export const StreamBridgeEventsRequest = new StreamBridgeEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BridgeEvent$Type extends MessageType<BridgeEvent> {
    constructor() {
        super("backend.v1.BridgeEvent", [
            { no: 1, name: "event_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "token_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "amount", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "sender", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "recipient", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "block_height", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 7, name: "tx_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BridgeEvent>): BridgeEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventType = "";
        message.tokenAddress = "";
        message.amount = "";
        message.sender = "";
        message.recipient = "";
        message.blockHeight = "0";
        message.txHash = "";
        if (value !== undefined)
            reflectionMergePartial<BridgeEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BridgeEvent): BridgeEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_type */ 1:
                    message.eventType = reader.string();
                    break;
                case /* string token_address */ 2:
                    message.tokenAddress = reader.string();
                    break;
                case /* string amount */ 3:
                    message.amount = reader.string();
                    break;
                case /* string sender */ 4:
                    message.sender = reader.string();
                    break;
                case /* string recipient */ 5:
                    message.recipient = reader.string();
                    break;
                case /* int64 block_height */ 6:
                    message.blockHeight = reader.int64().toString();
                    break;
                case /* string tx_hash */ 7:
                    message.txHash = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BridgeEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_type = 1; */
        if (message.eventType !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventType);
        /* string token_address = 2; */
        if (message.tokenAddress !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tokenAddress);
        /* string amount = 3; */
        if (message.amount !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.amount);
        /* string sender = 4; */
        if (message.sender !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.sender);
        /* string recipient = 5; */
        if (message.recipient !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.recipient);
        /* int64 block_height = 6; */
        if (message.blockHeight !== "0")
            writer.tag(6, WireType.Varint).int64(message.blockHeight);
        /* string tx_hash = 7; */
        if (message.txHash !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.txHash);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.BridgeEvent
 */
export const BridgeEvent = new BridgeEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StreamOracleEventsRequest$Type extends MessageType<StreamOracleEventsRequest> {
    constructor() {
        super("backend.v1.StreamOracleEventsRequest", [
            { no: 1, name: "oracle_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StreamOracleEventsRequest>): StreamOracleEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.oracleAddress = "";
        if (value !== undefined)
            reflectionMergePartial<StreamOracleEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamOracleEventsRequest): StreamOracleEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string oracle_address */ 1:
                    message.oracleAddress = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamOracleEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string oracle_address = 1; */
        if (message.oracleAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.oracleAddress);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.StreamOracleEventsRequest
 */
export const StreamOracleEventsRequest = new StreamOracleEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OracleEvent$Type extends MessageType<OracleEvent> {
    constructor() {
        super("backend.v1.OracleEvent", [
            { no: 1, name: "oracle_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "payload", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "block_height", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 6, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<OracleEvent>): OracleEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.oracleAddress = "";
        message.requestId = "";
        message.dataType = "";
        message.payload = "";
        message.blockHeight = "0";
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<OracleEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OracleEvent): OracleEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string oracle_address */ 1:
                    message.oracleAddress = reader.string();
                    break;
                case /* string request_id */ 2:
                    message.requestId = reader.string();
                    break;
                case /* string data_type */ 3:
                    message.dataType = reader.string();
                    break;
                case /* string payload */ 4:
                    message.payload = reader.string();
                    break;
                case /* int64 block_height */ 5:
                    message.blockHeight = reader.int64().toString();
                    break;
                case /* string status */ 6:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OracleEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string oracle_address = 1; */
        if (message.oracleAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.oracleAddress);
        /* string request_id = 2; */
        if (message.requestId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.requestId);
        /* string data_type = 3; */
        if (message.dataType !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.dataType);
        /* string payload = 4; */
        if (message.payload !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.payload);
        /* int64 block_height = 5; */
        if (message.blockHeight !== "0")
            writer.tag(5, WireType.Varint).int64(message.blockHeight);
        /* string status = 6; */
        if (message.status !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.OracleEvent
 */
export const OracleEvent = new OracleEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StreamMilestoneEventsRequest$Type extends MessageType<StreamMilestoneEventsRequest> {
    constructor() {
        super("backend.v1.StreamMilestoneEventsRequest", [
            { no: 1, name: "milestone_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StreamMilestoneEventsRequest>): StreamMilestoneEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.milestoneId = "";
        if (value !== undefined)
            reflectionMergePartial<StreamMilestoneEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamMilestoneEventsRequest): StreamMilestoneEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string milestone_id */ 1:
                    message.milestoneId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamMilestoneEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string milestone_id = 1; */
        if (message.milestoneId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.milestoneId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.StreamMilestoneEventsRequest
 */
export const StreamMilestoneEventsRequest = new StreamMilestoneEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MilestoneEvent$Type extends MessageType<MilestoneEvent> {
    constructor() {
        super("backend.v1.MilestoneEvent", [
            { no: 1, name: "milestone_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "block_height", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<MilestoneEvent>): MilestoneEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.milestoneId = "";
        message.status = "";
        message.blockHeight = "0";
        if (value !== undefined)
            reflectionMergePartial<MilestoneEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MilestoneEvent): MilestoneEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string milestone_id */ 1:
                    message.milestoneId = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* int64 block_height */ 3:
                    message.blockHeight = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MilestoneEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string milestone_id = 1; */
        if (message.milestoneId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.milestoneId);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* int64 block_height = 3; */
        if (message.blockHeight !== "0")
            writer.tag(3, WireType.Varint).int64(message.blockHeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.MilestoneEvent
 */
export const MilestoneEvent = new MilestoneEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StreamChainStatsRequest$Type extends MessageType<StreamChainStatsRequest> {
    constructor() {
        super("backend.v1.StreamChainStatsRequest", []);
    }
    create(value?: PartialMessage<StreamChainStatsRequest>): StreamChainStatsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<StreamChainStatsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamChainStatsRequest): StreamChainStatsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamChainStatsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.StreamChainStatsRequest
 */
export const StreamChainStatsRequest = new StreamChainStatsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChainStatsEvent$Type extends MessageType<ChainStatsEvent> {
    constructor() {
        super("backend.v1.ChainStatsEvent", [
            { no: 1, name: "tps_avg", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "tps_peak", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "total_txs", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 4, name: "avg_block_time_ms", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<ChainStatsEvent>): ChainStatsEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tpsAvg = 0;
        message.tpsPeak = 0;
        message.totalTxs = "0";
        message.avgBlockTimeMs = 0;
        if (value !== undefined)
            reflectionMergePartial<ChainStatsEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChainStatsEvent): ChainStatsEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double tps_avg */ 1:
                    message.tpsAvg = reader.double();
                    break;
                case /* double tps_peak */ 2:
                    message.tpsPeak = reader.double();
                    break;
                case /* int64 total_txs */ 3:
                    message.totalTxs = reader.int64().toString();
                    break;
                case /* double avg_block_time_ms */ 4:
                    message.avgBlockTimeMs = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChainStatsEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double tps_avg = 1; */
        if (message.tpsAvg !== 0)
            writer.tag(1, WireType.Bit64).double(message.tpsAvg);
        /* double tps_peak = 2; */
        if (message.tpsPeak !== 0)
            writer.tag(2, WireType.Bit64).double(message.tpsPeak);
        /* int64 total_txs = 3; */
        if (message.totalTxs !== "0")
            writer.tag(3, WireType.Varint).int64(message.totalTxs);
        /* double avg_block_time_ms = 4; */
        if (message.avgBlockTimeMs !== 0)
            writer.tag(4, WireType.Bit64).double(message.avgBlockTimeMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message backend.v1.ChainStatsEvent
 */
export const ChainStatsEvent = new ChainStatsEvent$Type();
/**
 * @generated ServiceType for protobuf service backend.v1.StreamService
 */
export const StreamService = new ServiceType("backend.v1.StreamService", [
    { name: "StreamBridgeEvents", serverStreaming: true, options: { "google.api.http": { get: "/api/rest/v1/stream/bridge" } }, I: StreamBridgeEventsRequest, O: BridgeEvent },
    { name: "StreamOracleEvents", serverStreaming: true, options: { "google.api.http": { get: "/api/rest/v1/stream/oracle" } }, I: StreamOracleEventsRequest, O: OracleEvent },
    { name: "StreamMilestoneEvents", serverStreaming: true, options: { "google.api.http": { get: "/api/rest/v1/stream/milestone" } }, I: StreamMilestoneEventsRequest, O: MilestoneEvent },
    { name: "StreamChainStats", serverStreaming: true, options: { "google.api.http": { get: "/api/rest/v1/stream/stats" } }, I: StreamChainStatsRequest, O: ChainStatsEvent }
]);
