// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "backend/v1/stream.proto" (package "backend.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { StreamService } from "./stream";
import type { ChainStatsEvent } from "./stream";
import type { StreamChainStatsRequest } from "./stream";
import type { MilestoneEvent } from "./stream";
import type { StreamMilestoneEventsRequest } from "./stream";
import type { OracleEvent } from "./stream";
import type { StreamOracleEventsRequest } from "./stream";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { BridgeEvent } from "./stream";
import type { StreamBridgeEventsRequest } from "./stream";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service backend.v1.StreamService
 */
export interface IStreamServiceClient {
    /**
     * @generated from protobuf rpc: StreamBridgeEvents
     */
    streamBridgeEvents(input: StreamBridgeEventsRequest, options?: RpcOptions): ServerStreamingCall<StreamBridgeEventsRequest, BridgeEvent>;
    /**
     * @generated from protobuf rpc: StreamOracleEvents
     */
    streamOracleEvents(input: StreamOracleEventsRequest, options?: RpcOptions): ServerStreamingCall<StreamOracleEventsRequest, OracleEvent>;
    /**
     * @generated from protobuf rpc: StreamMilestoneEvents
     */
    streamMilestoneEvents(input: StreamMilestoneEventsRequest, options?: RpcOptions): ServerStreamingCall<StreamMilestoneEventsRequest, MilestoneEvent>;
    /**
     * @generated from protobuf rpc: StreamChainStats
     */
    streamChainStats(input: StreamChainStatsRequest, options?: RpcOptions): ServerStreamingCall<StreamChainStatsRequest, ChainStatsEvent>;
}
/**
 * @generated from protobuf service backend.v1.StreamService
 */
export class StreamServiceClient implements IStreamServiceClient, ServiceInfo {
    typeName = StreamService.typeName;
    methods = StreamService.methods;
    options = StreamService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: StreamBridgeEvents
     */
    streamBridgeEvents(input: StreamBridgeEventsRequest, options?: RpcOptions): ServerStreamingCall<StreamBridgeEventsRequest, BridgeEvent> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamBridgeEventsRequest, BridgeEvent>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StreamOracleEvents
     */
    streamOracleEvents(input: StreamOracleEventsRequest, options?: RpcOptions): ServerStreamingCall<StreamOracleEventsRequest, OracleEvent> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamOracleEventsRequest, OracleEvent>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StreamMilestoneEvents
     */
    streamMilestoneEvents(input: StreamMilestoneEventsRequest, options?: RpcOptions): ServerStreamingCall<StreamMilestoneEventsRequest, MilestoneEvent> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamMilestoneEventsRequest, MilestoneEvent>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StreamChainStats
     */
    streamChainStats(input: StreamChainStatsRequest, options?: RpcOptions): ServerStreamingCall<StreamChainStatsRequest, ChainStatsEvent> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamChainStatsRequest, ChainStatsEvent>("serverStreaming", this._transport, method, opt, input);
    }
}
