// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: explorer/v1/explorer.proto

package explorerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExplorerService_GetBlock_FullMethodName                 = "/explorer.v1.ExplorerService/GetBlock"
	ExplorerService_ListBlocks_FullMethodName               = "/explorer.v1.ExplorerService/ListBlocks"
	ExplorerService_GetTx_FullMethodName                    = "/explorer.v1.ExplorerService/GetTx"
	ExplorerService_ListTxs_FullMethodName                  = "/explorer.v1.ExplorerService/ListTxs"
	ExplorerService_ListTxsByAddress_FullMethodName         = "/explorer.v1.ExplorerService/ListTxsByAddress"
	ExplorerService_GetAddress_FullMethodName               = "/explorer.v1.ExplorerService/GetAddress"
	ExplorerService_GetValidator_FullMethodName             = "/explorer.v1.ExplorerService/GetValidator"
	ExplorerService_ListValidators_FullMethodName           = "/explorer.v1.ExplorerService/ListValidators"
	ExplorerService_GetStakingStats_FullMethodName          = "/explorer.v1.ExplorerService/GetStakingStats"
	ExplorerService_GetOracleFeed_FullMethodName            = "/explorer.v1.ExplorerService/GetOracleFeed"
	ExplorerService_GetOracleRound_FullMethodName           = "/explorer.v1.ExplorerService/GetOracleRound"
	ExplorerService_ListOracleRounds_FullMethodName         = "/explorer.v1.ExplorerService/ListOracleRounds"
	ExplorerService_GetMilestone_FullMethodName             = "/explorer.v1.ExplorerService/GetMilestone"
	ExplorerService_ListMilestones_FullMethodName           = "/explorer.v1.ExplorerService/ListMilestones"
	ExplorerService_GetSettlement_FullMethodName            = "/explorer.v1.ExplorerService/GetSettlement"
	ExplorerService_ListSettlements_FullMethodName          = "/explorer.v1.ExplorerService/ListSettlements"
	ExplorerService_GetContract_FullMethodName              = "/explorer.v1.ExplorerService/GetContract"
	ExplorerService_ListContracts_FullMethodName            = "/explorer.v1.ExplorerService/ListContracts"
	ExplorerService_GetCode_FullMethodName                  = "/explorer.v1.ExplorerService/GetCode"
	ExplorerService_ListCodes_FullMethodName                = "/explorer.v1.ExplorerService/ListCodes"
	ExplorerService_GetGovernanceProposal_FullMethodName    = "/explorer.v1.ExplorerService/GetGovernanceProposal"
	ExplorerService_ListProposals_FullMethodName            = "/explorer.v1.ExplorerService/ListProposals"
	ExplorerService_ListIbcChannels_FullMethodName          = "/explorer.v1.ExplorerService/ListIbcChannels"
	ExplorerService_GetIbcChannel_FullMethodName            = "/explorer.v1.ExplorerService/GetIbcChannel"
	ExplorerService_ListIbcAssets_FullMethodName            = "/explorer.v1.ExplorerService/ListIbcAssets"
	ExplorerService_GetCw20Token_FullMethodName             = "/explorer.v1.ExplorerService/GetCw20Token"
	ExplorerService_GetCw721Collection_FullMethodName       = "/explorer.v1.ExplorerService/GetCw721Collection"
	ExplorerService_GetCw721Token_FullMethodName            = "/explorer.v1.ExplorerService/GetCw721Token"
	ExplorerService_StreamLatestBlocks_FullMethodName       = "/explorer.v1.ExplorerService/StreamLatestBlocks"
	ExplorerService_StreamConsensusRound_FullMethodName     = "/explorer.v1.ExplorerService/StreamConsensusRound"
	ExplorerService_GetBridgeTx_FullMethodName              = "/explorer.v1.ExplorerService/GetBridgeTx"
	ExplorerService_ListBridgeTxs_FullMethodName            = "/explorer.v1.ExplorerService/ListBridgeTxs"
	ExplorerService_GetBridgeSupplyMetrics_FullMethodName   = "/explorer.v1.ExplorerService/GetBridgeSupplyMetrics"
	ExplorerService_ListRelayers_FullMethodName             = "/explorer.v1.ExplorerService/ListRelayers"
	ExplorerService_ListBridgeCircuitBreaker_FullMethodName = "/explorer.v1.ExplorerService/ListBridgeCircuitBreaker"
	ExplorerService_ListBridgeNonces_FullMethodName         = "/explorer.v1.ExplorerService/ListBridgeNonces"
	ExplorerService_GetTpsHistory_FullMethodName            = "/explorer.v1.ExplorerService/GetTpsHistory"
	ExplorerService_GetBlockTimeHistory_FullMethodName      = "/explorer.v1.ExplorerService/GetBlockTimeHistory"
	ExplorerService_GetValidatorUptimeGrid_FullMethodName   = "/explorer.v1.ExplorerService/GetValidatorUptimeGrid"
	ExplorerService_GetBridgeVolumeHistory_FullMethodName   = "/explorer.v1.ExplorerService/GetBridgeVolumeHistory"
	ExplorerService_ExportTxsCsv_FullMethodName             = "/explorer.v1.ExplorerService/ExportTxsCsv"
	ExplorerService_SearchGlobal_FullMethodName             = "/explorer.v1.ExplorerService/SearchGlobal"
	ExplorerService_RegisterWebhook_FullMethodName          = "/explorer.v1.ExplorerService/RegisterWebhook"
	ExplorerService_ListWebhooks_FullMethodName             = "/explorer.v1.ExplorerService/ListWebhooks"
	ExplorerService_DeleteWebhook_FullMethodName            = "/explorer.v1.ExplorerService/DeleteWebhook"
	ExplorerService_GetSystemStatus_FullMethodName          = "/explorer.v1.ExplorerService/GetSystemStatus"
)

// ExplorerServiceClient is the client API for ExplorerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExplorerServiceClient interface {
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*BlockDetail, error)
	ListBlocks(ctx context.Context, in *ListBlocksRequest, opts ...grpc.CallOption) (*BlockList, error)
	GetTx(ctx context.Context, in *GetTxRequest, opts ...grpc.CallOption) (*TxDetail, error)
	ListTxs(ctx context.Context, in *ListTxsRequest, opts ...grpc.CallOption) (*TxList, error)
	ListTxsByAddress(ctx context.Context, in *ListTxsByAddressRequest, opts ...grpc.CallOption) (*TxList, error)
	GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*AccountDetail, error)
	GetValidator(ctx context.Context, in *GetValidatorRequest, opts ...grpc.CallOption) (*ValidatorDetail, error)
	ListValidators(ctx context.Context, in *ListValidatorsRequest, opts ...grpc.CallOption) (*ValidatorSlotGrid, error)
	GetStakingStats(ctx context.Context, in *GetStakingStatsRequest, opts ...grpc.CallOption) (*StakingStats, error)
	GetOracleFeed(ctx context.Context, in *GetOracleFeedRequest, opts ...grpc.CallOption) (*FeedDetail, error)
	GetOracleRound(ctx context.Context, in *GetOracleRoundRequest, opts ...grpc.CallOption) (*RoundDetail, error)
	ListOracleRounds(ctx context.Context, in *ListOracleRoundsRequest, opts ...grpc.CallOption) (*RoundList, error)
	GetMilestone(ctx context.Context, in *GetMilestoneRequest, opts ...grpc.CallOption) (*MilestoneDetail, error)
	ListMilestones(ctx context.Context, in *ListMilestonesRequest, opts ...grpc.CallOption) (*MilestoneList, error)
	GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*SettlementDetail, error)
	ListSettlements(ctx context.Context, in *ListSettlementsRequest, opts ...grpc.CallOption) (*SettlementList, error)
	GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*ContractDetail, error)
	ListContracts(ctx context.Context, in *ListContractsRequest, opts ...grpc.CallOption) (*ContractList, error)
	GetCode(ctx context.Context, in *GetCodeRequest, opts ...grpc.CallOption) (*CodeDetail, error)
	ListCodes(ctx context.Context, in *ListCodesRequest, opts ...grpc.CallOption) (*CodeList, error)
	GetGovernanceProposal(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*ProposalDetail, error)
	ListProposals(ctx context.Context, in *ListProposalsRequest, opts ...grpc.CallOption) (*ProposalList, error)
	ListIbcChannels(ctx context.Context, in *ListIbcChannelsRequest, opts ...grpc.CallOption) (*IbcChannelList, error)
	GetIbcChannel(ctx context.Context, in *GetIbcChannelRequest, opts ...grpc.CallOption) (*IbcChannelDetail, error)
	ListIbcAssets(ctx context.Context, in *ListIbcAssetsRequest, opts ...grpc.CallOption) (*IbcAssetList, error)
	GetCw20Token(ctx context.Context, in *GetCw20TokenRequest, opts ...grpc.CallOption) (*Cw20TokenDetail, error)
	GetCw721Collection(ctx context.Context, in *GetCw721CollectionRequest, opts ...grpc.CallOption) (*Cw721CollectionDetail, error)
	GetCw721Token(ctx context.Context, in *GetCw721TokenRequest, opts ...grpc.CallOption) (*Cw721TokenDetail, error)
	StreamLatestBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockSummary], error)
	StreamConsensusRound(ctx context.Context, in *StreamConsensusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsensusRound], error)
	GetBridgeTx(ctx context.Context, in *GetBridgeTxRequest, opts ...grpc.CallOption) (*BridgeTxDetail, error)
	ListBridgeTxs(ctx context.Context, in *ListBridgeTxsRequest, opts ...grpc.CallOption) (*BridgeTxList, error)
	GetBridgeSupplyMetrics(ctx context.Context, in *GetBridgeSupplyMetricsRequest, opts ...grpc.CallOption) (*SupplyMetrics, error)
	ListRelayers(ctx context.Context, in *ListRelayersRequest, opts ...grpc.CallOption) (*RelayerList, error)
	ListBridgeCircuitBreaker(ctx context.Context, in *ListBridgeCircuitBreakerRequest, opts ...grpc.CallOption) (*CircuitBreakerHistory, error)
	ListBridgeNonces(ctx context.Context, in *ListBridgeNoncesRequest, opts ...grpc.CallOption) (*NonceRegistryDetail, error)
	GetTpsHistory(ctx context.Context, in *GetTpsRequest, opts ...grpc.CallOption) (*TpsHistory, error)
	GetBlockTimeHistory(ctx context.Context, in *GetBlockTimeRequest, opts ...grpc.CallOption) (*BlockTimeHistory, error)
	GetValidatorUptimeGrid(ctx context.Context, in *GetUptimeRequest, opts ...grpc.CallOption) (*UptimeHeatmap, error)
	GetBridgeVolumeHistory(ctx context.Context, in *GetBridgeVolumeRequest, opts ...grpc.CallOption) (*VolumeHistory, error)
	ExportTxsCsv(ctx context.Context, in *ExportTxsCsvRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CsvChunk], error)
	SearchGlobal(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*WebhookDetail, error)
	ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*WebhookList, error)
	DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*DeleteWebhookResponse, error)
	GetSystemStatus(ctx context.Context, in *GetSystemStatusRequest, opts ...grpc.CallOption) (*SystemStatus, error)
}

type explorerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExplorerServiceClient(cc grpc.ClientConnInterface) ExplorerServiceClient {
	return &explorerServiceClient{cc}
}

func (c *explorerServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*BlockDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListBlocks(ctx context.Context, in *ListBlocksRequest, opts ...grpc.CallOption) (*BlockList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockList)
	err := c.cc.Invoke(ctx, ExplorerService_ListBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetTx(ctx context.Context, in *GetTxRequest, opts ...grpc.CallOption) (*TxDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListTxs(ctx context.Context, in *ListTxsRequest, opts ...grpc.CallOption) (*TxList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxList)
	err := c.cc.Invoke(ctx, ExplorerService_ListTxs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListTxsByAddress(ctx context.Context, in *ListTxsByAddressRequest, opts ...grpc.CallOption) (*TxList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxList)
	err := c.cc.Invoke(ctx, ExplorerService_ListTxsByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*AccountDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetValidator(ctx context.Context, in *GetValidatorRequest, opts ...grpc.CallOption) (*ValidatorDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatorDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetValidator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListValidators(ctx context.Context, in *ListValidatorsRequest, opts ...grpc.CallOption) (*ValidatorSlotGrid, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatorSlotGrid)
	err := c.cc.Invoke(ctx, ExplorerService_ListValidators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetStakingStats(ctx context.Context, in *GetStakingStatsRequest, opts ...grpc.CallOption) (*StakingStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StakingStats)
	err := c.cc.Invoke(ctx, ExplorerService_GetStakingStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetOracleFeed(ctx context.Context, in *GetOracleFeedRequest, opts ...grpc.CallOption) (*FeedDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetOracleFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetOracleRound(ctx context.Context, in *GetOracleRoundRequest, opts ...grpc.CallOption) (*RoundDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoundDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetOracleRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListOracleRounds(ctx context.Context, in *ListOracleRoundsRequest, opts ...grpc.CallOption) (*RoundList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoundList)
	err := c.cc.Invoke(ctx, ExplorerService_ListOracleRounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetMilestone(ctx context.Context, in *GetMilestoneRequest, opts ...grpc.CallOption) (*MilestoneDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MilestoneDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetMilestone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListMilestones(ctx context.Context, in *ListMilestonesRequest, opts ...grpc.CallOption) (*MilestoneList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MilestoneList)
	err := c.cc.Invoke(ctx, ExplorerService_ListMilestones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*SettlementDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListSettlements(ctx context.Context, in *ListSettlementsRequest, opts ...grpc.CallOption) (*SettlementList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementList)
	err := c.cc.Invoke(ctx, ExplorerService_ListSettlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*ContractDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListContracts(ctx context.Context, in *ListContractsRequest, opts ...grpc.CallOption) (*ContractList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractList)
	err := c.cc.Invoke(ctx, ExplorerService_ListContracts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetCode(ctx context.Context, in *GetCodeRequest, opts ...grpc.CallOption) (*CodeDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListCodes(ctx context.Context, in *ListCodesRequest, opts ...grpc.CallOption) (*CodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeList)
	err := c.cc.Invoke(ctx, ExplorerService_ListCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetGovernanceProposal(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*ProposalDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetGovernanceProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListProposals(ctx context.Context, in *ListProposalsRequest, opts ...grpc.CallOption) (*ProposalList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalList)
	err := c.cc.Invoke(ctx, ExplorerService_ListProposals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListIbcChannels(ctx context.Context, in *ListIbcChannelsRequest, opts ...grpc.CallOption) (*IbcChannelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IbcChannelList)
	err := c.cc.Invoke(ctx, ExplorerService_ListIbcChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetIbcChannel(ctx context.Context, in *GetIbcChannelRequest, opts ...grpc.CallOption) (*IbcChannelDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IbcChannelDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetIbcChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListIbcAssets(ctx context.Context, in *ListIbcAssetsRequest, opts ...grpc.CallOption) (*IbcAssetList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IbcAssetList)
	err := c.cc.Invoke(ctx, ExplorerService_ListIbcAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetCw20Token(ctx context.Context, in *GetCw20TokenRequest, opts ...grpc.CallOption) (*Cw20TokenDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cw20TokenDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetCw20Token_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetCw721Collection(ctx context.Context, in *GetCw721CollectionRequest, opts ...grpc.CallOption) (*Cw721CollectionDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cw721CollectionDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetCw721Collection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetCw721Token(ctx context.Context, in *GetCw721TokenRequest, opts ...grpc.CallOption) (*Cw721TokenDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cw721TokenDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetCw721Token_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) StreamLatestBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExplorerService_ServiceDesc.Streams[0], ExplorerService_StreamLatestBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBlocksRequest, BlockSummary]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExplorerService_StreamLatestBlocksClient = grpc.ServerStreamingClient[BlockSummary]

func (c *explorerServiceClient) StreamConsensusRound(ctx context.Context, in *StreamConsensusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsensusRound], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExplorerService_ServiceDesc.Streams[1], ExplorerService_StreamConsensusRound_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConsensusRequest, ConsensusRound]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExplorerService_StreamConsensusRoundClient = grpc.ServerStreamingClient[ConsensusRound]

func (c *explorerServiceClient) GetBridgeTx(ctx context.Context, in *GetBridgeTxRequest, opts ...grpc.CallOption) (*BridgeTxDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BridgeTxDetail)
	err := c.cc.Invoke(ctx, ExplorerService_GetBridgeTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListBridgeTxs(ctx context.Context, in *ListBridgeTxsRequest, opts ...grpc.CallOption) (*BridgeTxList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BridgeTxList)
	err := c.cc.Invoke(ctx, ExplorerService_ListBridgeTxs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetBridgeSupplyMetrics(ctx context.Context, in *GetBridgeSupplyMetricsRequest, opts ...grpc.CallOption) (*SupplyMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupplyMetrics)
	err := c.cc.Invoke(ctx, ExplorerService_GetBridgeSupplyMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListRelayers(ctx context.Context, in *ListRelayersRequest, opts ...grpc.CallOption) (*RelayerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayerList)
	err := c.cc.Invoke(ctx, ExplorerService_ListRelayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListBridgeCircuitBreaker(ctx context.Context, in *ListBridgeCircuitBreakerRequest, opts ...grpc.CallOption) (*CircuitBreakerHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CircuitBreakerHistory)
	err := c.cc.Invoke(ctx, ExplorerService_ListBridgeCircuitBreaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListBridgeNonces(ctx context.Context, in *ListBridgeNoncesRequest, opts ...grpc.CallOption) (*NonceRegistryDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NonceRegistryDetail)
	err := c.cc.Invoke(ctx, ExplorerService_ListBridgeNonces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetTpsHistory(ctx context.Context, in *GetTpsRequest, opts ...grpc.CallOption) (*TpsHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TpsHistory)
	err := c.cc.Invoke(ctx, ExplorerService_GetTpsHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetBlockTimeHistory(ctx context.Context, in *GetBlockTimeRequest, opts ...grpc.CallOption) (*BlockTimeHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockTimeHistory)
	err := c.cc.Invoke(ctx, ExplorerService_GetBlockTimeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetValidatorUptimeGrid(ctx context.Context, in *GetUptimeRequest, opts ...grpc.CallOption) (*UptimeHeatmap, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UptimeHeatmap)
	err := c.cc.Invoke(ctx, ExplorerService_GetValidatorUptimeGrid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetBridgeVolumeHistory(ctx context.Context, in *GetBridgeVolumeRequest, opts ...grpc.CallOption) (*VolumeHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeHistory)
	err := c.cc.Invoke(ctx, ExplorerService_GetBridgeVolumeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ExportTxsCsv(ctx context.Context, in *ExportTxsCsvRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CsvChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExplorerService_ServiceDesc.Streams[2], ExplorerService_ExportTxsCsv_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportTxsCsvRequest, CsvChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExplorerService_ExportTxsCsvClient = grpc.ServerStreamingClient[CsvChunk]

func (c *explorerServiceClient) SearchGlobal(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ExplorerService_SearchGlobal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*WebhookDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookDetail)
	err := c.cc.Invoke(ctx, ExplorerService_RegisterWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*WebhookList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookList)
	err := c.cc.Invoke(ctx, ExplorerService_ListWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*DeleteWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWebhookResponse)
	err := c.cc.Invoke(ctx, ExplorerService_DeleteWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *explorerServiceClient) GetSystemStatus(ctx context.Context, in *GetSystemStatusRequest, opts ...grpc.CallOption) (*SystemStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatus)
	err := c.cc.Invoke(ctx, ExplorerService_GetSystemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExplorerServiceServer is the server API for ExplorerService service.
// All implementations must embed UnimplementedExplorerServiceServer
// for forward compatibility.
type ExplorerServiceServer interface {
	GetBlock(context.Context, *GetBlockRequest) (*BlockDetail, error)
	ListBlocks(context.Context, *ListBlocksRequest) (*BlockList, error)
	GetTx(context.Context, *GetTxRequest) (*TxDetail, error)
	ListTxs(context.Context, *ListTxsRequest) (*TxList, error)
	ListTxsByAddress(context.Context, *ListTxsByAddressRequest) (*TxList, error)
	GetAddress(context.Context, *GetAddressRequest) (*AccountDetail, error)
	GetValidator(context.Context, *GetValidatorRequest) (*ValidatorDetail, error)
	ListValidators(context.Context, *ListValidatorsRequest) (*ValidatorSlotGrid, error)
	GetStakingStats(context.Context, *GetStakingStatsRequest) (*StakingStats, error)
	GetOracleFeed(context.Context, *GetOracleFeedRequest) (*FeedDetail, error)
	GetOracleRound(context.Context, *GetOracleRoundRequest) (*RoundDetail, error)
	ListOracleRounds(context.Context, *ListOracleRoundsRequest) (*RoundList, error)
	GetMilestone(context.Context, *GetMilestoneRequest) (*MilestoneDetail, error)
	ListMilestones(context.Context, *ListMilestonesRequest) (*MilestoneList, error)
	GetSettlement(context.Context, *GetSettlementRequest) (*SettlementDetail, error)
	ListSettlements(context.Context, *ListSettlementsRequest) (*SettlementList, error)
	GetContract(context.Context, *GetContractRequest) (*ContractDetail, error)
	ListContracts(context.Context, *ListContractsRequest) (*ContractList, error)
	GetCode(context.Context, *GetCodeRequest) (*CodeDetail, error)
	ListCodes(context.Context, *ListCodesRequest) (*CodeList, error)
	GetGovernanceProposal(context.Context, *GetProposalRequest) (*ProposalDetail, error)
	ListProposals(context.Context, *ListProposalsRequest) (*ProposalList, error)
	ListIbcChannels(context.Context, *ListIbcChannelsRequest) (*IbcChannelList, error)
	GetIbcChannel(context.Context, *GetIbcChannelRequest) (*IbcChannelDetail, error)
	ListIbcAssets(context.Context, *ListIbcAssetsRequest) (*IbcAssetList, error)
	GetCw20Token(context.Context, *GetCw20TokenRequest) (*Cw20TokenDetail, error)
	GetCw721Collection(context.Context, *GetCw721CollectionRequest) (*Cw721CollectionDetail, error)
	GetCw721Token(context.Context, *GetCw721TokenRequest) (*Cw721TokenDetail, error)
	StreamLatestBlocks(*StreamBlocksRequest, grpc.ServerStreamingServer[BlockSummary]) error
	StreamConsensusRound(*StreamConsensusRequest, grpc.ServerStreamingServer[ConsensusRound]) error
	GetBridgeTx(context.Context, *GetBridgeTxRequest) (*BridgeTxDetail, error)
	ListBridgeTxs(context.Context, *ListBridgeTxsRequest) (*BridgeTxList, error)
	GetBridgeSupplyMetrics(context.Context, *GetBridgeSupplyMetricsRequest) (*SupplyMetrics, error)
	ListRelayers(context.Context, *ListRelayersRequest) (*RelayerList, error)
	ListBridgeCircuitBreaker(context.Context, *ListBridgeCircuitBreakerRequest) (*CircuitBreakerHistory, error)
	ListBridgeNonces(context.Context, *ListBridgeNoncesRequest) (*NonceRegistryDetail, error)
	GetTpsHistory(context.Context, *GetTpsRequest) (*TpsHistory, error)
	GetBlockTimeHistory(context.Context, *GetBlockTimeRequest) (*BlockTimeHistory, error)
	GetValidatorUptimeGrid(context.Context, *GetUptimeRequest) (*UptimeHeatmap, error)
	GetBridgeVolumeHistory(context.Context, *GetBridgeVolumeRequest) (*VolumeHistory, error)
	ExportTxsCsv(*ExportTxsCsvRequest, grpc.ServerStreamingServer[CsvChunk]) error
	SearchGlobal(context.Context, *SearchRequest) (*SearchResponse, error)
	RegisterWebhook(context.Context, *RegisterWebhookRequest) (*WebhookDetail, error)
	ListWebhooks(context.Context, *ListWebhooksRequest) (*WebhookList, error)
	DeleteWebhook(context.Context, *DeleteWebhookRequest) (*DeleteWebhookResponse, error)
	GetSystemStatus(context.Context, *GetSystemStatusRequest) (*SystemStatus, error)
	mustEmbedUnimplementedExplorerServiceServer()
}

// UnimplementedExplorerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExplorerServiceServer struct{}

func (UnimplementedExplorerServiceServer) GetBlock(context.Context, *GetBlockRequest) (*BlockDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedExplorerServiceServer) ListBlocks(context.Context, *ListBlocksRequest) (*BlockList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlocks not implemented")
}
func (UnimplementedExplorerServiceServer) GetTx(context.Context, *GetTxRequest) (*TxDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTx not implemented")
}
func (UnimplementedExplorerServiceServer) ListTxs(context.Context, *ListTxsRequest) (*TxList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTxs not implemented")
}
func (UnimplementedExplorerServiceServer) ListTxsByAddress(context.Context, *ListTxsByAddressRequest) (*TxList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTxsByAddress not implemented")
}
func (UnimplementedExplorerServiceServer) GetAddress(context.Context, *GetAddressRequest) (*AccountDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAddress not implemented")
}
func (UnimplementedExplorerServiceServer) GetValidator(context.Context, *GetValidatorRequest) (*ValidatorDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValidator not implemented")
}
func (UnimplementedExplorerServiceServer) ListValidators(context.Context, *ListValidatorsRequest) (*ValidatorSlotGrid, error) {
	return nil, status.Error(codes.Unimplemented, "method ListValidators not implemented")
}
func (UnimplementedExplorerServiceServer) GetStakingStats(context.Context, *GetStakingStatsRequest) (*StakingStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStakingStats not implemented")
}
func (UnimplementedExplorerServiceServer) GetOracleFeed(context.Context, *GetOracleFeedRequest) (*FeedDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOracleFeed not implemented")
}
func (UnimplementedExplorerServiceServer) GetOracleRound(context.Context, *GetOracleRoundRequest) (*RoundDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOracleRound not implemented")
}
func (UnimplementedExplorerServiceServer) ListOracleRounds(context.Context, *ListOracleRoundsRequest) (*RoundList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOracleRounds not implemented")
}
func (UnimplementedExplorerServiceServer) GetMilestone(context.Context, *GetMilestoneRequest) (*MilestoneDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMilestone not implemented")
}
func (UnimplementedExplorerServiceServer) ListMilestones(context.Context, *ListMilestonesRequest) (*MilestoneList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMilestones not implemented")
}
func (UnimplementedExplorerServiceServer) GetSettlement(context.Context, *GetSettlementRequest) (*SettlementDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettlement not implemented")
}
func (UnimplementedExplorerServiceServer) ListSettlements(context.Context, *ListSettlementsRequest) (*SettlementList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSettlements not implemented")
}
func (UnimplementedExplorerServiceServer) GetContract(context.Context, *GetContractRequest) (*ContractDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContract not implemented")
}
func (UnimplementedExplorerServiceServer) ListContracts(context.Context, *ListContractsRequest) (*ContractList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContracts not implemented")
}
func (UnimplementedExplorerServiceServer) GetCode(context.Context, *GetCodeRequest) (*CodeDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCode not implemented")
}
func (UnimplementedExplorerServiceServer) ListCodes(context.Context, *ListCodesRequest) (*CodeList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCodes not implemented")
}
func (UnimplementedExplorerServiceServer) GetGovernanceProposal(context.Context, *GetProposalRequest) (*ProposalDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGovernanceProposal not implemented")
}
func (UnimplementedExplorerServiceServer) ListProposals(context.Context, *ListProposalsRequest) (*ProposalList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProposals not implemented")
}
func (UnimplementedExplorerServiceServer) ListIbcChannels(context.Context, *ListIbcChannelsRequest) (*IbcChannelList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIbcChannels not implemented")
}
func (UnimplementedExplorerServiceServer) GetIbcChannel(context.Context, *GetIbcChannelRequest) (*IbcChannelDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIbcChannel not implemented")
}
func (UnimplementedExplorerServiceServer) ListIbcAssets(context.Context, *ListIbcAssetsRequest) (*IbcAssetList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIbcAssets not implemented")
}
func (UnimplementedExplorerServiceServer) GetCw20Token(context.Context, *GetCw20TokenRequest) (*Cw20TokenDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCw20Token not implemented")
}
func (UnimplementedExplorerServiceServer) GetCw721Collection(context.Context, *GetCw721CollectionRequest) (*Cw721CollectionDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCw721Collection not implemented")
}
func (UnimplementedExplorerServiceServer) GetCw721Token(context.Context, *GetCw721TokenRequest) (*Cw721TokenDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCw721Token not implemented")
}
func (UnimplementedExplorerServiceServer) StreamLatestBlocks(*StreamBlocksRequest, grpc.ServerStreamingServer[BlockSummary]) error {
	return status.Error(codes.Unimplemented, "method StreamLatestBlocks not implemented")
}
func (UnimplementedExplorerServiceServer) StreamConsensusRound(*StreamConsensusRequest, grpc.ServerStreamingServer[ConsensusRound]) error {
	return status.Error(codes.Unimplemented, "method StreamConsensusRound not implemented")
}
func (UnimplementedExplorerServiceServer) GetBridgeTx(context.Context, *GetBridgeTxRequest) (*BridgeTxDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBridgeTx not implemented")
}
func (UnimplementedExplorerServiceServer) ListBridgeTxs(context.Context, *ListBridgeTxsRequest) (*BridgeTxList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBridgeTxs not implemented")
}
func (UnimplementedExplorerServiceServer) GetBridgeSupplyMetrics(context.Context, *GetBridgeSupplyMetricsRequest) (*SupplyMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBridgeSupplyMetrics not implemented")
}
func (UnimplementedExplorerServiceServer) ListRelayers(context.Context, *ListRelayersRequest) (*RelayerList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRelayers not implemented")
}
func (UnimplementedExplorerServiceServer) ListBridgeCircuitBreaker(context.Context, *ListBridgeCircuitBreakerRequest) (*CircuitBreakerHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBridgeCircuitBreaker not implemented")
}
func (UnimplementedExplorerServiceServer) ListBridgeNonces(context.Context, *ListBridgeNoncesRequest) (*NonceRegistryDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBridgeNonces not implemented")
}
func (UnimplementedExplorerServiceServer) GetTpsHistory(context.Context, *GetTpsRequest) (*TpsHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTpsHistory not implemented")
}
func (UnimplementedExplorerServiceServer) GetBlockTimeHistory(context.Context, *GetBlockTimeRequest) (*BlockTimeHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockTimeHistory not implemented")
}
func (UnimplementedExplorerServiceServer) GetValidatorUptimeGrid(context.Context, *GetUptimeRequest) (*UptimeHeatmap, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValidatorUptimeGrid not implemented")
}
func (UnimplementedExplorerServiceServer) GetBridgeVolumeHistory(context.Context, *GetBridgeVolumeRequest) (*VolumeHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBridgeVolumeHistory not implemented")
}
func (UnimplementedExplorerServiceServer) ExportTxsCsv(*ExportTxsCsvRequest, grpc.ServerStreamingServer[CsvChunk]) error {
	return status.Error(codes.Unimplemented, "method ExportTxsCsv not implemented")
}
func (UnimplementedExplorerServiceServer) SearchGlobal(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGlobal not implemented")
}
func (UnimplementedExplorerServiceServer) RegisterWebhook(context.Context, *RegisterWebhookRequest) (*WebhookDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWebhook not implemented")
}
func (UnimplementedExplorerServiceServer) ListWebhooks(context.Context, *ListWebhooksRequest) (*WebhookList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhooks not implemented")
}
func (UnimplementedExplorerServiceServer) DeleteWebhook(context.Context, *DeleteWebhookRequest) (*DeleteWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWebhook not implemented")
}
func (UnimplementedExplorerServiceServer) GetSystemStatus(context.Context, *GetSystemStatusRequest) (*SystemStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStatus not implemented")
}
func (UnimplementedExplorerServiceServer) mustEmbedUnimplementedExplorerServiceServer() {}
func (UnimplementedExplorerServiceServer) testEmbeddedByValue()                         {}

// UnsafeExplorerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExplorerServiceServer will
// result in compilation errors.
type UnsafeExplorerServiceServer interface {
	mustEmbedUnimplementedExplorerServiceServer()
}

func RegisterExplorerServiceServer(s grpc.ServiceRegistrar, srv ExplorerServiceServer) {
	// If the following call panics, it indicates UnimplementedExplorerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExplorerService_ServiceDesc, srv)
}

func _ExplorerService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListBlocks(ctx, req.(*ListBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetTx(ctx, req.(*GetTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListTxs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListTxs(ctx, req.(*ListTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListTxsByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTxsByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListTxsByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListTxsByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListTxsByAddress(ctx, req.(*ListTxsByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetAddress(ctx, req.(*GetAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetValidator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetValidator(ctx, req.(*GetValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListValidators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListValidators(ctx, req.(*ListValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetStakingStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStakingStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetStakingStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetStakingStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetStakingStats(ctx, req.(*GetStakingStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetOracleFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOracleFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetOracleFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetOracleFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetOracleFeed(ctx, req.(*GetOracleFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetOracleRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOracleRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetOracleRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetOracleRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetOracleRound(ctx, req.(*GetOracleRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListOracleRounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOracleRoundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListOracleRounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListOracleRounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListOracleRounds(ctx, req.(*ListOracleRoundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetMilestone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetMilestone(ctx, req.(*GetMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListMilestones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMilestonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListMilestones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListMilestones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListMilestones(ctx, req.(*ListMilestonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetSettlement(ctx, req.(*GetSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListSettlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSettlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListSettlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListSettlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListSettlements(ctx, req.(*ListSettlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetContract(ctx, req.(*GetContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListContracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContractsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListContracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListContracts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListContracts(ctx, req.(*ListContractsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetCode(ctx, req.(*GetCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListCodes(ctx, req.(*ListCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetGovernanceProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetGovernanceProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetGovernanceProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetGovernanceProposal(ctx, req.(*GetProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListProposals(ctx, req.(*ListProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListIbcChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIbcChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListIbcChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListIbcChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListIbcChannels(ctx, req.(*ListIbcChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetIbcChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIbcChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetIbcChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetIbcChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetIbcChannel(ctx, req.(*GetIbcChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListIbcAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIbcAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListIbcAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListIbcAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListIbcAssets(ctx, req.(*ListIbcAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetCw20Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCw20TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetCw20Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetCw20Token_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetCw20Token(ctx, req.(*GetCw20TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetCw721Collection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCw721CollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetCw721Collection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetCw721Collection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetCw721Collection(ctx, req.(*GetCw721CollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetCw721Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCw721TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetCw721Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetCw721Token_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetCw721Token(ctx, req.(*GetCw721TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_StreamLatestBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExplorerServiceServer).StreamLatestBlocks(m, &grpc.GenericServerStream[StreamBlocksRequest, BlockSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExplorerService_StreamLatestBlocksServer = grpc.ServerStreamingServer[BlockSummary]

func _ExplorerService_StreamConsensusRound_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConsensusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExplorerServiceServer).StreamConsensusRound(m, &grpc.GenericServerStream[StreamConsensusRequest, ConsensusRound]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExplorerService_StreamConsensusRoundServer = grpc.ServerStreamingServer[ConsensusRound]

func _ExplorerService_GetBridgeTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBridgeTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetBridgeTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetBridgeTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetBridgeTx(ctx, req.(*GetBridgeTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListBridgeTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBridgeTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListBridgeTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListBridgeTxs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListBridgeTxs(ctx, req.(*ListBridgeTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetBridgeSupplyMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBridgeSupplyMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetBridgeSupplyMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetBridgeSupplyMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetBridgeSupplyMetrics(ctx, req.(*GetBridgeSupplyMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListRelayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRelayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListRelayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListRelayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListRelayers(ctx, req.(*ListRelayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListBridgeCircuitBreaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBridgeCircuitBreakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListBridgeCircuitBreaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListBridgeCircuitBreaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListBridgeCircuitBreaker(ctx, req.(*ListBridgeCircuitBreakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListBridgeNonces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBridgeNoncesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListBridgeNonces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListBridgeNonces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListBridgeNonces(ctx, req.(*ListBridgeNoncesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetTpsHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetTpsHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetTpsHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetTpsHistory(ctx, req.(*GetTpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetBlockTimeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetBlockTimeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetBlockTimeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetBlockTimeHistory(ctx, req.(*GetBlockTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetValidatorUptimeGrid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUptimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetValidatorUptimeGrid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetValidatorUptimeGrid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetValidatorUptimeGrid(ctx, req.(*GetUptimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetBridgeVolumeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBridgeVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetBridgeVolumeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetBridgeVolumeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetBridgeVolumeHistory(ctx, req.(*GetBridgeVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ExportTxsCsv_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportTxsCsvRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExplorerServiceServer).ExportTxsCsv(m, &grpc.GenericServerStream[ExportTxsCsvRequest, CsvChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExplorerService_ExportTxsCsvServer = grpc.ServerStreamingServer[CsvChunk]

func _ExplorerService_SearchGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).SearchGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_SearchGlobal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).SearchGlobal(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_RegisterWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).RegisterWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_RegisterWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).RegisterWebhook(ctx, req.(*RegisterWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_ListWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).ListWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_ListWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).ListWebhooks(ctx, req.(*ListWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_DeleteWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).DeleteWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_DeleteWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).DeleteWebhook(ctx, req.(*DeleteWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExplorerService_GetSystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServiceServer).GetSystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExplorerService_GetSystemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServiceServer).GetSystemStatus(ctx, req.(*GetSystemStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExplorerService_ServiceDesc is the grpc.ServiceDesc for ExplorerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExplorerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "explorer.v1.ExplorerService",
	HandlerType: (*ExplorerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _ExplorerService_GetBlock_Handler,
		},
		{
			MethodName: "ListBlocks",
			Handler:    _ExplorerService_ListBlocks_Handler,
		},
		{
			MethodName: "GetTx",
			Handler:    _ExplorerService_GetTx_Handler,
		},
		{
			MethodName: "ListTxs",
			Handler:    _ExplorerService_ListTxs_Handler,
		},
		{
			MethodName: "ListTxsByAddress",
			Handler:    _ExplorerService_ListTxsByAddress_Handler,
		},
		{
			MethodName: "GetAddress",
			Handler:    _ExplorerService_GetAddress_Handler,
		},
		{
			MethodName: "GetValidator",
			Handler:    _ExplorerService_GetValidator_Handler,
		},
		{
			MethodName: "ListValidators",
			Handler:    _ExplorerService_ListValidators_Handler,
		},
		{
			MethodName: "GetStakingStats",
			Handler:    _ExplorerService_GetStakingStats_Handler,
		},
		{
			MethodName: "GetOracleFeed",
			Handler:    _ExplorerService_GetOracleFeed_Handler,
		},
		{
			MethodName: "GetOracleRound",
			Handler:    _ExplorerService_GetOracleRound_Handler,
		},
		{
			MethodName: "ListOracleRounds",
			Handler:    _ExplorerService_ListOracleRounds_Handler,
		},
		{
			MethodName: "GetMilestone",
			Handler:    _ExplorerService_GetMilestone_Handler,
		},
		{
			MethodName: "ListMilestones",
			Handler:    _ExplorerService_ListMilestones_Handler,
		},
		{
			MethodName: "GetSettlement",
			Handler:    _ExplorerService_GetSettlement_Handler,
		},
		{
			MethodName: "ListSettlements",
			Handler:    _ExplorerService_ListSettlements_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _ExplorerService_GetContract_Handler,
		},
		{
			MethodName: "ListContracts",
			Handler:    _ExplorerService_ListContracts_Handler,
		},
		{
			MethodName: "GetCode",
			Handler:    _ExplorerService_GetCode_Handler,
		},
		{
			MethodName: "ListCodes",
			Handler:    _ExplorerService_ListCodes_Handler,
		},
		{
			MethodName: "GetGovernanceProposal",
			Handler:    _ExplorerService_GetGovernanceProposal_Handler,
		},
		{
			MethodName: "ListProposals",
			Handler:    _ExplorerService_ListProposals_Handler,
		},
		{
			MethodName: "ListIbcChannels",
			Handler:    _ExplorerService_ListIbcChannels_Handler,
		},
		{
			MethodName: "GetIbcChannel",
			Handler:    _ExplorerService_GetIbcChannel_Handler,
		},
		{
			MethodName: "ListIbcAssets",
			Handler:    _ExplorerService_ListIbcAssets_Handler,
		},
		{
			MethodName: "GetCw20Token",
			Handler:    _ExplorerService_GetCw20Token_Handler,
		},
		{
			MethodName: "GetCw721Collection",
			Handler:    _ExplorerService_GetCw721Collection_Handler,
		},
		{
			MethodName: "GetCw721Token",
			Handler:    _ExplorerService_GetCw721Token_Handler,
		},
		{
			MethodName: "GetBridgeTx",
			Handler:    _ExplorerService_GetBridgeTx_Handler,
		},
		{
			MethodName: "ListBridgeTxs",
			Handler:    _ExplorerService_ListBridgeTxs_Handler,
		},
		{
			MethodName: "GetBridgeSupplyMetrics",
			Handler:    _ExplorerService_GetBridgeSupplyMetrics_Handler,
		},
		{
			MethodName: "ListRelayers",
			Handler:    _ExplorerService_ListRelayers_Handler,
		},
		{
			MethodName: "ListBridgeCircuitBreaker",
			Handler:    _ExplorerService_ListBridgeCircuitBreaker_Handler,
		},
		{
			MethodName: "ListBridgeNonces",
			Handler:    _ExplorerService_ListBridgeNonces_Handler,
		},
		{
			MethodName: "GetTpsHistory",
			Handler:    _ExplorerService_GetTpsHistory_Handler,
		},
		{
			MethodName: "GetBlockTimeHistory",
			Handler:    _ExplorerService_GetBlockTimeHistory_Handler,
		},
		{
			MethodName: "GetValidatorUptimeGrid",
			Handler:    _ExplorerService_GetValidatorUptimeGrid_Handler,
		},
		{
			MethodName: "GetBridgeVolumeHistory",
			Handler:    _ExplorerService_GetBridgeVolumeHistory_Handler,
		},
		{
			MethodName: "SearchGlobal",
			Handler:    _ExplorerService_SearchGlobal_Handler,
		},
		{
			MethodName: "RegisterWebhook",
			Handler:    _ExplorerService_RegisterWebhook_Handler,
		},
		{
			MethodName: "ListWebhooks",
			Handler:    _ExplorerService_ListWebhooks_Handler,
		},
		{
			MethodName: "DeleteWebhook",
			Handler:    _ExplorerService_DeleteWebhook_Handler,
		},
		{
			MethodName: "GetSystemStatus",
			Handler:    _ExplorerService_GetSystemStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLatestBlocks",
			Handler:       _ExplorerService_StreamLatestBlocks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamConsensusRound",
			Handler:       _ExplorerService_StreamConsensusRound_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExportTxsCsv",
			Handler:       _ExplorerService_ExportTxsCsv_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "explorer/v1/explorer.proto",
}
