// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "explorer/v1/explorer.proto" (package "explorer.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ExplorerService } from "./explorer";
import type { SystemStatus } from "./explorer";
import type { GetSystemStatusRequest } from "./explorer";
import type { DeleteWebhookResponse } from "./explorer";
import type { DeleteWebhookRequest } from "./explorer";
import type { WebhookList } from "./explorer";
import type { ListWebhooksRequest } from "./explorer";
import type { WebhookDetail } from "./explorer";
import type { RegisterWebhookRequest } from "./explorer";
import type { SearchResponse } from "./explorer";
import type { SearchRequest } from "./explorer";
import type { CsvChunk } from "./explorer";
import type { ExportTxsCsvRequest } from "./explorer";
import type { VolumeHistory } from "./explorer";
import type { GetBridgeVolumeRequest } from "./explorer";
import type { UptimeHeatmap } from "./explorer";
import type { GetUptimeRequest } from "./explorer";
import type { BlockTimeHistory } from "./explorer";
import type { GetBlockTimeRequest } from "./explorer";
import type { TpsHistory } from "./explorer";
import type { GetTpsRequest } from "./explorer";
import type { NonceRegistryDetail } from "./explorer";
import type { ListBridgeNoncesRequest } from "./explorer";
import type { CircuitBreakerHistory } from "./explorer";
import type { ListBridgeCircuitBreakerRequest } from "./explorer";
import type { RelayerList } from "./explorer";
import type { ListRelayersRequest } from "./explorer";
import type { SupplyMetrics } from "./explorer";
import type { GetBridgeSupplyMetricsRequest } from "./explorer";
import type { BridgeTxList } from "./explorer";
import type { ListBridgeTxsRequest } from "./explorer";
import type { BridgeTxDetail } from "./explorer";
import type { GetBridgeTxRequest } from "./explorer";
import type { ConsensusRound } from "./explorer";
import type { StreamConsensusRequest } from "./explorer";
import type { BlockSummary } from "./explorer";
import type { StreamBlocksRequest } from "./explorer";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { Cw721TokenDetail } from "./explorer";
import type { GetCw721TokenRequest } from "./explorer";
import type { Cw721CollectionDetail } from "./explorer";
import type { GetCw721CollectionRequest } from "./explorer";
import type { Cw20TokenDetail } from "./explorer";
import type { GetCw20TokenRequest } from "./explorer";
import type { IbcAssetList } from "./explorer";
import type { ListIbcAssetsRequest } from "./explorer";
import type { IbcChannelDetail } from "./explorer";
import type { GetIbcChannelRequest } from "./explorer";
import type { IbcChannelList } from "./explorer";
import type { ListIbcChannelsRequest } from "./explorer";
import type { ProposalList } from "./explorer";
import type { ListProposalsRequest } from "./explorer";
import type { ProposalDetail } from "./explorer";
import type { GetProposalRequest } from "./explorer";
import type { CodeList } from "./explorer";
import type { ListCodesRequest } from "./explorer";
import type { CodeDetail } from "./explorer";
import type { GetCodeRequest } from "./explorer";
import type { ContractList } from "./explorer";
import type { ListContractsRequest } from "./explorer";
import type { ContractDetail } from "./explorer";
import type { GetContractRequest } from "./explorer";
import type { SettlementList } from "./explorer";
import type { ListSettlementsRequest } from "./explorer";
import type { SettlementDetail } from "./explorer";
import type { GetSettlementRequest } from "./explorer";
import type { MilestoneList } from "./explorer";
import type { ListMilestonesRequest } from "./explorer";
import type { MilestoneDetail } from "./explorer";
import type { GetMilestoneRequest } from "./explorer";
import type { RoundList } from "./explorer";
import type { ListOracleRoundsRequest } from "./explorer";
import type { RoundDetail } from "./explorer";
import type { GetOracleRoundRequest } from "./explorer";
import type { FeedDetail } from "./explorer";
import type { GetOracleFeedRequest } from "./explorer";
import type { StakingStats } from "./explorer";
import type { GetStakingStatsRequest } from "./explorer";
import type { ValidatorSlotGrid } from "./explorer";
import type { ListValidatorsRequest } from "./explorer";
import type { ValidatorDetail } from "./explorer";
import type { GetValidatorRequest } from "./explorer";
import type { AccountDetail } from "./explorer";
import type { GetAddressRequest } from "./explorer";
import type { ListTxsByAddressRequest } from "./explorer";
import type { TxList } from "./explorer";
import type { ListTxsRequest } from "./explorer";
import type { TxDetail } from "./explorer";
import type { GetTxRequest } from "./explorer";
import type { BlockList } from "./explorer";
import type { ListBlocksRequest } from "./explorer";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { BlockDetail } from "./explorer";
import type { GetBlockRequest } from "./explorer";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service explorer.v1.ExplorerService
 */
export interface IExplorerServiceClient {
    /**
     * @generated from protobuf rpc: GetBlock
     */
    getBlock(input: GetBlockRequest, options?: RpcOptions): UnaryCall<GetBlockRequest, BlockDetail>;
    /**
     * @generated from protobuf rpc: ListBlocks
     */
    listBlocks(input: ListBlocksRequest, options?: RpcOptions): UnaryCall<ListBlocksRequest, BlockList>;
    /**
     * @generated from protobuf rpc: GetTx
     */
    getTx(input: GetTxRequest, options?: RpcOptions): UnaryCall<GetTxRequest, TxDetail>;
    /**
     * @generated from protobuf rpc: ListTxs
     */
    listTxs(input: ListTxsRequest, options?: RpcOptions): UnaryCall<ListTxsRequest, TxList>;
    /**
     * @generated from protobuf rpc: ListTxsByAddress
     */
    listTxsByAddress(input: ListTxsByAddressRequest, options?: RpcOptions): UnaryCall<ListTxsByAddressRequest, TxList>;
    /**
     * @generated from protobuf rpc: GetAddress
     */
    getAddress(input: GetAddressRequest, options?: RpcOptions): UnaryCall<GetAddressRequest, AccountDetail>;
    /**
     * @generated from protobuf rpc: GetValidator
     */
    getValidator(input: GetValidatorRequest, options?: RpcOptions): UnaryCall<GetValidatorRequest, ValidatorDetail>;
    /**
     * @generated from protobuf rpc: ListValidators
     */
    listValidators(input: ListValidatorsRequest, options?: RpcOptions): UnaryCall<ListValidatorsRequest, ValidatorSlotGrid>;
    /**
     * @generated from protobuf rpc: GetStakingStats
     */
    getStakingStats(input: GetStakingStatsRequest, options?: RpcOptions): UnaryCall<GetStakingStatsRequest, StakingStats>;
    /**
     * @generated from protobuf rpc: GetOracleFeed
     */
    getOracleFeed(input: GetOracleFeedRequest, options?: RpcOptions): UnaryCall<GetOracleFeedRequest, FeedDetail>;
    /**
     * @generated from protobuf rpc: GetOracleRound
     */
    getOracleRound(input: GetOracleRoundRequest, options?: RpcOptions): UnaryCall<GetOracleRoundRequest, RoundDetail>;
    /**
     * @generated from protobuf rpc: ListOracleRounds
     */
    listOracleRounds(input: ListOracleRoundsRequest, options?: RpcOptions): UnaryCall<ListOracleRoundsRequest, RoundList>;
    /**
     * @generated from protobuf rpc: GetMilestone
     */
    getMilestone(input: GetMilestoneRequest, options?: RpcOptions): UnaryCall<GetMilestoneRequest, MilestoneDetail>;
    /**
     * @generated from protobuf rpc: ListMilestones
     */
    listMilestones(input: ListMilestonesRequest, options?: RpcOptions): UnaryCall<ListMilestonesRequest, MilestoneList>;
    /**
     * @generated from protobuf rpc: GetSettlement
     */
    getSettlement(input: GetSettlementRequest, options?: RpcOptions): UnaryCall<GetSettlementRequest, SettlementDetail>;
    /**
     * @generated from protobuf rpc: ListSettlements
     */
    listSettlements(input: ListSettlementsRequest, options?: RpcOptions): UnaryCall<ListSettlementsRequest, SettlementList>;
    /**
     * @generated from protobuf rpc: GetContract
     */
    getContract(input: GetContractRequest, options?: RpcOptions): UnaryCall<GetContractRequest, ContractDetail>;
    /**
     * @generated from protobuf rpc: ListContracts
     */
    listContracts(input: ListContractsRequest, options?: RpcOptions): UnaryCall<ListContractsRequest, ContractList>;
    /**
     * @generated from protobuf rpc: GetCode
     */
    getCode(input: GetCodeRequest, options?: RpcOptions): UnaryCall<GetCodeRequest, CodeDetail>;
    /**
     * @generated from protobuf rpc: ListCodes
     */
    listCodes(input: ListCodesRequest, options?: RpcOptions): UnaryCall<ListCodesRequest, CodeList>;
    /**
     * @generated from protobuf rpc: GetGovernanceProposal
     */
    getGovernanceProposal(input: GetProposalRequest, options?: RpcOptions): UnaryCall<GetProposalRequest, ProposalDetail>;
    /**
     * @generated from protobuf rpc: ListProposals
     */
    listProposals(input: ListProposalsRequest, options?: RpcOptions): UnaryCall<ListProposalsRequest, ProposalList>;
    /**
     * @generated from protobuf rpc: ListIbcChannels
     */
    listIbcChannels(input: ListIbcChannelsRequest, options?: RpcOptions): UnaryCall<ListIbcChannelsRequest, IbcChannelList>;
    /**
     * @generated from protobuf rpc: GetIbcChannel
     */
    getIbcChannel(input: GetIbcChannelRequest, options?: RpcOptions): UnaryCall<GetIbcChannelRequest, IbcChannelDetail>;
    /**
     * @generated from protobuf rpc: ListIbcAssets
     */
    listIbcAssets(input: ListIbcAssetsRequest, options?: RpcOptions): UnaryCall<ListIbcAssetsRequest, IbcAssetList>;
    /**
     * @generated from protobuf rpc: GetCw20Token
     */
    getCw20Token(input: GetCw20TokenRequest, options?: RpcOptions): UnaryCall<GetCw20TokenRequest, Cw20TokenDetail>;
    /**
     * @generated from protobuf rpc: GetCw721Collection
     */
    getCw721Collection(input: GetCw721CollectionRequest, options?: RpcOptions): UnaryCall<GetCw721CollectionRequest, Cw721CollectionDetail>;
    /**
     * @generated from protobuf rpc: GetCw721Token
     */
    getCw721Token(input: GetCw721TokenRequest, options?: RpcOptions): UnaryCall<GetCw721TokenRequest, Cw721TokenDetail>;
    /**
     * @generated from protobuf rpc: StreamLatestBlocks
     */
    streamLatestBlocks(input: StreamBlocksRequest, options?: RpcOptions): ServerStreamingCall<StreamBlocksRequest, BlockSummary>;
    /**
     * @generated from protobuf rpc: StreamConsensusRound
     */
    streamConsensusRound(input: StreamConsensusRequest, options?: RpcOptions): ServerStreamingCall<StreamConsensusRequest, ConsensusRound>;
    /**
     * @generated from protobuf rpc: GetBridgeTx
     */
    getBridgeTx(input: GetBridgeTxRequest, options?: RpcOptions): UnaryCall<GetBridgeTxRequest, BridgeTxDetail>;
    /**
     * @generated from protobuf rpc: ListBridgeTxs
     */
    listBridgeTxs(input: ListBridgeTxsRequest, options?: RpcOptions): UnaryCall<ListBridgeTxsRequest, BridgeTxList>;
    /**
     * @generated from protobuf rpc: GetBridgeSupplyMetrics
     */
    getBridgeSupplyMetrics(input: GetBridgeSupplyMetricsRequest, options?: RpcOptions): UnaryCall<GetBridgeSupplyMetricsRequest, SupplyMetrics>;
    /**
     * @generated from protobuf rpc: ListRelayers
     */
    listRelayers(input: ListRelayersRequest, options?: RpcOptions): UnaryCall<ListRelayersRequest, RelayerList>;
    /**
     * @generated from protobuf rpc: ListBridgeCircuitBreaker
     */
    listBridgeCircuitBreaker(input: ListBridgeCircuitBreakerRequest, options?: RpcOptions): UnaryCall<ListBridgeCircuitBreakerRequest, CircuitBreakerHistory>;
    /**
     * @generated from protobuf rpc: ListBridgeNonces
     */
    listBridgeNonces(input: ListBridgeNoncesRequest, options?: RpcOptions): UnaryCall<ListBridgeNoncesRequest, NonceRegistryDetail>;
    /**
     * @generated from protobuf rpc: GetTpsHistory
     */
    getTpsHistory(input: GetTpsRequest, options?: RpcOptions): UnaryCall<GetTpsRequest, TpsHistory>;
    /**
     * @generated from protobuf rpc: GetBlockTimeHistory
     */
    getBlockTimeHistory(input: GetBlockTimeRequest, options?: RpcOptions): UnaryCall<GetBlockTimeRequest, BlockTimeHistory>;
    /**
     * @generated from protobuf rpc: GetValidatorUptimeGrid
     */
    getValidatorUptimeGrid(input: GetUptimeRequest, options?: RpcOptions): UnaryCall<GetUptimeRequest, UptimeHeatmap>;
    /**
     * @generated from protobuf rpc: GetBridgeVolumeHistory
     */
    getBridgeVolumeHistory(input: GetBridgeVolumeRequest, options?: RpcOptions): UnaryCall<GetBridgeVolumeRequest, VolumeHistory>;
    /**
     * @generated from protobuf rpc: ExportTxsCsv
     */
    exportTxsCsv(input: ExportTxsCsvRequest, options?: RpcOptions): ServerStreamingCall<ExportTxsCsvRequest, CsvChunk>;
    /**
     * @generated from protobuf rpc: SearchGlobal
     */
    searchGlobal(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse>;
    /**
     * @generated from protobuf rpc: RegisterWebhook
     */
    registerWebhook(input: RegisterWebhookRequest, options?: RpcOptions): UnaryCall<RegisterWebhookRequest, WebhookDetail>;
    /**
     * @generated from protobuf rpc: ListWebhooks
     */
    listWebhooks(input: ListWebhooksRequest, options?: RpcOptions): UnaryCall<ListWebhooksRequest, WebhookList>;
    /**
     * @generated from protobuf rpc: DeleteWebhook
     */
    deleteWebhook(input: DeleteWebhookRequest, options?: RpcOptions): UnaryCall<DeleteWebhookRequest, DeleteWebhookResponse>;
    /**
     * @generated from protobuf rpc: GetSystemStatus
     */
    getSystemStatus(input: GetSystemStatusRequest, options?: RpcOptions): UnaryCall<GetSystemStatusRequest, SystemStatus>;
}
/**
 * @generated from protobuf service explorer.v1.ExplorerService
 */
export class ExplorerServiceClient implements IExplorerServiceClient, ServiceInfo {
    typeName = ExplorerService.typeName;
    methods = ExplorerService.methods;
    options = ExplorerService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetBlock
     */
    getBlock(input: GetBlockRequest, options?: RpcOptions): UnaryCall<GetBlockRequest, BlockDetail> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBlockRequest, BlockDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListBlocks
     */
    listBlocks(input: ListBlocksRequest, options?: RpcOptions): UnaryCall<ListBlocksRequest, BlockList> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBlocksRequest, BlockList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTx
     */
    getTx(input: GetTxRequest, options?: RpcOptions): UnaryCall<GetTxRequest, TxDetail> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTxRequest, TxDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTxs
     */
    listTxs(input: ListTxsRequest, options?: RpcOptions): UnaryCall<ListTxsRequest, TxList> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTxsRequest, TxList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTxsByAddress
     */
    listTxsByAddress(input: ListTxsByAddressRequest, options?: RpcOptions): UnaryCall<ListTxsByAddressRequest, TxList> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTxsByAddressRequest, TxList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAddress
     */
    getAddress(input: GetAddressRequest, options?: RpcOptions): UnaryCall<GetAddressRequest, AccountDetail> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAddressRequest, AccountDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetValidator
     */
    getValidator(input: GetValidatorRequest, options?: RpcOptions): UnaryCall<GetValidatorRequest, ValidatorDetail> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetValidatorRequest, ValidatorDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListValidators
     */
    listValidators(input: ListValidatorsRequest, options?: RpcOptions): UnaryCall<ListValidatorsRequest, ValidatorSlotGrid> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListValidatorsRequest, ValidatorSlotGrid>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetStakingStats
     */
    getStakingStats(input: GetStakingStatsRequest, options?: RpcOptions): UnaryCall<GetStakingStatsRequest, StakingStats> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetStakingStatsRequest, StakingStats>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetOracleFeed
     */
    getOracleFeed(input: GetOracleFeedRequest, options?: RpcOptions): UnaryCall<GetOracleFeedRequest, FeedDetail> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOracleFeedRequest, FeedDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetOracleRound
     */
    getOracleRound(input: GetOracleRoundRequest, options?: RpcOptions): UnaryCall<GetOracleRoundRequest, RoundDetail> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOracleRoundRequest, RoundDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListOracleRounds
     */
    listOracleRounds(input: ListOracleRoundsRequest, options?: RpcOptions): UnaryCall<ListOracleRoundsRequest, RoundList> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListOracleRoundsRequest, RoundList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMilestone
     */
    getMilestone(input: GetMilestoneRequest, options?: RpcOptions): UnaryCall<GetMilestoneRequest, MilestoneDetail> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMilestoneRequest, MilestoneDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMilestones
     */
    listMilestones(input: ListMilestonesRequest, options?: RpcOptions): UnaryCall<ListMilestonesRequest, MilestoneList> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMilestonesRequest, MilestoneList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSettlement
     */
    getSettlement(input: GetSettlementRequest, options?: RpcOptions): UnaryCall<GetSettlementRequest, SettlementDetail> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSettlementRequest, SettlementDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSettlements
     */
    listSettlements(input: ListSettlementsRequest, options?: RpcOptions): UnaryCall<ListSettlementsRequest, SettlementList> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSettlementsRequest, SettlementList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetContract
     */
    getContract(input: GetContractRequest, options?: RpcOptions): UnaryCall<GetContractRequest, ContractDetail> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetContractRequest, ContractDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListContracts
     */
    listContracts(input: ListContractsRequest, options?: RpcOptions): UnaryCall<ListContractsRequest, ContractList> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListContractsRequest, ContractList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCode
     */
    getCode(input: GetCodeRequest, options?: RpcOptions): UnaryCall<GetCodeRequest, CodeDetail> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCodeRequest, CodeDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCodes
     */
    listCodes(input: ListCodesRequest, options?: RpcOptions): UnaryCall<ListCodesRequest, CodeList> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCodesRequest, CodeList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetGovernanceProposal
     */
    getGovernanceProposal(input: GetProposalRequest, options?: RpcOptions): UnaryCall<GetProposalRequest, ProposalDetail> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProposalRequest, ProposalDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListProposals
     */
    listProposals(input: ListProposalsRequest, options?: RpcOptions): UnaryCall<ListProposalsRequest, ProposalList> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListProposalsRequest, ProposalList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListIbcChannels
     */
    listIbcChannels(input: ListIbcChannelsRequest, options?: RpcOptions): UnaryCall<ListIbcChannelsRequest, IbcChannelList> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListIbcChannelsRequest, IbcChannelList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetIbcChannel
     */
    getIbcChannel(input: GetIbcChannelRequest, options?: RpcOptions): UnaryCall<GetIbcChannelRequest, IbcChannelDetail> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetIbcChannelRequest, IbcChannelDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListIbcAssets
     */
    listIbcAssets(input: ListIbcAssetsRequest, options?: RpcOptions): UnaryCall<ListIbcAssetsRequest, IbcAssetList> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListIbcAssetsRequest, IbcAssetList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCw20Token
     */
    getCw20Token(input: GetCw20TokenRequest, options?: RpcOptions): UnaryCall<GetCw20TokenRequest, Cw20TokenDetail> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCw20TokenRequest, Cw20TokenDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCw721Collection
     */
    getCw721Collection(input: GetCw721CollectionRequest, options?: RpcOptions): UnaryCall<GetCw721CollectionRequest, Cw721CollectionDetail> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCw721CollectionRequest, Cw721CollectionDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCw721Token
     */
    getCw721Token(input: GetCw721TokenRequest, options?: RpcOptions): UnaryCall<GetCw721TokenRequest, Cw721TokenDetail> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCw721TokenRequest, Cw721TokenDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StreamLatestBlocks
     */
    streamLatestBlocks(input: StreamBlocksRequest, options?: RpcOptions): ServerStreamingCall<StreamBlocksRequest, BlockSummary> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamBlocksRequest, BlockSummary>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StreamConsensusRound
     */
    streamConsensusRound(input: StreamConsensusRequest, options?: RpcOptions): ServerStreamingCall<StreamConsensusRequest, ConsensusRound> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamConsensusRequest, ConsensusRound>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBridgeTx
     */
    getBridgeTx(input: GetBridgeTxRequest, options?: RpcOptions): UnaryCall<GetBridgeTxRequest, BridgeTxDetail> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBridgeTxRequest, BridgeTxDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListBridgeTxs
     */
    listBridgeTxs(input: ListBridgeTxsRequest, options?: RpcOptions): UnaryCall<ListBridgeTxsRequest, BridgeTxList> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBridgeTxsRequest, BridgeTxList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBridgeSupplyMetrics
     */
    getBridgeSupplyMetrics(input: GetBridgeSupplyMetricsRequest, options?: RpcOptions): UnaryCall<GetBridgeSupplyMetricsRequest, SupplyMetrics> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBridgeSupplyMetricsRequest, SupplyMetrics>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListRelayers
     */
    listRelayers(input: ListRelayersRequest, options?: RpcOptions): UnaryCall<ListRelayersRequest, RelayerList> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRelayersRequest, RelayerList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListBridgeCircuitBreaker
     */
    listBridgeCircuitBreaker(input: ListBridgeCircuitBreakerRequest, options?: RpcOptions): UnaryCall<ListBridgeCircuitBreakerRequest, CircuitBreakerHistory> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBridgeCircuitBreakerRequest, CircuitBreakerHistory>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListBridgeNonces
     */
    listBridgeNonces(input: ListBridgeNoncesRequest, options?: RpcOptions): UnaryCall<ListBridgeNoncesRequest, NonceRegistryDetail> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBridgeNoncesRequest, NonceRegistryDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTpsHistory
     */
    getTpsHistory(input: GetTpsRequest, options?: RpcOptions): UnaryCall<GetTpsRequest, TpsHistory> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTpsRequest, TpsHistory>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlockTimeHistory
     */
    getBlockTimeHistory(input: GetBlockTimeRequest, options?: RpcOptions): UnaryCall<GetBlockTimeRequest, BlockTimeHistory> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBlockTimeRequest, BlockTimeHistory>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetValidatorUptimeGrid
     */
    getValidatorUptimeGrid(input: GetUptimeRequest, options?: RpcOptions): UnaryCall<GetUptimeRequest, UptimeHeatmap> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUptimeRequest, UptimeHeatmap>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBridgeVolumeHistory
     */
    getBridgeVolumeHistory(input: GetBridgeVolumeRequest, options?: RpcOptions): UnaryCall<GetBridgeVolumeRequest, VolumeHistory> {
        const method = this.methods[39], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBridgeVolumeRequest, VolumeHistory>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ExportTxsCsv
     */
    exportTxsCsv(input: ExportTxsCsvRequest, options?: RpcOptions): ServerStreamingCall<ExportTxsCsvRequest, CsvChunk> {
        const method = this.methods[40], opt = this._transport.mergeOptions(options);
        return stackIntercept<ExportTxsCsvRequest, CsvChunk>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchGlobal
     */
    searchGlobal(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse> {
        const method = this.methods[41], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchRequest, SearchResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterWebhook
     */
    registerWebhook(input: RegisterWebhookRequest, options?: RpcOptions): UnaryCall<RegisterWebhookRequest, WebhookDetail> {
        const method = this.methods[42], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterWebhookRequest, WebhookDetail>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListWebhooks
     */
    listWebhooks(input: ListWebhooksRequest, options?: RpcOptions): UnaryCall<ListWebhooksRequest, WebhookList> {
        const method = this.methods[43], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListWebhooksRequest, WebhookList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteWebhook
     */
    deleteWebhook(input: DeleteWebhookRequest, options?: RpcOptions): UnaryCall<DeleteWebhookRequest, DeleteWebhookResponse> {
        const method = this.methods[44], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteWebhookRequest, DeleteWebhookResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSystemStatus
     */
    getSystemStatus(input: GetSystemStatusRequest, options?: RpcOptions): UnaryCall<GetSystemStatusRequest, SystemStatus> {
        const method = this.methods[45], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSystemStatusRequest, SystemStatus>("unary", this._transport, method, opt, input);
    }
}
