// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: relayer/v1/relayer.proto

package relayerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayerService_SubmitSignature_FullMethodName    = "/relayer.v1.RelayerService/SubmitSignature"
	RelayerService_GetCommitteeNonces_FullMethodName = "/relayer.v1.RelayerService/GetCommitteeNonces"
)

// RelayerServiceClient is the client API for RelayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayerServiceClient interface {
	SubmitSignature(ctx context.Context, in *SubmitSignatureRequest, opts ...grpc.CallOption) (*SubmitSignatureResponse, error)
	GetCommitteeNonces(ctx context.Context, in *GetCommitteeNoncesRequest, opts ...grpc.CallOption) (*GetCommitteeNoncesResponse, error)
}

type relayerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayerServiceClient(cc grpc.ClientConnInterface) RelayerServiceClient {
	return &relayerServiceClient{cc}
}

func (c *relayerServiceClient) SubmitSignature(ctx context.Context, in *SubmitSignatureRequest, opts ...grpc.CallOption) (*SubmitSignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSignatureResponse)
	err := c.cc.Invoke(ctx, RelayerService_SubmitSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayerServiceClient) GetCommitteeNonces(ctx context.Context, in *GetCommitteeNoncesRequest, opts ...grpc.CallOption) (*GetCommitteeNoncesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommitteeNoncesResponse)
	err := c.cc.Invoke(ctx, RelayerService_GetCommitteeNonces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayerServiceServer is the server API for RelayerService service.
// All implementations must embed UnimplementedRelayerServiceServer
// for forward compatibility.
type RelayerServiceServer interface {
	SubmitSignature(context.Context, *SubmitSignatureRequest) (*SubmitSignatureResponse, error)
	GetCommitteeNonces(context.Context, *GetCommitteeNoncesRequest) (*GetCommitteeNoncesResponse, error)
	mustEmbedUnimplementedRelayerServiceServer()
}

// UnimplementedRelayerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayerServiceServer struct{}

func (UnimplementedRelayerServiceServer) SubmitSignature(context.Context, *SubmitSignatureRequest) (*SubmitSignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSignature not implemented")
}
func (UnimplementedRelayerServiceServer) GetCommitteeNonces(context.Context, *GetCommitteeNoncesRequest) (*GetCommitteeNoncesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommitteeNonces not implemented")
}
func (UnimplementedRelayerServiceServer) mustEmbedUnimplementedRelayerServiceServer() {}
func (UnimplementedRelayerServiceServer) testEmbeddedByValue()                        {}

// UnsafeRelayerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayerServiceServer will
// result in compilation errors.
type UnsafeRelayerServiceServer interface {
	mustEmbedUnimplementedRelayerServiceServer()
}

func RegisterRelayerServiceServer(s grpc.ServiceRegistrar, srv RelayerServiceServer) {
	// If the following call panics, it indicates UnimplementedRelayerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayerService_ServiceDesc, srv)
}

func _RelayerService_SubmitSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerServiceServer).SubmitSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayerService_SubmitSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerServiceServer).SubmitSignature(ctx, req.(*SubmitSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayerService_GetCommitteeNonces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitteeNoncesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerServiceServer).GetCommitteeNonces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayerService_GetCommitteeNonces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerServiceServer).GetCommitteeNonces(ctx, req.(*GetCommitteeNoncesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayerService_ServiceDesc is the grpc.ServiceDesc for RelayerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relayer.v1.RelayerService",
	HandlerType: (*RelayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitSignature",
			Handler:    _RelayerService_SubmitSignature_Handler,
		},
		{
			MethodName: "GetCommitteeNonces",
			Handler:    _RelayerService_GetCommitteeNonces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relayer/v1/relayer.proto",
}
