// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relayer/v1/relayer.proto

package relayerv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitSignatureRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommitteeId      string                 `protobuf:"bytes,1,opt,name=committee_id,json=committeeId,proto3" json:"committee_id,omitempty"`
	Nonce            uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature        string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // e.g., hex-encoded signature
	ValidatorAddress string                 `protobuf:"bytes,4,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitSignatureRequest) Reset() {
	*x = SubmitSignatureRequest{}
	mi := &file_relayer_v1_relayer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSignatureRequest) ProtoMessage() {}

func (x *SubmitSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_v1_relayer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSignatureRequest.ProtoReflect.Descriptor instead.
func (*SubmitSignatureRequest) Descriptor() ([]byte, []int) {
	return file_relayer_v1_relayer_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitSignatureRequest) GetCommitteeId() string {
	if x != nil {
		return x.CommitteeId
	}
	return ""
}

func (x *SubmitSignatureRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *SubmitSignatureRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SubmitSignatureRequest) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

type SubmitSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSignatureResponse) Reset() {
	*x = SubmitSignatureResponse{}
	mi := &file_relayer_v1_relayer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSignatureResponse) ProtoMessage() {}

func (x *SubmitSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_v1_relayer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSignatureResponse.ProtoReflect.Descriptor instead.
func (*SubmitSignatureResponse) Descriptor() ([]byte, []int) {
	return file_relayer_v1_relayer_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitSignatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitSignatureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCommitteeNoncesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitteeId   string                 `protobuf:"bytes,1,opt,name=committee_id,json=committeeId,proto3" json:"committee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitteeNoncesRequest) Reset() {
	*x = GetCommitteeNoncesRequest{}
	mi := &file_relayer_v1_relayer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitteeNoncesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitteeNoncesRequest) ProtoMessage() {}

func (x *GetCommitteeNoncesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_v1_relayer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitteeNoncesRequest.ProtoReflect.Descriptor instead.
func (*GetCommitteeNoncesRequest) Descriptor() ([]byte, []int) {
	return file_relayer_v1_relayer_proto_rawDescGZIP(), []int{2}
}

func (x *GetCommitteeNoncesRequest) GetCommitteeId() string {
	if x != nil {
		return x.CommitteeId
	}
	return ""
}

type GetCommitteeNoncesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitteeId   string                 `protobuf:"bytes,1,opt,name=committee_id,json=committeeId,proto3" json:"committee_id,omitempty"`
	CurrentNonce  uint64                 `protobuf:"varint,2,opt,name=current_nonce,json=currentNonce,proto3" json:"current_nonce,omitempty"`
	ExpectedNonce uint64                 `protobuf:"varint,3,opt,name=expected_nonce,json=expectedNonce,proto3" json:"expected_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitteeNoncesResponse) Reset() {
	*x = GetCommitteeNoncesResponse{}
	mi := &file_relayer_v1_relayer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitteeNoncesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitteeNoncesResponse) ProtoMessage() {}

func (x *GetCommitteeNoncesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_v1_relayer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitteeNoncesResponse.ProtoReflect.Descriptor instead.
func (*GetCommitteeNoncesResponse) Descriptor() ([]byte, []int) {
	return file_relayer_v1_relayer_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommitteeNoncesResponse) GetCommitteeId() string {
	if x != nil {
		return x.CommitteeId
	}
	return ""
}

func (x *GetCommitteeNoncesResponse) GetCurrentNonce() uint64 {
	if x != nil {
		return x.CurrentNonce
	}
	return 0
}

func (x *GetCommitteeNoncesResponse) GetExpectedNonce() uint64 {
	if x != nil {
		return x.ExpectedNonce
	}
	return 0
}

var File_relayer_v1_relayer_proto protoreflect.FileDescriptor

const file_relayer_v1_relayer_proto_rawDesc = "" +
	"\n" +
	"\x18relayer/v1/relayer.proto\x12\n" +
	"relayer.v1\x1a\x1cgoogle/api/annotations.proto\"\x9c\x01\n" +
	"\x16SubmitSignatureRequest\x12!\n" +
	"\fcommittee_id\x18\x01 \x01(\tR\vcommitteeId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12+\n" +
	"\x11validator_address\x18\x04 \x01(\tR\x10validatorAddress\"M\n" +
	"\x17SubmitSignatureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x19GetCommitteeNoncesRequest\x12!\n" +
	"\fcommittee_id\x18\x01 \x01(\tR\vcommitteeId\"\x8b\x01\n" +
	"\x1aGetCommitteeNoncesResponse\x12!\n" +
	"\fcommittee_id\x18\x01 \x01(\tR\vcommitteeId\x12#\n" +
	"\rcurrent_nonce\x18\x02 \x01(\x04R\fcurrentNonce\x12%\n" +
	"\x0eexpected_nonce\x18\x03 \x01(\x04R\rexpectedNonce2\xa3\x02\n" +
	"\x0eRelayerService\x12\x85\x01\n" +
	"\x0fSubmitSignature\x12\".relayer.v1.SubmitSignatureRequest\x1a#.relayer.v1.SubmitSignatureResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/rest/v1/relayer/signature\x12\x88\x01\n" +
	"\x12GetCommitteeNonces\x12%.relayer.v1.GetCommitteeNoncesRequest\x1a&.relayer.v1.GetCommitteeNoncesResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/rest/v1/relayer/noncesB8Z6github.com/sovereign-l1/chain/api/relayer/v1;relayerv1b\x06proto3"

var (
	file_relayer_v1_relayer_proto_rawDescOnce sync.Once
	file_relayer_v1_relayer_proto_rawDescData []byte
)

func file_relayer_v1_relayer_proto_rawDescGZIP() []byte {
	file_relayer_v1_relayer_proto_rawDescOnce.Do(func() {
		file_relayer_v1_relayer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relayer_v1_relayer_proto_rawDesc), len(file_relayer_v1_relayer_proto_rawDesc)))
	})
	return file_relayer_v1_relayer_proto_rawDescData
}

var file_relayer_v1_relayer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_relayer_v1_relayer_proto_goTypes = []any{
	(*SubmitSignatureRequest)(nil),     // 0: relayer.v1.SubmitSignatureRequest
	(*SubmitSignatureResponse)(nil),    // 1: relayer.v1.SubmitSignatureResponse
	(*GetCommitteeNoncesRequest)(nil),  // 2: relayer.v1.GetCommitteeNoncesRequest
	(*GetCommitteeNoncesResponse)(nil), // 3: relayer.v1.GetCommitteeNoncesResponse
}
var file_relayer_v1_relayer_proto_depIdxs = []int32{
	0, // 0: relayer.v1.RelayerService.SubmitSignature:input_type -> relayer.v1.SubmitSignatureRequest
	2, // 1: relayer.v1.RelayerService.GetCommitteeNonces:input_type -> relayer.v1.GetCommitteeNoncesRequest
	1, // 2: relayer.v1.RelayerService.SubmitSignature:output_type -> relayer.v1.SubmitSignatureResponse
	3, // 3: relayer.v1.RelayerService.GetCommitteeNonces:output_type -> relayer.v1.GetCommitteeNoncesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relayer_v1_relayer_proto_init() }
func file_relayer_v1_relayer_proto_init() {
	if File_relayer_v1_relayer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relayer_v1_relayer_proto_rawDesc), len(file_relayer_v1_relayer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relayer_v1_relayer_proto_goTypes,
		DependencyIndexes: file_relayer_v1_relayer_proto_depIdxs,
		MessageInfos:      file_relayer_v1_relayer_proto_msgTypes,
	}.Build()
	File_relayer_v1_relayer_proto = out.File
	file_relayer_v1_relayer_proto_goTypes = nil
	file_relayer_v1_relayer_proto_depIdxs = nil
}
