apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-write
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  # --- Local hostPath Deployment (For local cluster / testing) ---
  hostPath:
    path: /mnt/data/db-write
    type: DirectoryOrCreate
  # --- NFS Storage Deployment (Production reference) ---
  # nfs:
  #   path: /mnt/nfs_share/
  #   server: 74.220.21.187
  claimRef:
    name: db-write-data-db-write-0
    namespace: sovereign-chain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-read
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  # --- Local hostPath Deployment (For local cluster / testing) ---
  hostPath:
    path: /mnt/data/db-read
    type: DirectoryOrCreate
  # --- NFS Storage Deployment (Production reference) ---
  # nfs:
  #   path: /mnt/nfs_share/
  #   server: 74.220.21.187
  claimRef:
    name: db-read-data-db-read-0
    namespace: sovereign-chain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-relayer
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  # --- Local hostPath Deployment (For local cluster / testing) ---
  hostPath:
    path: /mnt/data/db-relayer
    type: DirectoryOrCreate
  # --- NFS Storage Deployment (Production reference) ---
  # nfs:
  #   path: /mnt/nfs_share/
  #   server: 74.220.21.187
  claimRef:
    name: db-relayer-data-db-relayer-0
    namespace: sovereign-chain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nats-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  # --- Local hostPath Deployment (For local cluster / testing) ---
  hostPath:
    path: /mnt/data/nats-0
    type: DirectoryOrCreate
  # --- NFS Storage Deployment (Production reference) ---
  # nfs:
  #   path: /mnt/nfs_share/
  #   server: 74.220.21.187
  claimRef:
    name: nats-data-nats-0
    namespace: sovereign-chain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nats-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  # --- Local hostPath Deployment (For local cluster / testing) ---
  hostPath:
    path: /mnt/data/nats-1
    type: DirectoryOrCreate
  # --- NFS Storage Deployment (Production reference) ---
  # nfs:
  #   path: /mnt/nfs_share/
  #   server: 74.220.21.187
  claimRef:
    name: nats-data-nats-1
    namespace: sovereign-chain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nats-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  # --- Local hostPath Deployment (For local cluster / testing) ---
  hostPath:
    path: /mnt/data/nats-2
    type: DirectoryOrCreate
  # --- NFS Storage Deployment (Production reference) ---
  # nfs:
  #   path: /mnt/nfs_share/
  #   server: 74.220.21.187
  claimRef:
    name: nats-data-nats-2
    namespace: sovereign-chain
