apiVersion: v1
kind: PersistentVolume
metadata:
  name: sovereign-pv
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # --- NFS Storage Deployment (Production) ---
  nfs:
    path: /mnt/nfs_share/
    server: 74.220.21.187 # Overridden by config.env / deployment script if needed
  
  # --- Local hostPath Deployment (For local cluster / testing) ---
  # hostPath:
  #   path: /mnt/data/
  #   type: DirectoryOrCreate
