apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet-deployment
  namespace: sovereign-backend
  labels:
    app: faucet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faucet
  template:
    metadata:
      labels:
        app: faucet
    spec:
      containers:
        - name: faucet
          image: sovereign-l1/faucet:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: NODE_URL
              value: "http://chain-node:26657"
            - name: FAUCET_KEY
              value: "faucet"
            - name: DENOM
              value: "usov"
            - name: FAUCET_AMOUNT
              value: "10000000"
---
apiVersion: v1
kind: Service
metadata:
  name: faucet-service
  namespace: sovereign-backend
spec:
  selector:
    app: faucet
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
