// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "relayer/v1/relayer.proto" (package "relayer.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RelayerService } from "./relayer";
import type { GetCommitteeNoncesResponse } from "./relayer";
import type { GetCommitteeNoncesRequest } from "./relayer";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SubmitSignatureResponse } from "./relayer";
import type { SubmitSignatureRequest } from "./relayer";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service relayer.v1.RelayerService
 */
export interface IRelayerServiceClient {
    /**
     * @generated from protobuf rpc: SubmitSignature
     */
    submitSignature(input: SubmitSignatureRequest, options?: RpcOptions): UnaryCall<SubmitSignatureRequest, SubmitSignatureResponse>;
    /**
     * @generated from protobuf rpc: GetCommitteeNonces
     */
    getCommitteeNonces(input: GetCommitteeNoncesRequest, options?: RpcOptions): UnaryCall<GetCommitteeNoncesRequest, GetCommitteeNoncesResponse>;
}
/**
 * @generated from protobuf service relayer.v1.RelayerService
 */
export class RelayerServiceClient implements IRelayerServiceClient, ServiceInfo {
    typeName = RelayerService.typeName;
    methods = RelayerService.methods;
    options = RelayerService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SubmitSignature
     */
    submitSignature(input: SubmitSignatureRequest, options?: RpcOptions): UnaryCall<SubmitSignatureRequest, SubmitSignatureResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SubmitSignatureRequest, SubmitSignatureResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCommitteeNonces
     */
    getCommitteeNonces(input: GetCommitteeNoncesRequest, options?: RpcOptions): UnaryCall<GetCommitteeNoncesRequest, GetCommitteeNoncesResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCommitteeNoncesRequest, GetCommitteeNoncesResponse>("unary", this._transport, method, opt, input);
    }
}
