// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "relayer/v1/relayer.proto" (package "relayer.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message relayer.v1.SubmitSignatureRequest
 */
export interface SubmitSignatureRequest {
    /**
     * @generated from protobuf field: string committee_id = 1
     */
    committeeId: string;
    /**
     * @generated from protobuf field: uint64 nonce = 2
     */
    nonce: string;
    /**
     * @generated from protobuf field: string signature = 3
     */
    signature: string; // e.g., hex-encoded signature
    /**
     * @generated from protobuf field: string validator_address = 4
     */
    validatorAddress: string;
}
/**
 * @generated from protobuf message relayer.v1.SubmitSignatureResponse
 */
export interface SubmitSignatureResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message relayer.v1.GetCommitteeNoncesRequest
 */
export interface GetCommitteeNoncesRequest {
    /**
     * @generated from protobuf field: string committee_id = 1
     */
    committeeId: string;
}
/**
 * @generated from protobuf message relayer.v1.GetCommitteeNoncesResponse
 */
export interface GetCommitteeNoncesResponse {
    /**
     * @generated from protobuf field: string committee_id = 1
     */
    committeeId: string;
    /**
     * @generated from protobuf field: uint64 current_nonce = 2
     */
    currentNonce: string;
    /**
     * @generated from protobuf field: uint64 expected_nonce = 3
     */
    expectedNonce: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class SubmitSignatureRequest$Type extends MessageType<SubmitSignatureRequest> {
    constructor() {
        super("relayer.v1.SubmitSignatureRequest", [
            { no: 1, name: "committee_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "nonce", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 3, name: "signature", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "validator_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SubmitSignatureRequest>): SubmitSignatureRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.committeeId = "";
        message.nonce = "0";
        message.signature = "";
        message.validatorAddress = "";
        if (value !== undefined)
            reflectionMergePartial<SubmitSignatureRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubmitSignatureRequest): SubmitSignatureRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string committee_id */ 1:
                    message.committeeId = reader.string();
                    break;
                case /* uint64 nonce */ 2:
                    message.nonce = reader.uint64().toString();
                    break;
                case /* string signature */ 3:
                    message.signature = reader.string();
                    break;
                case /* string validator_address */ 4:
                    message.validatorAddress = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubmitSignatureRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string committee_id = 1; */
        if (message.committeeId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.committeeId);
        /* uint64 nonce = 2; */
        if (message.nonce !== "0")
            writer.tag(2, WireType.Varint).uint64(message.nonce);
        /* string signature = 3; */
        if (message.signature !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.signature);
        /* string validator_address = 4; */
        if (message.validatorAddress !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.validatorAddress);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message relayer.v1.SubmitSignatureRequest
 */
export const SubmitSignatureRequest = new SubmitSignatureRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubmitSignatureResponse$Type extends MessageType<SubmitSignatureResponse> {
    constructor() {
        super("relayer.v1.SubmitSignatureResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SubmitSignatureResponse>): SubmitSignatureResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<SubmitSignatureResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubmitSignatureResponse): SubmitSignatureResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubmitSignatureResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message relayer.v1.SubmitSignatureResponse
 */
export const SubmitSignatureResponse = new SubmitSignatureResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCommitteeNoncesRequest$Type extends MessageType<GetCommitteeNoncesRequest> {
    constructor() {
        super("relayer.v1.GetCommitteeNoncesRequest", [
            { no: 1, name: "committee_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetCommitteeNoncesRequest>): GetCommitteeNoncesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.committeeId = "";
        if (value !== undefined)
            reflectionMergePartial<GetCommitteeNoncesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCommitteeNoncesRequest): GetCommitteeNoncesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string committee_id */ 1:
                    message.committeeId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCommitteeNoncesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string committee_id = 1; */
        if (message.committeeId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.committeeId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message relayer.v1.GetCommitteeNoncesRequest
 */
export const GetCommitteeNoncesRequest = new GetCommitteeNoncesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCommitteeNoncesResponse$Type extends MessageType<GetCommitteeNoncesResponse> {
    constructor() {
        super("relayer.v1.GetCommitteeNoncesResponse", [
            { no: 1, name: "committee_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "current_nonce", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 3, name: "expected_nonce", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetCommitteeNoncesResponse>): GetCommitteeNoncesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.committeeId = "";
        message.currentNonce = "0";
        message.expectedNonce = "0";
        if (value !== undefined)
            reflectionMergePartial<GetCommitteeNoncesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCommitteeNoncesResponse): GetCommitteeNoncesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string committee_id */ 1:
                    message.committeeId = reader.string();
                    break;
                case /* uint64 current_nonce */ 2:
                    message.currentNonce = reader.uint64().toString();
                    break;
                case /* uint64 expected_nonce */ 3:
                    message.expectedNonce = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCommitteeNoncesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string committee_id = 1; */
        if (message.committeeId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.committeeId);
        /* uint64 current_nonce = 2; */
        if (message.currentNonce !== "0")
            writer.tag(2, WireType.Varint).uint64(message.currentNonce);
        /* uint64 expected_nonce = 3; */
        if (message.expectedNonce !== "0")
            writer.tag(3, WireType.Varint).uint64(message.expectedNonce);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message relayer.v1.GetCommitteeNoncesResponse
 */
export const GetCommitteeNoncesResponse = new GetCommitteeNoncesResponse$Type();
/**
 * @generated ServiceType for protobuf service relayer.v1.RelayerService
 */
export const RelayerService = new ServiceType("relayer.v1.RelayerService", [
    { name: "SubmitSignature", options: { "google.api.http": { post: "/api/rest/v1/relayer/signature", body: "*" } }, I: SubmitSignatureRequest, O: SubmitSignatureResponse },
    { name: "GetCommitteeNonces", options: { "google.api.http": { get: "/api/rest/v1/relayer/nonces" } }, I: GetCommitteeNoncesRequest, O: GetCommitteeNoncesResponse }
]);
